<?php

namespace Numbers\Frontend\HTML\FontAwesome\Model;
class Icons extends \Object\Data {
	public $column_key = 'no_data_fontawesome_icon_code';
	public $column_prefix = 'no_data_fontawesome_icon_';
	public $columns = [
		'no_data_fontawesome_icon_code' => ['name' => 'Code', 'type' => 'text'],
		'no_data_fontawesome_icon_name' => ['name' => 'Name', 'type' => 'text'],
		'no_data_fontawesome_icon_unicode' => ['name' => 'Unicode', 'type' => 'text'],
	];
	public $options_map = [
		'no_data_fontawesome_icon_code' => 'name',
		'no_data_fontawesome_icon_code*' => 'icon_class'
	];
	public $orderby = [
		'no_data_fontawesome_icon_name' => SORT_ASC
	];
	public $data = [
		'500px' => ['no_data_fontawesome_icon_unicode' => '\f26e', 'no_data_fontawesome_icon_name' => '500px'],
		'address-book' => ['no_data_fontawesome_icon_unicode' => '\f2b9', 'no_data_fontawesome_icon_name' => 'Address book'],
		'address-book-o' => ['no_data_fontawesome_icon_unicode' => '\f2ba', 'no_data_fontawesome_icon_name' => 'Address book o'],
		'address-card' => ['no_data_fontawesome_icon_unicode' => '\f2bb', 'no_data_fontawesome_icon_name' => 'Address card'],
		'address-card-o' => ['no_data_fontawesome_icon_unicode' => '\f2bc', 'no_data_fontawesome_icon_name' => 'Address card o'],
		'adjust' => ['no_data_fontawesome_icon_unicode' => '\f042', 'no_data_fontawesome_icon_name' => 'Adjust'],
		'adn' => ['no_data_fontawesome_icon_unicode' => '\f170', 'no_data_fontawesome_icon_name' => 'Adn'],
		'align-center' => ['no_data_fontawesome_icon_unicode' => '\f037', 'no_data_fontawesome_icon_name' => 'Align center'],
		'align-justify' => ['no_data_fontawesome_icon_unicode' => '\f039', 'no_data_fontawesome_icon_name' => 'Align justify'],
		'align-left' => ['no_data_fontawesome_icon_unicode' => '\f036', 'no_data_fontawesome_icon_name' => 'Align left'],
		'align-right' => ['no_data_fontawesome_icon_unicode' => '\f038', 'no_data_fontawesome_icon_name' => 'Align right'],
		'amazon' => ['no_data_fontawesome_icon_unicode' => '\f270', 'no_data_fontawesome_icon_name' => 'Amazon'],
		'ambulance' => ['no_data_fontawesome_icon_unicode' => '\f0f9', 'no_data_fontawesome_icon_name' => 'Ambulance'],
		'american-sign-language-interpreting' => ['no_data_fontawesome_icon_unicode' => '\f2a3', 'no_data_fontawesome_icon_name' => 'American sign language interpreting'],
		'anchor' => ['no_data_fontawesome_icon_unicode' => '\f13d', 'no_data_fontawesome_icon_name' => 'Anchor'],
		'android' => ['no_data_fontawesome_icon_unicode' => '\f17b', 'no_data_fontawesome_icon_name' => 'Android'],
		'angellist' => ['no_data_fontawesome_icon_unicode' => '\f209', 'no_data_fontawesome_icon_name' => 'Angellist'],
		'angle-double-down' => ['no_data_fontawesome_icon_unicode' => '\f103', 'no_data_fontawesome_icon_name' => 'Angle double down'],
		'angle-double-left' => ['no_data_fontawesome_icon_unicode' => '\f100', 'no_data_fontawesome_icon_name' => 'Angle double left'],
		'angle-double-right' => ['no_data_fontawesome_icon_unicode' => '\f101', 'no_data_fontawesome_icon_name' => 'Angle double right'],
		'angle-double-up' => ['no_data_fontawesome_icon_unicode' => '\f102', 'no_data_fontawesome_icon_name' => 'Angle double up'],
		'angle-down' => ['no_data_fontawesome_icon_unicode' => '\f107', 'no_data_fontawesome_icon_name' => 'Angle down'],
		'angle-left' => ['no_data_fontawesome_icon_unicode' => '\f104', 'no_data_fontawesome_icon_name' => 'Angle left'],
		'angle-right' => ['no_data_fontawesome_icon_unicode' => '\f105', 'no_data_fontawesome_icon_name' => 'Angle right'],
		'angle-up' => ['no_data_fontawesome_icon_unicode' => '\f106', 'no_data_fontawesome_icon_name' => 'Angle up'],
		'apple' => ['no_data_fontawesome_icon_unicode' => '\f179', 'no_data_fontawesome_icon_name' => 'Apple'],
		'archive' => ['no_data_fontawesome_icon_unicode' => '\f187', 'no_data_fontawesome_icon_name' => 'Archive'],
		'area-chart' => ['no_data_fontawesome_icon_unicode' => '\f1fe', 'no_data_fontawesome_icon_name' => 'Area chart'],
		'arrow-circle-down' => ['no_data_fontawesome_icon_unicode' => '\f0ab', 'no_data_fontawesome_icon_name' => 'Arrow circle down'],
		'arrow-circle-left' => ['no_data_fontawesome_icon_unicode' => '\f0a8', 'no_data_fontawesome_icon_name' => 'Arrow circle left'],
		'arrow-circle-o-down' => ['no_data_fontawesome_icon_unicode' => '\f01a', 'no_data_fontawesome_icon_name' => 'Arrow circle o down'],
		'arrow-circle-o-left' => ['no_data_fontawesome_icon_unicode' => '\f190', 'no_data_fontawesome_icon_name' => 'Arrow circle o left'],
		'arrow-circle-o-right' => ['no_data_fontawesome_icon_unicode' => '\f18e', 'no_data_fontawesome_icon_name' => 'Arrow circle o right'],
		'arrow-circle-o-up' => ['no_data_fontawesome_icon_unicode' => '\f01b', 'no_data_fontawesome_icon_name' => 'Arrow circle o up'],
		'arrow-circle-right' => ['no_data_fontawesome_icon_unicode' => '\f0a9', 'no_data_fontawesome_icon_name' => 'Arrow circle right'],
		'arrow-circle-up' => ['no_data_fontawesome_icon_unicode' => '\f0aa', 'no_data_fontawesome_icon_name' => 'Arrow circle up'],
		'arrow-down' => ['no_data_fontawesome_icon_unicode' => '\f063', 'no_data_fontawesome_icon_name' => 'Arrow down'],
		'arrow-left' => ['no_data_fontawesome_icon_unicode' => '\f060', 'no_data_fontawesome_icon_name' => 'Arrow left'],
		'arrow-right' => ['no_data_fontawesome_icon_unicode' => '\f061', 'no_data_fontawesome_icon_name' => 'Arrow right'],
		'arrow-up' => ['no_data_fontawesome_icon_unicode' => '\f062', 'no_data_fontawesome_icon_name' => 'Arrow up'],
		'arrows' => ['no_data_fontawesome_icon_unicode' => '\f047', 'no_data_fontawesome_icon_name' => 'Arrows'],
		'arrows-alt' => ['no_data_fontawesome_icon_unicode' => '\f0b2', 'no_data_fontawesome_icon_name' => 'Arrows alt'],
		'arrows-h' => ['no_data_fontawesome_icon_unicode' => '\f07e', 'no_data_fontawesome_icon_name' => 'Arrows h'],
		'arrows-v' => ['no_data_fontawesome_icon_unicode' => '\f07d', 'no_data_fontawesome_icon_name' => 'Arrows v'],
		'assistive-listening-systems' => ['no_data_fontawesome_icon_unicode' => '\f2a2', 'no_data_fontawesome_icon_name' => 'Assistive listening systems'],
		'asterisk' => ['no_data_fontawesome_icon_unicode' => '\f069', 'no_data_fontawesome_icon_name' => 'Asterisk'],
		'at' => ['no_data_fontawesome_icon_unicode' => '\f1fa', 'no_data_fontawesome_icon_name' => 'At'],
		'audio-description' => ['no_data_fontawesome_icon_unicode' => '\f29e', 'no_data_fontawesome_icon_name' => 'Audio description'],
		'backward' => ['no_data_fontawesome_icon_unicode' => '\f04a', 'no_data_fontawesome_icon_name' => 'Backward'],
		'balance-scale' => ['no_data_fontawesome_icon_unicode' => '\f24e', 'no_data_fontawesome_icon_name' => 'Balance scale'],
		'ban' => ['no_data_fontawesome_icon_unicode' => '\f05e', 'no_data_fontawesome_icon_name' => 'Ban'],
		'bandcamp' => ['no_data_fontawesome_icon_unicode' => '\f2d5', 'no_data_fontawesome_icon_name' => 'Bandcamp'],
		'bar-chart' => ['no_data_fontawesome_icon_unicode' => '\f080', 'no_data_fontawesome_icon_name' => 'Bar chart'],
		'barcode' => ['no_data_fontawesome_icon_unicode' => '\f02a', 'no_data_fontawesome_icon_name' => 'Barcode'],
		'bars' => ['no_data_fontawesome_icon_unicode' => '\f0c9', 'no_data_fontawesome_icon_name' => 'Bars'],
		'bath' => ['no_data_fontawesome_icon_unicode' => '\f2cd', 'no_data_fontawesome_icon_name' => 'Bath'],
		'battery-empty' => ['no_data_fontawesome_icon_unicode' => '\f244', 'no_data_fontawesome_icon_name' => 'Battery empty'],
		'battery-full' => ['no_data_fontawesome_icon_unicode' => '\f240', 'no_data_fontawesome_icon_name' => 'Battery full'],
		'battery-half' => ['no_data_fontawesome_icon_unicode' => '\f242', 'no_data_fontawesome_icon_name' => 'Battery half'],
		'battery-quarter' => ['no_data_fontawesome_icon_unicode' => '\f243', 'no_data_fontawesome_icon_name' => 'Battery quarter'],
		'battery-three-quarters' => ['no_data_fontawesome_icon_unicode' => '\f241', 'no_data_fontawesome_icon_name' => 'Battery three quarters'],
		'bed' => ['no_data_fontawesome_icon_unicode' => '\f236', 'no_data_fontawesome_icon_name' => 'Bed'],
		'beer' => ['no_data_fontawesome_icon_unicode' => '\f0fc', 'no_data_fontawesome_icon_name' => 'Beer'],
		'behance' => ['no_data_fontawesome_icon_unicode' => '\f1b4', 'no_data_fontawesome_icon_name' => 'Behance'],
		'behance-square' => ['no_data_fontawesome_icon_unicode' => '\f1b5', 'no_data_fontawesome_icon_name' => 'Behance square'],
		'bell' => ['no_data_fontawesome_icon_unicode' => '\f0f3', 'no_data_fontawesome_icon_name' => 'Bell'],
		'bell-o' => ['no_data_fontawesome_icon_unicode' => '\f0a2', 'no_data_fontawesome_icon_name' => 'Bell o'],
		'bell-slash' => ['no_data_fontawesome_icon_unicode' => '\f1f6', 'no_data_fontawesome_icon_name' => 'Bell slash'],
		'bell-slash-o' => ['no_data_fontawesome_icon_unicode' => '\f1f7', 'no_data_fontawesome_icon_name' => 'Bell slash o'],
		'bicycle' => ['no_data_fontawesome_icon_unicode' => '\f206', 'no_data_fontawesome_icon_name' => 'Bicycle'],
		'binoculars' => ['no_data_fontawesome_icon_unicode' => '\f1e5', 'no_data_fontawesome_icon_name' => 'Binoculars'],
		'birthday-cake' => ['no_data_fontawesome_icon_unicode' => '\f1fd', 'no_data_fontawesome_icon_name' => 'Birthday cake'],
		'bitbucket' => ['no_data_fontawesome_icon_unicode' => '\f171', 'no_data_fontawesome_icon_name' => 'Bitbucket'],
		'bitbucket-square' => ['no_data_fontawesome_icon_unicode' => '\f172', 'no_data_fontawesome_icon_name' => 'Bitbucket square'],
		'black-tie' => ['no_data_fontawesome_icon_unicode' => '\f27e', 'no_data_fontawesome_icon_name' => 'Black tie'],
		'blind' => ['no_data_fontawesome_icon_unicode' => '\f29d', 'no_data_fontawesome_icon_name' => 'Blind'],
		'bluetooth' => ['no_data_fontawesome_icon_unicode' => '\f293', 'no_data_fontawesome_icon_name' => 'Bluetooth'],
		'bluetooth-b' => ['no_data_fontawesome_icon_unicode' => '\f294', 'no_data_fontawesome_icon_name' => 'Bluetooth b'],
		'bold' => ['no_data_fontawesome_icon_unicode' => '\f032', 'no_data_fontawesome_icon_name' => 'Bold'],
		'bolt' => ['no_data_fontawesome_icon_unicode' => '\f0e7', 'no_data_fontawesome_icon_name' => 'Bolt'],
		'bomb' => ['no_data_fontawesome_icon_unicode' => '\f1e2', 'no_data_fontawesome_icon_name' => 'Bomb'],
		'book' => ['no_data_fontawesome_icon_unicode' => '\f02d', 'no_data_fontawesome_icon_name' => 'Book'],
		'bookmark' => ['no_data_fontawesome_icon_unicode' => '\f02e', 'no_data_fontawesome_icon_name' => 'Bookmark'],
		'bookmark-o' => ['no_data_fontawesome_icon_unicode' => '\f097', 'no_data_fontawesome_icon_name' => 'Bookmark o'],
		'braille' => ['no_data_fontawesome_icon_unicode' => '\f2a1', 'no_data_fontawesome_icon_name' => 'Braille'],
		'briefcase' => ['no_data_fontawesome_icon_unicode' => '\f0b1', 'no_data_fontawesome_icon_name' => 'Briefcase'],
		'btc' => ['no_data_fontawesome_icon_unicode' => '\f15a', 'no_data_fontawesome_icon_name' => 'Btc'],
		'bug' => ['no_data_fontawesome_icon_unicode' => '\f188', 'no_data_fontawesome_icon_name' => 'Bug'],
		'building' => ['no_data_fontawesome_icon_unicode' => '\f1ad', 'no_data_fontawesome_icon_name' => 'Building'],
		'building-o' => ['no_data_fontawesome_icon_unicode' => '\f0f7', 'no_data_fontawesome_icon_name' => 'Building o'],
		'bullhorn' => ['no_data_fontawesome_icon_unicode' => '\f0a1', 'no_data_fontawesome_icon_name' => 'Bullhorn'],
		'bullseye' => ['no_data_fontawesome_icon_unicode' => '\f140', 'no_data_fontawesome_icon_name' => 'Bullseye'],
		'bus' => ['no_data_fontawesome_icon_unicode' => '\f207', 'no_data_fontawesome_icon_name' => 'Bus'],
		'buysellads' => ['no_data_fontawesome_icon_unicode' => '\f20d', 'no_data_fontawesome_icon_name' => 'Buysellads'],
		'calculator' => ['no_data_fontawesome_icon_unicode' => '\f1ec', 'no_data_fontawesome_icon_name' => 'Calculator'],
		'calendar' => ['no_data_fontawesome_icon_unicode' => '\f073', 'no_data_fontawesome_icon_name' => 'Calendar'],
		'calendar-check-o' => ['no_data_fontawesome_icon_unicode' => '\f274', 'no_data_fontawesome_icon_name' => 'Calendar check o'],
		'calendar-minus-o' => ['no_data_fontawesome_icon_unicode' => '\f272', 'no_data_fontawesome_icon_name' => 'Calendar minus o'],
		'calendar-o' => ['no_data_fontawesome_icon_unicode' => '\f133', 'no_data_fontawesome_icon_name' => 'Calendar o'],
		'calendar-plus-o' => ['no_data_fontawesome_icon_unicode' => '\f271', 'no_data_fontawesome_icon_name' => 'Calendar plus o'],
		'calendar-times-o' => ['no_data_fontawesome_icon_unicode' => '\f273', 'no_data_fontawesome_icon_name' => 'Calendar times o'],
		'camera' => ['no_data_fontawesome_icon_unicode' => '\f030', 'no_data_fontawesome_icon_name' => 'Camera'],
		'camera-retro' => ['no_data_fontawesome_icon_unicode' => '\f083', 'no_data_fontawesome_icon_name' => 'Camera retro'],
		'car' => ['no_data_fontawesome_icon_unicode' => '\f1b9', 'no_data_fontawesome_icon_name' => 'Car'],
		'caret-down' => ['no_data_fontawesome_icon_unicode' => '\f0d7', 'no_data_fontawesome_icon_name' => 'Caret down'],
		'caret-left' => ['no_data_fontawesome_icon_unicode' => '\f0d9', 'no_data_fontawesome_icon_name' => 'Caret left'],
		'caret-right' => ['no_data_fontawesome_icon_unicode' => '\f0da', 'no_data_fontawesome_icon_name' => 'Caret right'],
		'caret-square-o-down' => ['no_data_fontawesome_icon_unicode' => '\f150', 'no_data_fontawesome_icon_name' => 'Caret square o down'],
		'caret-square-o-left' => ['no_data_fontawesome_icon_unicode' => '\f191', 'no_data_fontawesome_icon_name' => 'Caret square o left'],
		'caret-square-o-right' => ['no_data_fontawesome_icon_unicode' => '\f152', 'no_data_fontawesome_icon_name' => 'Caret square o right'],
		'caret-square-o-up' => ['no_data_fontawesome_icon_unicode' => '\f151', 'no_data_fontawesome_icon_name' => 'Caret square o up'],
		'caret-up' => ['no_data_fontawesome_icon_unicode' => '\f0d8', 'no_data_fontawesome_icon_name' => 'Caret up'],
		'cart-arrow-down' => ['no_data_fontawesome_icon_unicode' => '\f218', 'no_data_fontawesome_icon_name' => 'Cart arrow down'],
		'cart-plus' => ['no_data_fontawesome_icon_unicode' => '\f217', 'no_data_fontawesome_icon_name' => 'Cart plus'],
		'cc' => ['no_data_fontawesome_icon_unicode' => '\f20a', 'no_data_fontawesome_icon_name' => 'Cc'],
		'cc-amex' => ['no_data_fontawesome_icon_unicode' => '\f1f3', 'no_data_fontawesome_icon_name' => 'Cc amex'],
		'cc-diners-club' => ['no_data_fontawesome_icon_unicode' => '\f24c', 'no_data_fontawesome_icon_name' => 'Cc diners club'],
		'cc-discover' => ['no_data_fontawesome_icon_unicode' => '\f1f2', 'no_data_fontawesome_icon_name' => 'Cc discover'],
		'cc-jcb' => ['no_data_fontawesome_icon_unicode' => '\f24b', 'no_data_fontawesome_icon_name' => 'Cc jcb'],
		'cc-mastercard' => ['no_data_fontawesome_icon_unicode' => '\f1f1', 'no_data_fontawesome_icon_name' => 'Cc mastercard'],
		'cc-paypal' => ['no_data_fontawesome_icon_unicode' => '\f1f4', 'no_data_fontawesome_icon_name' => 'Cc paypal'],
		'cc-stripe' => ['no_data_fontawesome_icon_unicode' => '\f1f5', 'no_data_fontawesome_icon_name' => 'Cc stripe'],
		'cc-visa' => ['no_data_fontawesome_icon_unicode' => '\f1f0', 'no_data_fontawesome_icon_name' => 'Cc visa'],
		'certificate' => ['no_data_fontawesome_icon_unicode' => '\f0a3', 'no_data_fontawesome_icon_name' => 'Certificate'],
		'chain-broken' => ['no_data_fontawesome_icon_unicode' => '\f127', 'no_data_fontawesome_icon_name' => 'Chain broken'],
		'check' => ['no_data_fontawesome_icon_unicode' => '\f00c', 'no_data_fontawesome_icon_name' => 'Check'],
		'check-circle' => ['no_data_fontawesome_icon_unicode' => '\f058', 'no_data_fontawesome_icon_name' => 'Check circle'],
		'check-circle-o' => ['no_data_fontawesome_icon_unicode' => '\f05d', 'no_data_fontawesome_icon_name' => 'Check circle o'],
		'check-square' => ['no_data_fontawesome_icon_unicode' => '\f14a', 'no_data_fontawesome_icon_name' => 'Check square'],
		'check-square-o' => ['no_data_fontawesome_icon_unicode' => '\f046', 'no_data_fontawesome_icon_name' => 'Check square o'],
		'chevron-circle-down' => ['no_data_fontawesome_icon_unicode' => '\f13a', 'no_data_fontawesome_icon_name' => 'Chevron circle down'],
		'chevron-circle-left' => ['no_data_fontawesome_icon_unicode' => '\f137', 'no_data_fontawesome_icon_name' => 'Chevron circle left'],
		'chevron-circle-right' => ['no_data_fontawesome_icon_unicode' => '\f138', 'no_data_fontawesome_icon_name' => 'Chevron circle right'],
		'chevron-circle-up' => ['no_data_fontawesome_icon_unicode' => '\f139', 'no_data_fontawesome_icon_name' => 'Chevron circle up'],
		'chevron-down' => ['no_data_fontawesome_icon_unicode' => '\f078', 'no_data_fontawesome_icon_name' => 'Chevron down'],
		'chevron-left' => ['no_data_fontawesome_icon_unicode' => '\f053', 'no_data_fontawesome_icon_name' => 'Chevron left'],
		'chevron-right' => ['no_data_fontawesome_icon_unicode' => '\f054', 'no_data_fontawesome_icon_name' => 'Chevron right'],
		'chevron-up' => ['no_data_fontawesome_icon_unicode' => '\f077', 'no_data_fontawesome_icon_name' => 'Chevron up'],
		'child' => ['no_data_fontawesome_icon_unicode' => '\f1ae', 'no_data_fontawesome_icon_name' => 'Child'],
		'chrome' => ['no_data_fontawesome_icon_unicode' => '\f268', 'no_data_fontawesome_icon_name' => 'Chrome'],
		'circle' => ['no_data_fontawesome_icon_unicode' => '\f111', 'no_data_fontawesome_icon_name' => 'Circle'],
		'circle-o' => ['no_data_fontawesome_icon_unicode' => '\f10c', 'no_data_fontawesome_icon_name' => 'Circle o'],
		'circle-o-notch' => ['no_data_fontawesome_icon_unicode' => '\f1ce', 'no_data_fontawesome_icon_name' => 'Circle o notch'],
		'circle-thin' => ['no_data_fontawesome_icon_unicode' => '\f1db', 'no_data_fontawesome_icon_name' => 'Circle thin'],
		'clipboard' => ['no_data_fontawesome_icon_unicode' => '\f0ea', 'no_data_fontawesome_icon_name' => 'Clipboard'],
		'clock-o' => ['no_data_fontawesome_icon_unicode' => '\f017', 'no_data_fontawesome_icon_name' => 'Clock o'],
		'clone' => ['no_data_fontawesome_icon_unicode' => '\f24d', 'no_data_fontawesome_icon_name' => 'Clone'],
		'cloud' => ['no_data_fontawesome_icon_unicode' => '\f0c2', 'no_data_fontawesome_icon_name' => 'Cloud'],
		'cloud-download' => ['no_data_fontawesome_icon_unicode' => '\f0ed', 'no_data_fontawesome_icon_name' => 'Cloud download'],
		'cloud-upload' => ['no_data_fontawesome_icon_unicode' => '\f0ee', 'no_data_fontawesome_icon_name' => 'Cloud upload'],
		'code' => ['no_data_fontawesome_icon_unicode' => '\f121', 'no_data_fontawesome_icon_name' => 'Code'],
		'code-fork' => ['no_data_fontawesome_icon_unicode' => '\f126', 'no_data_fontawesome_icon_name' => 'Code fork'],
		'codepen' => ['no_data_fontawesome_icon_unicode' => '\f1cb', 'no_data_fontawesome_icon_name' => 'Codepen'],
		'codiepie' => ['no_data_fontawesome_icon_unicode' => '\f284', 'no_data_fontawesome_icon_name' => 'Codiepie'],
		'coffee' => ['no_data_fontawesome_icon_unicode' => '\f0f4', 'no_data_fontawesome_icon_name' => 'Coffee'],
		'cog' => ['no_data_fontawesome_icon_unicode' => '\f013', 'no_data_fontawesome_icon_name' => 'Cog'],
		'cogs' => ['no_data_fontawesome_icon_unicode' => '\f085', 'no_data_fontawesome_icon_name' => 'Cogs'],
		'columns' => ['no_data_fontawesome_icon_unicode' => '\f0db', 'no_data_fontawesome_icon_name' => 'Columns'],
		'comment' => ['no_data_fontawesome_icon_unicode' => '\f075', 'no_data_fontawesome_icon_name' => 'Comment'],
		'comment-o' => ['no_data_fontawesome_icon_unicode' => '\f0e5', 'no_data_fontawesome_icon_name' => 'Comment o'],
		'commenting' => ['no_data_fontawesome_icon_unicode' => '\f27a', 'no_data_fontawesome_icon_name' => 'Commenting'],
		'commenting-o' => ['no_data_fontawesome_icon_unicode' => '\f27b', 'no_data_fontawesome_icon_name' => 'Commenting o'],
		'comments' => ['no_data_fontawesome_icon_unicode' => '\f086', 'no_data_fontawesome_icon_name' => 'Comments'],
		'comments-o' => ['no_data_fontawesome_icon_unicode' => '\f0e6', 'no_data_fontawesome_icon_name' => 'Comments o'],
		'compass' => ['no_data_fontawesome_icon_unicode' => '\f14e', 'no_data_fontawesome_icon_name' => 'Compass'],
		'compress' => ['no_data_fontawesome_icon_unicode' => '\f066', 'no_data_fontawesome_icon_name' => 'Compress'],
		'connectdevelop' => ['no_data_fontawesome_icon_unicode' => '\f20e', 'no_data_fontawesome_icon_name' => 'Connectdevelop'],
		'contao' => ['no_data_fontawesome_icon_unicode' => '\f26d', 'no_data_fontawesome_icon_name' => 'Contao'],
		'copyright' => ['no_data_fontawesome_icon_unicode' => '\f1f9', 'no_data_fontawesome_icon_name' => 'Copyright'],
		'creative-commons' => ['no_data_fontawesome_icon_unicode' => '\f25e', 'no_data_fontawesome_icon_name' => 'Creative commons'],
		'credit-card' => ['no_data_fontawesome_icon_unicode' => '\f09d', 'no_data_fontawesome_icon_name' => 'Credit card'],
		'credit-card-alt' => ['no_data_fontawesome_icon_unicode' => '\f283', 'no_data_fontawesome_icon_name' => 'Credit card alt'],
		'crop' => ['no_data_fontawesome_icon_unicode' => '\f125', 'no_data_fontawesome_icon_name' => 'Crop'],
		'crosshairs' => ['no_data_fontawesome_icon_unicode' => '\f05b', 'no_data_fontawesome_icon_name' => 'Crosshairs'],
		'css3' => ['no_data_fontawesome_icon_unicode' => '\f13c', 'no_data_fontawesome_icon_name' => 'Css3'],
		'cube' => ['no_data_fontawesome_icon_unicode' => '\f1b2', 'no_data_fontawesome_icon_name' => 'Cube'],
		'cubes' => ['no_data_fontawesome_icon_unicode' => '\f1b3', 'no_data_fontawesome_icon_name' => 'Cubes'],
		'cutlery' => ['no_data_fontawesome_icon_unicode' => '\f0f5', 'no_data_fontawesome_icon_name' => 'Cutlery'],
		'dashcube' => ['no_data_fontawesome_icon_unicode' => '\f210', 'no_data_fontawesome_icon_name' => 'Dashcube'],
		'database' => ['no_data_fontawesome_icon_unicode' => '\f1c0', 'no_data_fontawesome_icon_name' => 'Database'],
		'deaf' => ['no_data_fontawesome_icon_unicode' => '\f2a4', 'no_data_fontawesome_icon_name' => 'Deaf'],
		'delicious' => ['no_data_fontawesome_icon_unicode' => '\f1a5', 'no_data_fontawesome_icon_name' => 'Delicious'],
		'desktop' => ['no_data_fontawesome_icon_unicode' => '\f108', 'no_data_fontawesome_icon_name' => 'Desktop'],
		'deviantart' => ['no_data_fontawesome_icon_unicode' => '\f1bd', 'no_data_fontawesome_icon_name' => 'Deviantart'],
		'diamond' => ['no_data_fontawesome_icon_unicode' => '\f219', 'no_data_fontawesome_icon_name' => 'Diamond'],
		'digg' => ['no_data_fontawesome_icon_unicode' => '\f1a6', 'no_data_fontawesome_icon_name' => 'Digg'],
		'dot-circle-o' => ['no_data_fontawesome_icon_unicode' => '\f192', 'no_data_fontawesome_icon_name' => 'Dot circle o'],
		'download' => ['no_data_fontawesome_icon_unicode' => '\f019', 'no_data_fontawesome_icon_name' => 'Download'],
		'dribbble' => ['no_data_fontawesome_icon_unicode' => '\f17d', 'no_data_fontawesome_icon_name' => 'Dribbble'],
		'dropbox' => ['no_data_fontawesome_icon_unicode' => '\f16b', 'no_data_fontawesome_icon_name' => 'Dropbox'],
		'drupal' => ['no_data_fontawesome_icon_unicode' => '\f1a9', 'no_data_fontawesome_icon_name' => 'Drupal'],
		'edge' => ['no_data_fontawesome_icon_unicode' => '\f282', 'no_data_fontawesome_icon_name' => 'Edge'],
		'eercast' => ['no_data_fontawesome_icon_unicode' => '\f2da', 'no_data_fontawesome_icon_name' => 'Eercast'],
		'eject' => ['no_data_fontawesome_icon_unicode' => '\f052', 'no_data_fontawesome_icon_name' => 'Eject'],
		'ellipsis-h' => ['no_data_fontawesome_icon_unicode' => '\f141', 'no_data_fontawesome_icon_name' => 'Ellipsis h'],
		'ellipsis-v' => ['no_data_fontawesome_icon_unicode' => '\f142', 'no_data_fontawesome_icon_name' => 'Ellipsis v'],
		'empire' => ['no_data_fontawesome_icon_unicode' => '\f1d1', 'no_data_fontawesome_icon_name' => 'Empire'],
		'envelope' => ['no_data_fontawesome_icon_unicode' => '\f0e0', 'no_data_fontawesome_icon_name' => 'Envelope'],
		'envelope-o' => ['no_data_fontawesome_icon_unicode' => '\f003', 'no_data_fontawesome_icon_name' => 'Envelope o'],
		'envelope-open' => ['no_data_fontawesome_icon_unicode' => '\f2b6', 'no_data_fontawesome_icon_name' => 'Envelope open'],
		'envelope-open-o' => ['no_data_fontawesome_icon_unicode' => '\f2b7', 'no_data_fontawesome_icon_name' => 'Envelope open o'],
		'envelope-square' => ['no_data_fontawesome_icon_unicode' => '\f199', 'no_data_fontawesome_icon_name' => 'Envelope square'],
		'envira' => ['no_data_fontawesome_icon_unicode' => '\f299', 'no_data_fontawesome_icon_name' => 'Envira'],
		'eraser' => ['no_data_fontawesome_icon_unicode' => '\f12d', 'no_data_fontawesome_icon_name' => 'Eraser'],
		'etsy' => ['no_data_fontawesome_icon_unicode' => '\f2d7', 'no_data_fontawesome_icon_name' => 'Etsy'],
		'eur' => ['no_data_fontawesome_icon_unicode' => '\f153', 'no_data_fontawesome_icon_name' => 'Eur'],
		'exchange' => ['no_data_fontawesome_icon_unicode' => '\f0ec', 'no_data_fontawesome_icon_name' => 'Exchange'],
		'exclamation' => ['no_data_fontawesome_icon_unicode' => '\f12a', 'no_data_fontawesome_icon_name' => 'Exclamation'],
		'exclamation-circle' => ['no_data_fontawesome_icon_unicode' => '\f06a', 'no_data_fontawesome_icon_name' => 'Exclamation circle'],
		'exclamation-triangle' => ['no_data_fontawesome_icon_unicode' => '\f071', 'no_data_fontawesome_icon_name' => 'Exclamation triangle'],
		'expand' => ['no_data_fontawesome_icon_unicode' => '\f065', 'no_data_fontawesome_icon_name' => 'Expand'],
		'expeditedssl' => ['no_data_fontawesome_icon_unicode' => '\f23e', 'no_data_fontawesome_icon_name' => 'Expeditedssl'],
		'external-link' => ['no_data_fontawesome_icon_unicode' => '\f08e', 'no_data_fontawesome_icon_name' => 'External link'],
		'external-link-square' => ['no_data_fontawesome_icon_unicode' => '\f14c', 'no_data_fontawesome_icon_name' => 'External link square'],
		'eye' => ['no_data_fontawesome_icon_unicode' => '\f06e', 'no_data_fontawesome_icon_name' => 'Eye'],
		'eye-slash' => ['no_data_fontawesome_icon_unicode' => '\f070', 'no_data_fontawesome_icon_name' => 'Eye slash'],
		'eyedropper' => ['no_data_fontawesome_icon_unicode' => '\f1fb', 'no_data_fontawesome_icon_name' => 'Eyedropper'],
		'facebook' => ['no_data_fontawesome_icon_unicode' => '\f09a', 'no_data_fontawesome_icon_name' => 'Facebook'],
		'facebook-official' => ['no_data_fontawesome_icon_unicode' => '\f230', 'no_data_fontawesome_icon_name' => 'Facebook official'],
		'facebook-square' => ['no_data_fontawesome_icon_unicode' => '\f082', 'no_data_fontawesome_icon_name' => 'Facebook square'],
		'fast-backward' => ['no_data_fontawesome_icon_unicode' => '\f049', 'no_data_fontawesome_icon_name' => 'Fast backward'],
		'fast-forward' => ['no_data_fontawesome_icon_unicode' => '\f050', 'no_data_fontawesome_icon_name' => 'Fast forward'],
		'fax' => ['no_data_fontawesome_icon_unicode' => '\f1ac', 'no_data_fontawesome_icon_name' => 'Fax'],
		'female' => ['no_data_fontawesome_icon_unicode' => '\f182', 'no_data_fontawesome_icon_name' => 'Female'],
		'fighter-jet' => ['no_data_fontawesome_icon_unicode' => '\f0fb', 'no_data_fontawesome_icon_name' => 'Fighter jet'],
		'file' => ['no_data_fontawesome_icon_unicode' => '\f15b', 'no_data_fontawesome_icon_name' => 'File'],
		'file-archive-o' => ['no_data_fontawesome_icon_unicode' => '\f1c6', 'no_data_fontawesome_icon_name' => 'File archive o'],
		'file-audio-o' => ['no_data_fontawesome_icon_unicode' => '\f1c7', 'no_data_fontawesome_icon_name' => 'File audio o'],
		'file-code-o' => ['no_data_fontawesome_icon_unicode' => '\f1c9', 'no_data_fontawesome_icon_name' => 'File code o'],
		'file-excel-o' => ['no_data_fontawesome_icon_unicode' => '\f1c3', 'no_data_fontawesome_icon_name' => 'File excel o'],
		'file-image-o' => ['no_data_fontawesome_icon_unicode' => '\f1c5', 'no_data_fontawesome_icon_name' => 'File image o'],
		'file-o' => ['no_data_fontawesome_icon_unicode' => '\f016', 'no_data_fontawesome_icon_name' => 'File o'],
		'file-pdf-o' => ['no_data_fontawesome_icon_unicode' => '\f1c1', 'no_data_fontawesome_icon_name' => 'File pdf o'],
		'file-powerpoint-o' => ['no_data_fontawesome_icon_unicode' => '\f1c4', 'no_data_fontawesome_icon_name' => 'File powerpoint o'],
		'file-text' => ['no_data_fontawesome_icon_unicode' => '\f15c', 'no_data_fontawesome_icon_name' => 'File text'],
		'file-text-o' => ['no_data_fontawesome_icon_unicode' => '\f0f6', 'no_data_fontawesome_icon_name' => 'File text o'],
		'file-video-o' => ['no_data_fontawesome_icon_unicode' => '\f1c8', 'no_data_fontawesome_icon_name' => 'File video o'],
		'file-word-o' => ['no_data_fontawesome_icon_unicode' => '\f1c2', 'no_data_fontawesome_icon_name' => 'File word o'],
		'files-o' => ['no_data_fontawesome_icon_unicode' => '\f0c5', 'no_data_fontawesome_icon_name' => 'Files o'],
		'film' => ['no_data_fontawesome_icon_unicode' => '\f008', 'no_data_fontawesome_icon_name' => 'Film'],
		'filter' => ['no_data_fontawesome_icon_unicode' => '\f0b0', 'no_data_fontawesome_icon_name' => 'Filter'],
		'fire' => ['no_data_fontawesome_icon_unicode' => '\f06d', 'no_data_fontawesome_icon_name' => 'Fire'],
		'fire-extinguisher' => ['no_data_fontawesome_icon_unicode' => '\f134', 'no_data_fontawesome_icon_name' => 'Fire extinguisher'],
		'firefox' => ['no_data_fontawesome_icon_unicode' => '\f269', 'no_data_fontawesome_icon_name' => 'Firefox'],
		'first-order' => ['no_data_fontawesome_icon_unicode' => '\f2b0', 'no_data_fontawesome_icon_name' => 'First order'],
		'flag' => ['no_data_fontawesome_icon_unicode' => '\f024', 'no_data_fontawesome_icon_name' => 'Flag'],
		'flag-checkered' => ['no_data_fontawesome_icon_unicode' => '\f11e', 'no_data_fontawesome_icon_name' => 'Flag checkered'],
		'flag-o' => ['no_data_fontawesome_icon_unicode' => '\f11d', 'no_data_fontawesome_icon_name' => 'Flag o'],
		'flask' => ['no_data_fontawesome_icon_unicode' => '\f0c3', 'no_data_fontawesome_icon_name' => 'Flask'],
		'flickr' => ['no_data_fontawesome_icon_unicode' => '\f16e', 'no_data_fontawesome_icon_name' => 'Flickr'],
		'floppy-o' => ['no_data_fontawesome_icon_unicode' => '\f0c7', 'no_data_fontawesome_icon_name' => 'Floppy o'],
		'folder' => ['no_data_fontawesome_icon_unicode' => '\f07b', 'no_data_fontawesome_icon_name' => 'Folder'],
		'folder-o' => ['no_data_fontawesome_icon_unicode' => '\f114', 'no_data_fontawesome_icon_name' => 'Folder o'],
		'folder-open' => ['no_data_fontawesome_icon_unicode' => '\f07c', 'no_data_fontawesome_icon_name' => 'Folder open'],
		'folder-open-o' => ['no_data_fontawesome_icon_unicode' => '\f115', 'no_data_fontawesome_icon_name' => 'Folder open o'],
		'font' => ['no_data_fontawesome_icon_unicode' => '\f031', 'no_data_fontawesome_icon_name' => 'Font'],
		'font-awesome' => ['no_data_fontawesome_icon_unicode' => '\f2b4', 'no_data_fontawesome_icon_name' => 'Font awesome'],
		'fonticons' => ['no_data_fontawesome_icon_unicode' => '\f280', 'no_data_fontawesome_icon_name' => 'Fonticons'],
		'fort-awesome' => ['no_data_fontawesome_icon_unicode' => '\f286', 'no_data_fontawesome_icon_name' => 'Fort awesome'],
		'forumbee' => ['no_data_fontawesome_icon_unicode' => '\f211', 'no_data_fontawesome_icon_name' => 'Forumbee'],
		'forward' => ['no_data_fontawesome_icon_unicode' => '\f04e', 'no_data_fontawesome_icon_name' => 'Forward'],
		'foursquare' => ['no_data_fontawesome_icon_unicode' => '\f180', 'no_data_fontawesome_icon_name' => 'Foursquare'],
		'free-code-camp' => ['no_data_fontawesome_icon_unicode' => '\f2c5', 'no_data_fontawesome_icon_name' => 'Free code camp'],
		'frown-o' => ['no_data_fontawesome_icon_unicode' => '\f119', 'no_data_fontawesome_icon_name' => 'Frown o'],
		'futbol-o' => ['no_data_fontawesome_icon_unicode' => '\f1e3', 'no_data_fontawesome_icon_name' => 'Futbol o'],
		'gamepad' => ['no_data_fontawesome_icon_unicode' => '\f11b', 'no_data_fontawesome_icon_name' => 'Gamepad'],
		'gavel' => ['no_data_fontawesome_icon_unicode' => '\f0e3', 'no_data_fontawesome_icon_name' => 'Gavel'],
		'gbp' => ['no_data_fontawesome_icon_unicode' => '\f154', 'no_data_fontawesome_icon_name' => 'Gbp'],
		'genderless' => ['no_data_fontawesome_icon_unicode' => '\f22d', 'no_data_fontawesome_icon_name' => 'Genderless'],
		'get-pocket' => ['no_data_fontawesome_icon_unicode' => '\f265', 'no_data_fontawesome_icon_name' => 'Get pocket'],
		'gg' => ['no_data_fontawesome_icon_unicode' => '\f260', 'no_data_fontawesome_icon_name' => 'Gg'],
		'gg-circle' => ['no_data_fontawesome_icon_unicode' => '\f261', 'no_data_fontawesome_icon_name' => 'Gg circle'],
		'gift' => ['no_data_fontawesome_icon_unicode' => '\f06b', 'no_data_fontawesome_icon_name' => 'Gift'],
		'git' => ['no_data_fontawesome_icon_unicode' => '\f1d3', 'no_data_fontawesome_icon_name' => 'Git'],
		'git-square' => ['no_data_fontawesome_icon_unicode' => '\f1d2', 'no_data_fontawesome_icon_name' => 'Git square'],
		'github' => ['no_data_fontawesome_icon_unicode' => '\f09b', 'no_data_fontawesome_icon_name' => 'Github'],
		'github-alt' => ['no_data_fontawesome_icon_unicode' => '\f113', 'no_data_fontawesome_icon_name' => 'Github alt'],
		'github-square' => ['no_data_fontawesome_icon_unicode' => '\f092', 'no_data_fontawesome_icon_name' => 'Github square'],
		'gitlab' => ['no_data_fontawesome_icon_unicode' => '\f296', 'no_data_fontawesome_icon_name' => 'Gitlab'],
		'glass' => ['no_data_fontawesome_icon_unicode' => '\f000', 'no_data_fontawesome_icon_name' => 'Glass'],
		'glide' => ['no_data_fontawesome_icon_unicode' => '\f2a5', 'no_data_fontawesome_icon_name' => 'Glide'],
		'glide-g' => ['no_data_fontawesome_icon_unicode' => '\f2a6', 'no_data_fontawesome_icon_name' => 'Glide g'],
		'globe' => ['no_data_fontawesome_icon_unicode' => '\f0ac', 'no_data_fontawesome_icon_name' => 'Globe'],
		'google' => ['no_data_fontawesome_icon_unicode' => '\f1a0', 'no_data_fontawesome_icon_name' => 'Google'],
		'google-plus' => ['no_data_fontawesome_icon_unicode' => '\f0d5', 'no_data_fontawesome_icon_name' => 'Google plus'],
		'google-plus-official' => ['no_data_fontawesome_icon_unicode' => '\f2b3', 'no_data_fontawesome_icon_name' => 'Google plus official'],
		'google-plus-square' => ['no_data_fontawesome_icon_unicode' => '\f0d4', 'no_data_fontawesome_icon_name' => 'Google plus square'],
		'google-wallet' => ['no_data_fontawesome_icon_unicode' => '\f1ee', 'no_data_fontawesome_icon_name' => 'Google wallet'],
		'graduation-cap' => ['no_data_fontawesome_icon_unicode' => '\f19d', 'no_data_fontawesome_icon_name' => 'Graduation cap'],
		'gratipay' => ['no_data_fontawesome_icon_unicode' => '\f184', 'no_data_fontawesome_icon_name' => 'Gratipay'],
		'grav' => ['no_data_fontawesome_icon_unicode' => '\f2d6', 'no_data_fontawesome_icon_name' => 'Grav'],
		'h-square' => ['no_data_fontawesome_icon_unicode' => '\f0fd', 'no_data_fontawesome_icon_name' => 'H square'],
		'hacker-news' => ['no_data_fontawesome_icon_unicode' => '\f1d4', 'no_data_fontawesome_icon_name' => 'Hacker news'],
		'hand-lizard-o' => ['no_data_fontawesome_icon_unicode' => '\f258', 'no_data_fontawesome_icon_name' => 'Hand lizard o'],
		'hand-o-down' => ['no_data_fontawesome_icon_unicode' => '\f0a7', 'no_data_fontawesome_icon_name' => 'Hand o down'],
		'hand-o-left' => ['no_data_fontawesome_icon_unicode' => '\f0a5', 'no_data_fontawesome_icon_name' => 'Hand o left'],
		'hand-o-right' => ['no_data_fontawesome_icon_unicode' => '\f0a4', 'no_data_fontawesome_icon_name' => 'Hand o right'],
		'hand-o-up' => ['no_data_fontawesome_icon_unicode' => '\f0a6', 'no_data_fontawesome_icon_name' => 'Hand o up'],
		'hand-paper-o' => ['no_data_fontawesome_icon_unicode' => '\f256', 'no_data_fontawesome_icon_name' => 'Hand paper o'],
		'hand-peace-o' => ['no_data_fontawesome_icon_unicode' => '\f25b', 'no_data_fontawesome_icon_name' => 'Hand peace o'],
		'hand-pointer-o' => ['no_data_fontawesome_icon_unicode' => '\f25a', 'no_data_fontawesome_icon_name' => 'Hand pointer o'],
		'hand-rock-o' => ['no_data_fontawesome_icon_unicode' => '\f255', 'no_data_fontawesome_icon_name' => 'Hand rock o'],
		'hand-scissors-o' => ['no_data_fontawesome_icon_unicode' => '\f257', 'no_data_fontawesome_icon_name' => 'Hand scissors o'],
		'hand-spock-o' => ['no_data_fontawesome_icon_unicode' => '\f259', 'no_data_fontawesome_icon_name' => 'Hand spock o'],
		'handshake-o' => ['no_data_fontawesome_icon_unicode' => '\f2b5', 'no_data_fontawesome_icon_name' => 'Handshake o'],
		'hashtag' => ['no_data_fontawesome_icon_unicode' => '\f292', 'no_data_fontawesome_icon_name' => 'Hashtag'],
		'hdd-o' => ['no_data_fontawesome_icon_unicode' => '\f0a0', 'no_data_fontawesome_icon_name' => 'Hdd o'],
		'header' => ['no_data_fontawesome_icon_unicode' => '\f1dc', 'no_data_fontawesome_icon_name' => 'Header'],
		'headphones' => ['no_data_fontawesome_icon_unicode' => '\f025', 'no_data_fontawesome_icon_name' => 'Headphones'],
		'heart' => ['no_data_fontawesome_icon_unicode' => '\f004', 'no_data_fontawesome_icon_name' => 'Heart'],
		'heart-o' => ['no_data_fontawesome_icon_unicode' => '\f08a', 'no_data_fontawesome_icon_name' => 'Heart o'],
		'heartbeat' => ['no_data_fontawesome_icon_unicode' => '\f21e', 'no_data_fontawesome_icon_name' => 'Heartbeat'],
		'history' => ['no_data_fontawesome_icon_unicode' => '\f1da', 'no_data_fontawesome_icon_name' => 'History'],
		'home' => ['no_data_fontawesome_icon_unicode' => '\f015', 'no_data_fontawesome_icon_name' => 'Home'],
		'hospital-o' => ['no_data_fontawesome_icon_unicode' => '\f0f8', 'no_data_fontawesome_icon_name' => 'Hospital o'],
		'hourglass' => ['no_data_fontawesome_icon_unicode' => '\f254', 'no_data_fontawesome_icon_name' => 'Hourglass'],
		'hourglass-end' => ['no_data_fontawesome_icon_unicode' => '\f253', 'no_data_fontawesome_icon_name' => 'Hourglass end'],
		'hourglass-half' => ['no_data_fontawesome_icon_unicode' => '\f252', 'no_data_fontawesome_icon_name' => 'Hourglass half'],
		'hourglass-o' => ['no_data_fontawesome_icon_unicode' => '\f250', 'no_data_fontawesome_icon_name' => 'Hourglass o'],
		'hourglass-start' => ['no_data_fontawesome_icon_unicode' => '\f251', 'no_data_fontawesome_icon_name' => 'Hourglass start'],
		'houzz' => ['no_data_fontawesome_icon_unicode' => '\f27c', 'no_data_fontawesome_icon_name' => 'Houzz'],
		'html5' => ['no_data_fontawesome_icon_unicode' => '\f13b', 'no_data_fontawesome_icon_name' => 'Html5'],
		'i-cursor' => ['no_data_fontawesome_icon_unicode' => '\f246', 'no_data_fontawesome_icon_name' => 'I cursor'],
		'id-badge' => ['no_data_fontawesome_icon_unicode' => '\f2c1', 'no_data_fontawesome_icon_name' => 'Id badge'],
		'id-card' => ['no_data_fontawesome_icon_unicode' => '\f2c2', 'no_data_fontawesome_icon_name' => 'Id card'],
		'id-card-o' => ['no_data_fontawesome_icon_unicode' => '\f2c3', 'no_data_fontawesome_icon_name' => 'Id card o'],
		'ils' => ['no_data_fontawesome_icon_unicode' => '\f20b', 'no_data_fontawesome_icon_name' => 'Ils'],
		'imdb' => ['no_data_fontawesome_icon_unicode' => '\f2d8', 'no_data_fontawesome_icon_name' => 'Imdb'],
		'inbox' => ['no_data_fontawesome_icon_unicode' => '\f01c', 'no_data_fontawesome_icon_name' => 'Inbox'],
		'indent' => ['no_data_fontawesome_icon_unicode' => '\f03c', 'no_data_fontawesome_icon_name' => 'Indent'],
		'industry' => ['no_data_fontawesome_icon_unicode' => '\f275', 'no_data_fontawesome_icon_name' => 'Industry'],
		'info' => ['no_data_fontawesome_icon_unicode' => '\f129', 'no_data_fontawesome_icon_name' => 'Info'],
		'info-circle' => ['no_data_fontawesome_icon_unicode' => '\f05a', 'no_data_fontawesome_icon_name' => 'Info circle'],
		'inr' => ['no_data_fontawesome_icon_unicode' => '\f156', 'no_data_fontawesome_icon_name' => 'Inr'],
		'instagram' => ['no_data_fontawesome_icon_unicode' => '\f16d', 'no_data_fontawesome_icon_name' => 'Instagram'],
		'internet-explorer' => ['no_data_fontawesome_icon_unicode' => '\f26b', 'no_data_fontawesome_icon_name' => 'Internet explorer'],
		'ioxhost' => ['no_data_fontawesome_icon_unicode' => '\f208', 'no_data_fontawesome_icon_name' => 'Ioxhost'],
		'italic' => ['no_data_fontawesome_icon_unicode' => '\f033', 'no_data_fontawesome_icon_name' => 'Italic'],
		'joomla' => ['no_data_fontawesome_icon_unicode' => '\f1aa', 'no_data_fontawesome_icon_name' => 'Joomla'],
		'jpy' => ['no_data_fontawesome_icon_unicode' => '\f157', 'no_data_fontawesome_icon_name' => 'Jpy'],
		'jsfiddle' => ['no_data_fontawesome_icon_unicode' => '\f1cc', 'no_data_fontawesome_icon_name' => 'Jsfiddle'],
		'key' => ['no_data_fontawesome_icon_unicode' => '\f084', 'no_data_fontawesome_icon_name' => 'Key'],
		'keyboard-o' => ['no_data_fontawesome_icon_unicode' => '\f11c', 'no_data_fontawesome_icon_name' => 'Keyboard o'],
		'krw' => ['no_data_fontawesome_icon_unicode' => '\f159', 'no_data_fontawesome_icon_name' => 'Krw'],
		'language' => ['no_data_fontawesome_icon_unicode' => '\f1ab', 'no_data_fontawesome_icon_name' => 'Language'],
		'laptop' => ['no_data_fontawesome_icon_unicode' => '\f109', 'no_data_fontawesome_icon_name' => 'Laptop'],
		'lastfm' => ['no_data_fontawesome_icon_unicode' => '\f202', 'no_data_fontawesome_icon_name' => 'Lastfm'],
		'lastfm-square' => ['no_data_fontawesome_icon_unicode' => '\f203', 'no_data_fontawesome_icon_name' => 'Lastfm square'],
		'leaf' => ['no_data_fontawesome_icon_unicode' => '\f06c', 'no_data_fontawesome_icon_name' => 'Leaf'],
		'leanpub' => ['no_data_fontawesome_icon_unicode' => '\f212', 'no_data_fontawesome_icon_name' => 'Leanpub'],
		'lemon-o' => ['no_data_fontawesome_icon_unicode' => '\f094', 'no_data_fontawesome_icon_name' => 'Lemon o'],
		'level-down' => ['no_data_fontawesome_icon_unicode' => '\f149', 'no_data_fontawesome_icon_name' => 'Level down'],
		'level-up' => ['no_data_fontawesome_icon_unicode' => '\f148', 'no_data_fontawesome_icon_name' => 'Level up'],
		'life-ring' => ['no_data_fontawesome_icon_unicode' => '\f1cd', 'no_data_fontawesome_icon_name' => 'Life ring'],
		'lightbulb-o' => ['no_data_fontawesome_icon_unicode' => '\f0eb', 'no_data_fontawesome_icon_name' => 'Lightbulb o'],
		'line-chart' => ['no_data_fontawesome_icon_unicode' => '\f201', 'no_data_fontawesome_icon_name' => 'Line chart'],
		'link' => ['no_data_fontawesome_icon_unicode' => '\f0c1', 'no_data_fontawesome_icon_name' => 'Link'],
		'linkedin' => ['no_data_fontawesome_icon_unicode' => '\f0e1', 'no_data_fontawesome_icon_name' => 'Linkedin'],
		'linkedin-square' => ['no_data_fontawesome_icon_unicode' => '\f08c', 'no_data_fontawesome_icon_name' => 'Linkedin square'],
		'linode' => ['no_data_fontawesome_icon_unicode' => '\f2b8', 'no_data_fontawesome_icon_name' => 'Linode'],
		'linux' => ['no_data_fontawesome_icon_unicode' => '\f17c', 'no_data_fontawesome_icon_name' => 'Linux'],
		'list' => ['no_data_fontawesome_icon_unicode' => '\f03a', 'no_data_fontawesome_icon_name' => 'List'],
		'list-alt' => ['no_data_fontawesome_icon_unicode' => '\f022', 'no_data_fontawesome_icon_name' => 'List alt'],
		'list-ol' => ['no_data_fontawesome_icon_unicode' => '\f0cb', 'no_data_fontawesome_icon_name' => 'List ol'],
		'list-ul' => ['no_data_fontawesome_icon_unicode' => '\f0ca', 'no_data_fontawesome_icon_name' => 'List ul'],
		'location-arrow' => ['no_data_fontawesome_icon_unicode' => '\f124', 'no_data_fontawesome_icon_name' => 'Location arrow'],
		'lock' => ['no_data_fontawesome_icon_unicode' => '\f023', 'no_data_fontawesome_icon_name' => 'Lock'],
		'long-arrow-down' => ['no_data_fontawesome_icon_unicode' => '\f175', 'no_data_fontawesome_icon_name' => 'Long arrow down'],
		'long-arrow-left' => ['no_data_fontawesome_icon_unicode' => '\f177', 'no_data_fontawesome_icon_name' => 'Long arrow left'],
		'long-arrow-right' => ['no_data_fontawesome_icon_unicode' => '\f178', 'no_data_fontawesome_icon_name' => 'Long arrow right'],
		'long-arrow-up' => ['no_data_fontawesome_icon_unicode' => '\f176', 'no_data_fontawesome_icon_name' => 'Long arrow up'],
		'low-vision' => ['no_data_fontawesome_icon_unicode' => '\f2a8', 'no_data_fontawesome_icon_name' => 'Low vision'],
		'magic' => ['no_data_fontawesome_icon_unicode' => '\f0d0', 'no_data_fontawesome_icon_name' => 'Magic'],
		'magnet' => ['no_data_fontawesome_icon_unicode' => '\f076', 'no_data_fontawesome_icon_name' => 'Magnet'],
		'male' => ['no_data_fontawesome_icon_unicode' => '\f183', 'no_data_fontawesome_icon_name' => 'Male'],
		'map' => ['no_data_fontawesome_icon_unicode' => '\f279', 'no_data_fontawesome_icon_name' => 'Map'],
		'map-marker' => ['no_data_fontawesome_icon_unicode' => '\f041', 'no_data_fontawesome_icon_name' => 'Map marker'],
		'map-o' => ['no_data_fontawesome_icon_unicode' => '\f278', 'no_data_fontawesome_icon_name' => 'Map o'],
		'map-pin' => ['no_data_fontawesome_icon_unicode' => '\f276', 'no_data_fontawesome_icon_name' => 'Map pin'],
		'map-signs' => ['no_data_fontawesome_icon_unicode' => '\f277', 'no_data_fontawesome_icon_name' => 'Map signs'],
		'mars' => ['no_data_fontawesome_icon_unicode' => '\f222', 'no_data_fontawesome_icon_name' => 'Mars'],
		'mars-double' => ['no_data_fontawesome_icon_unicode' => '\f227', 'no_data_fontawesome_icon_name' => 'Mars double'],
		'mars-stroke' => ['no_data_fontawesome_icon_unicode' => '\f229', 'no_data_fontawesome_icon_name' => 'Mars stroke'],
		'mars-stroke-h' => ['no_data_fontawesome_icon_unicode' => '\f22b', 'no_data_fontawesome_icon_name' => 'Mars stroke h'],
		'mars-stroke-v' => ['no_data_fontawesome_icon_unicode' => '\f22a', 'no_data_fontawesome_icon_name' => 'Mars stroke v'],
		'maxcdn' => ['no_data_fontawesome_icon_unicode' => '\f136', 'no_data_fontawesome_icon_name' => 'Maxcdn'],
		'meanpath' => ['no_data_fontawesome_icon_unicode' => '\f20c', 'no_data_fontawesome_icon_name' => 'Meanpath'],
		'medium' => ['no_data_fontawesome_icon_unicode' => '\f23a', 'no_data_fontawesome_icon_name' => 'Medium'],
		'medkit' => ['no_data_fontawesome_icon_unicode' => '\f0fa', 'no_data_fontawesome_icon_name' => 'Medkit'],
		'meetup' => ['no_data_fontawesome_icon_unicode' => '\f2e0', 'no_data_fontawesome_icon_name' => 'Meetup'],
		'meh-o' => ['no_data_fontawesome_icon_unicode' => '\f11a', 'no_data_fontawesome_icon_name' => 'Meh o'],
		'mercury' => ['no_data_fontawesome_icon_unicode' => '\f223', 'no_data_fontawesome_icon_name' => 'Mercury'],
		'microchip' => ['no_data_fontawesome_icon_unicode' => '\f2db', 'no_data_fontawesome_icon_name' => 'Microchip'],
		'microphone' => ['no_data_fontawesome_icon_unicode' => '\f130', 'no_data_fontawesome_icon_name' => 'Microphone'],
		'microphone-slash' => ['no_data_fontawesome_icon_unicode' => '\f131', 'no_data_fontawesome_icon_name' => 'Microphone slash'],
		'minus' => ['no_data_fontawesome_icon_unicode' => '\f068', 'no_data_fontawesome_icon_name' => 'Minus'],
		'minus-circle' => ['no_data_fontawesome_icon_unicode' => '\f056', 'no_data_fontawesome_icon_name' => 'Minus circle'],
		'minus-square' => ['no_data_fontawesome_icon_unicode' => '\f146', 'no_data_fontawesome_icon_name' => 'Minus square'],
		'minus-square-o' => ['no_data_fontawesome_icon_unicode' => '\f147', 'no_data_fontawesome_icon_name' => 'Minus square o'],
		'mixcloud' => ['no_data_fontawesome_icon_unicode' => '\f289', 'no_data_fontawesome_icon_name' => 'Mixcloud'],
		'mobile' => ['no_data_fontawesome_icon_unicode' => '\f10b', 'no_data_fontawesome_icon_name' => 'Mobile'],
		'modx' => ['no_data_fontawesome_icon_unicode' => '\f285', 'no_data_fontawesome_icon_name' => 'Modx'],
		'money' => ['no_data_fontawesome_icon_unicode' => '\f0d6', 'no_data_fontawesome_icon_name' => 'Money'],
		'moon-o' => ['no_data_fontawesome_icon_unicode' => '\f186', 'no_data_fontawesome_icon_name' => 'Moon o'],
		'motorcycle' => ['no_data_fontawesome_icon_unicode' => '\f21c', 'no_data_fontawesome_icon_name' => 'Motorcycle'],
		'mouse-pointer' => ['no_data_fontawesome_icon_unicode' => '\f245', 'no_data_fontawesome_icon_name' => 'Mouse pointer'],
		'music' => ['no_data_fontawesome_icon_unicode' => '\f001', 'no_data_fontawesome_icon_name' => 'Music'],
		'neuter' => ['no_data_fontawesome_icon_unicode' => '\f22c', 'no_data_fontawesome_icon_name' => 'Neuter'],
		'newspaper-o' => ['no_data_fontawesome_icon_unicode' => '\f1ea', 'no_data_fontawesome_icon_name' => 'Newspaper o'],
		'object-group' => ['no_data_fontawesome_icon_unicode' => '\f247', 'no_data_fontawesome_icon_name' => 'Object group'],
		'object-ungroup' => ['no_data_fontawesome_icon_unicode' => '\f248', 'no_data_fontawesome_icon_name' => 'Object ungroup'],
		'odnoklassniki' => ['no_data_fontawesome_icon_unicode' => '\f263', 'no_data_fontawesome_icon_name' => 'Odnoklassniki'],
		'odnoklassniki-square' => ['no_data_fontawesome_icon_unicode' => '\f264', 'no_data_fontawesome_icon_name' => 'Odnoklassniki square'],
		'opencart' => ['no_data_fontawesome_icon_unicode' => '\f23d', 'no_data_fontawesome_icon_name' => 'Opencart'],
		'openid' => ['no_data_fontawesome_icon_unicode' => '\f19b', 'no_data_fontawesome_icon_name' => 'Openid'],
		'opera' => ['no_data_fontawesome_icon_unicode' => '\f26a', 'no_data_fontawesome_icon_name' => 'Opera'],
		'optin-monster' => ['no_data_fontawesome_icon_unicode' => '\f23c', 'no_data_fontawesome_icon_name' => 'Optin monster'],
		'outdent' => ['no_data_fontawesome_icon_unicode' => '\f03b', 'no_data_fontawesome_icon_name' => 'Outdent'],
		'pagelines' => ['no_data_fontawesome_icon_unicode' => '\f18c', 'no_data_fontawesome_icon_name' => 'Pagelines'],
		'paint-brush' => ['no_data_fontawesome_icon_unicode' => '\f1fc', 'no_data_fontawesome_icon_name' => 'Paint brush'],
		'paper-plane' => ['no_data_fontawesome_icon_unicode' => '\f1d8', 'no_data_fontawesome_icon_name' => 'Paper plane'],
		'paper-plane-o' => ['no_data_fontawesome_icon_unicode' => '\f1d9', 'no_data_fontawesome_icon_name' => 'Paper plane o'],
		'paperclip' => ['no_data_fontawesome_icon_unicode' => '\f0c6', 'no_data_fontawesome_icon_name' => 'Paperclip'],
		'paragraph' => ['no_data_fontawesome_icon_unicode' => '\f1dd', 'no_data_fontawesome_icon_name' => 'Paragraph'],
		'pause' => ['no_data_fontawesome_icon_unicode' => '\f04c', 'no_data_fontawesome_icon_name' => 'Pause'],
		'pause-circle' => ['no_data_fontawesome_icon_unicode' => '\f28b', 'no_data_fontawesome_icon_name' => 'Pause circle'],
		'pause-circle-o' => ['no_data_fontawesome_icon_unicode' => '\f28c', 'no_data_fontawesome_icon_name' => 'Pause circle o'],
		'paw' => ['no_data_fontawesome_icon_unicode' => '\f1b0', 'no_data_fontawesome_icon_name' => 'Paw'],
		'paypal' => ['no_data_fontawesome_icon_unicode' => '\f1ed', 'no_data_fontawesome_icon_name' => 'Paypal'],
		'pencil' => ['no_data_fontawesome_icon_unicode' => '\f040', 'no_data_fontawesome_icon_name' => 'Pencil'],
		'pencil-square' => ['no_data_fontawesome_icon_unicode' => '\f14b', 'no_data_fontawesome_icon_name' => 'Pencil square'],
		'pencil-square-o' => ['no_data_fontawesome_icon_unicode' => '\f044', 'no_data_fontawesome_icon_name' => 'Pencil square o'],
		'percent' => ['no_data_fontawesome_icon_unicode' => '\f295', 'no_data_fontawesome_icon_name' => 'Percent'],
		'phone' => ['no_data_fontawesome_icon_unicode' => '\f095', 'no_data_fontawesome_icon_name' => 'Phone'],
		'phone-square' => ['no_data_fontawesome_icon_unicode' => '\f098', 'no_data_fontawesome_icon_name' => 'Phone square'],
		'picture-o' => ['no_data_fontawesome_icon_unicode' => '\f03e', 'no_data_fontawesome_icon_name' => 'Picture o'],
		'pie-chart' => ['no_data_fontawesome_icon_unicode' => '\f200', 'no_data_fontawesome_icon_name' => 'Pie chart'],
		'pied-piper' => ['no_data_fontawesome_icon_unicode' => '\f2ae', 'no_data_fontawesome_icon_name' => 'Pied piper'],
		'pied-piper-alt' => ['no_data_fontawesome_icon_unicode' => '\f1a8', 'no_data_fontawesome_icon_name' => 'Pied piper alt'],
		'pied-piper-pp' => ['no_data_fontawesome_icon_unicode' => '\f1a7', 'no_data_fontawesome_icon_name' => 'Pied piper pp'],
		'pinterest' => ['no_data_fontawesome_icon_unicode' => '\f0d2', 'no_data_fontawesome_icon_name' => 'Pinterest'],
		'pinterest-p' => ['no_data_fontawesome_icon_unicode' => '\f231', 'no_data_fontawesome_icon_name' => 'Pinterest p'],
		'pinterest-square' => ['no_data_fontawesome_icon_unicode' => '\f0d3', 'no_data_fontawesome_icon_name' => 'Pinterest square'],
		'plane' => ['no_data_fontawesome_icon_unicode' => '\f072', 'no_data_fontawesome_icon_name' => 'Plane'],
		'play' => ['no_data_fontawesome_icon_unicode' => '\f04b', 'no_data_fontawesome_icon_name' => 'Play'],
		'play-circle' => ['no_data_fontawesome_icon_unicode' => '\f144', 'no_data_fontawesome_icon_name' => 'Play circle'],
		'play-circle-o' => ['no_data_fontawesome_icon_unicode' => '\f01d', 'no_data_fontawesome_icon_name' => 'Play circle o'],
		'plug' => ['no_data_fontawesome_icon_unicode' => '\f1e6', 'no_data_fontawesome_icon_name' => 'Plug'],
		'plus' => ['no_data_fontawesome_icon_unicode' => '\f067', 'no_data_fontawesome_icon_name' => 'Plus'],
		'plus-circle' => ['no_data_fontawesome_icon_unicode' => '\f055', 'no_data_fontawesome_icon_name' => 'Plus circle'],
		'plus-square' => ['no_data_fontawesome_icon_unicode' => '\f0fe', 'no_data_fontawesome_icon_name' => 'Plus square'],
		'plus-square-o' => ['no_data_fontawesome_icon_unicode' => '\f196', 'no_data_fontawesome_icon_name' => 'Plus square o'],
		'podcast' => ['no_data_fontawesome_icon_unicode' => '\f2ce', 'no_data_fontawesome_icon_name' => 'Podcast'],
		'power-off' => ['no_data_fontawesome_icon_unicode' => '\f011', 'no_data_fontawesome_icon_name' => 'Power off'],
		'print' => ['no_data_fontawesome_icon_unicode' => '\f02f', 'no_data_fontawesome_icon_name' => 'Print'],
		'product-hunt' => ['no_data_fontawesome_icon_unicode' => '\f288', 'no_data_fontawesome_icon_name' => 'Product hunt'],
		'puzzle-piece' => ['no_data_fontawesome_icon_unicode' => '\f12e', 'no_data_fontawesome_icon_name' => 'Puzzle piece'],
		'qq' => ['no_data_fontawesome_icon_unicode' => '\f1d6', 'no_data_fontawesome_icon_name' => 'Qq'],
		'qrcode' => ['no_data_fontawesome_icon_unicode' => '\f029', 'no_data_fontawesome_icon_name' => 'Qrcode'],
		'question' => ['no_data_fontawesome_icon_unicode' => '\f128', 'no_data_fontawesome_icon_name' => 'Question'],
		'question-circle' => ['no_data_fontawesome_icon_unicode' => '\f059', 'no_data_fontawesome_icon_name' => 'Question circle'],
		'question-circle-o' => ['no_data_fontawesome_icon_unicode' => '\f29c', 'no_data_fontawesome_icon_name' => 'Question circle o'],
		'quora' => ['no_data_fontawesome_icon_unicode' => '\f2c4', 'no_data_fontawesome_icon_name' => 'Quora'],
		'quote-left' => ['no_data_fontawesome_icon_unicode' => '\f10d', 'no_data_fontawesome_icon_name' => 'Quote left'],
		'quote-right' => ['no_data_fontawesome_icon_unicode' => '\f10e', 'no_data_fontawesome_icon_name' => 'Quote right'],
		'random' => ['no_data_fontawesome_icon_unicode' => '\f074', 'no_data_fontawesome_icon_name' => 'Random'],
		'ravelry' => ['no_data_fontawesome_icon_unicode' => '\f2d9', 'no_data_fontawesome_icon_name' => 'Ravelry'],
		'rebel' => ['no_data_fontawesome_icon_unicode' => '\f1d0', 'no_data_fontawesome_icon_name' => 'Rebel'],
		'recycle' => ['no_data_fontawesome_icon_unicode' => '\f1b8', 'no_data_fontawesome_icon_name' => 'Recycle'],
		'reddit' => ['no_data_fontawesome_icon_unicode' => '\f1a1', 'no_data_fontawesome_icon_name' => 'Reddit'],
		'reddit-alien' => ['no_data_fontawesome_icon_unicode' => '\f281', 'no_data_fontawesome_icon_name' => 'Reddit alien'],
		'reddit-square' => ['no_data_fontawesome_icon_unicode' => '\f1a2', 'no_data_fontawesome_icon_name' => 'Reddit square'],
		'refresh' => ['no_data_fontawesome_icon_unicode' => '\f021', 'no_data_fontawesome_icon_name' => 'Refresh'],
		'registered' => ['no_data_fontawesome_icon_unicode' => '\f25d', 'no_data_fontawesome_icon_name' => 'Registered'],
		'renren' => ['no_data_fontawesome_icon_unicode' => '\f18b', 'no_data_fontawesome_icon_name' => 'Renren'],
		'repeat' => ['no_data_fontawesome_icon_unicode' => '\f01e', 'no_data_fontawesome_icon_name' => 'Repeat'],
		'reply' => ['no_data_fontawesome_icon_unicode' => '\f112', 'no_data_fontawesome_icon_name' => 'Reply'],
		'reply-all' => ['no_data_fontawesome_icon_unicode' => '\f122', 'no_data_fontawesome_icon_name' => 'Reply all'],
		'retweet' => ['no_data_fontawesome_icon_unicode' => '\f079', 'no_data_fontawesome_icon_name' => 'Retweet'],
		'road' => ['no_data_fontawesome_icon_unicode' => '\f018', 'no_data_fontawesome_icon_name' => 'Road'],
		'rocket' => ['no_data_fontawesome_icon_unicode' => '\f135', 'no_data_fontawesome_icon_name' => 'Rocket'],
		'rss' => ['no_data_fontawesome_icon_unicode' => '\f09e', 'no_data_fontawesome_icon_name' => 'Rss'],
		'rss-square' => ['no_data_fontawesome_icon_unicode' => '\f143', 'no_data_fontawesome_icon_name' => 'Rss square'],
		'rub' => ['no_data_fontawesome_icon_unicode' => '\f158', 'no_data_fontawesome_icon_name' => 'Rub'],
		'safari' => ['no_data_fontawesome_icon_unicode' => '\f267', 'no_data_fontawesome_icon_name' => 'Safari'],
		'scissors' => ['no_data_fontawesome_icon_unicode' => '\f0c4', 'no_data_fontawesome_icon_name' => 'Scissors'],
		'scribd' => ['no_data_fontawesome_icon_unicode' => '\f28a', 'no_data_fontawesome_icon_name' => 'Scribd'],
		'search' => ['no_data_fontawesome_icon_unicode' => '\f002', 'no_data_fontawesome_icon_name' => 'Search'],
		'search-minus' => ['no_data_fontawesome_icon_unicode' => '\f010', 'no_data_fontawesome_icon_name' => 'Search minus'],
		'search-plus' => ['no_data_fontawesome_icon_unicode' => '\f00e', 'no_data_fontawesome_icon_name' => 'Search plus'],
		'sellsy' => ['no_data_fontawesome_icon_unicode' => '\f213', 'no_data_fontawesome_icon_name' => 'Sellsy'],
		'server' => ['no_data_fontawesome_icon_unicode' => '\f233', 'no_data_fontawesome_icon_name' => 'Server'],
		'share' => ['no_data_fontawesome_icon_unicode' => '\f064', 'no_data_fontawesome_icon_name' => 'Share'],
		'share-alt' => ['no_data_fontawesome_icon_unicode' => '\f1e0', 'no_data_fontawesome_icon_name' => 'Share alt'],
		'share-alt-square' => ['no_data_fontawesome_icon_unicode' => '\f1e1', 'no_data_fontawesome_icon_name' => 'Share alt square'],
		'share-square' => ['no_data_fontawesome_icon_unicode' => '\f14d', 'no_data_fontawesome_icon_name' => 'Share square'],
		'share-square-o' => ['no_data_fontawesome_icon_unicode' => '\f045', 'no_data_fontawesome_icon_name' => 'Share square o'],
		'shield' => ['no_data_fontawesome_icon_unicode' => '\f132', 'no_data_fontawesome_icon_name' => 'Shield'],
		'ship' => ['no_data_fontawesome_icon_unicode' => '\f21a', 'no_data_fontawesome_icon_name' => 'Ship'],
		'shirtsinbulk' => ['no_data_fontawesome_icon_unicode' => '\f214', 'no_data_fontawesome_icon_name' => 'Shirtsinbulk'],
		'shopping-bag' => ['no_data_fontawesome_icon_unicode' => '\f290', 'no_data_fontawesome_icon_name' => 'Shopping bag'],
		'shopping-basket' => ['no_data_fontawesome_icon_unicode' => '\f291', 'no_data_fontawesome_icon_name' => 'Shopping basket'],
		'shopping-cart' => ['no_data_fontawesome_icon_unicode' => '\f07a', 'no_data_fontawesome_icon_name' => 'Shopping cart'],
		'shower' => ['no_data_fontawesome_icon_unicode' => '\f2cc', 'no_data_fontawesome_icon_name' => 'Shower'],
		'sign-in' => ['no_data_fontawesome_icon_unicode' => '\f090', 'no_data_fontawesome_icon_name' => 'Sign in'],
		'sign-language' => ['no_data_fontawesome_icon_unicode' => '\f2a7', 'no_data_fontawesome_icon_name' => 'Sign language'],
		'sign-out' => ['no_data_fontawesome_icon_unicode' => '\f08b', 'no_data_fontawesome_icon_name' => 'Sign out'],
		'signal' => ['no_data_fontawesome_icon_unicode' => '\f012', 'no_data_fontawesome_icon_name' => 'Signal'],
		'simplybuilt' => ['no_data_fontawesome_icon_unicode' => '\f215', 'no_data_fontawesome_icon_name' => 'Simplybuilt'],
		'sitemap' => ['no_data_fontawesome_icon_unicode' => '\f0e8', 'no_data_fontawesome_icon_name' => 'Sitemap'],
		'skyatlas' => ['no_data_fontawesome_icon_unicode' => '\f216', 'no_data_fontawesome_icon_name' => 'Skyatlas'],
		'skype' => ['no_data_fontawesome_icon_unicode' => '\f17e', 'no_data_fontawesome_icon_name' => 'Skype'],
		'slack' => ['no_data_fontawesome_icon_unicode' => '\f198', 'no_data_fontawesome_icon_name' => 'Slack'],
		'sliders' => ['no_data_fontawesome_icon_unicode' => '\f1de', 'no_data_fontawesome_icon_name' => 'Sliders'],
		'slideshare' => ['no_data_fontawesome_icon_unicode' => '\f1e7', 'no_data_fontawesome_icon_name' => 'Slideshare'],
		'smile-o' => ['no_data_fontawesome_icon_unicode' => '\f118', 'no_data_fontawesome_icon_name' => 'Smile o'],
		'snapchat' => ['no_data_fontawesome_icon_unicode' => '\f2ab', 'no_data_fontawesome_icon_name' => 'Snapchat'],
		'snapchat-ghost' => ['no_data_fontawesome_icon_unicode' => '\f2ac', 'no_data_fontawesome_icon_name' => 'Snapchat ghost'],
		'snapchat-square' => ['no_data_fontawesome_icon_unicode' => '\f2ad', 'no_data_fontawesome_icon_name' => 'Snapchat square'],
		'snowflake-o' => ['no_data_fontawesome_icon_unicode' => '\f2dc', 'no_data_fontawesome_icon_name' => 'Snowflake o'],
		'sort' => ['no_data_fontawesome_icon_unicode' => '\f0dc', 'no_data_fontawesome_icon_name' => 'Sort'],
		'sort-alpha-asc' => ['no_data_fontawesome_icon_unicode' => '\f15d', 'no_data_fontawesome_icon_name' => 'Sort alpha asc'],
		'sort-alpha-desc' => ['no_data_fontawesome_icon_unicode' => '\f15e', 'no_data_fontawesome_icon_name' => 'Sort alpha desc'],
		'sort-amount-asc' => ['no_data_fontawesome_icon_unicode' => '\f160', 'no_data_fontawesome_icon_name' => 'Sort amount asc'],
		'sort-amount-desc' => ['no_data_fontawesome_icon_unicode' => '\f161', 'no_data_fontawesome_icon_name' => 'Sort amount desc'],
		'sort-asc' => ['no_data_fontawesome_icon_unicode' => '\f0de', 'no_data_fontawesome_icon_name' => 'Sort asc'],
		'sort-desc' => ['no_data_fontawesome_icon_unicode' => '\f0dd', 'no_data_fontawesome_icon_name' => 'Sort desc'],
		'sort-numeric-asc' => ['no_data_fontawesome_icon_unicode' => '\f162', 'no_data_fontawesome_icon_name' => 'Sort numeric asc'],
		'sort-numeric-desc' => ['no_data_fontawesome_icon_unicode' => '\f163', 'no_data_fontawesome_icon_name' => 'Sort numeric desc'],
		'soundcloud' => ['no_data_fontawesome_icon_unicode' => '\f1be', 'no_data_fontawesome_icon_name' => 'Soundcloud'],
		'space-shuttle' => ['no_data_fontawesome_icon_unicode' => '\f197', 'no_data_fontawesome_icon_name' => 'Space shuttle'],
		'spinner' => ['no_data_fontawesome_icon_unicode' => '\f110', 'no_data_fontawesome_icon_name' => 'Spinner'],
		'spoon' => ['no_data_fontawesome_icon_unicode' => '\f1b1', 'no_data_fontawesome_icon_name' => 'Spoon'],
		'spotify' => ['no_data_fontawesome_icon_unicode' => '\f1bc', 'no_data_fontawesome_icon_name' => 'Spotify'],
		'square' => ['no_data_fontawesome_icon_unicode' => '\f0c8', 'no_data_fontawesome_icon_name' => 'Square'],
		'square-o' => ['no_data_fontawesome_icon_unicode' => '\f096', 'no_data_fontawesome_icon_name' => 'Square o'],
		'stack-exchange' => ['no_data_fontawesome_icon_unicode' => '\f18d', 'no_data_fontawesome_icon_name' => 'Stack exchange'],
		'stack-overflow' => ['no_data_fontawesome_icon_unicode' => '\f16c', 'no_data_fontawesome_icon_name' => 'Stack overflow'],
		'star' => ['no_data_fontawesome_icon_unicode' => '\f005', 'no_data_fontawesome_icon_name' => 'Star'],
		'star-half' => ['no_data_fontawesome_icon_unicode' => '\f089', 'no_data_fontawesome_icon_name' => 'Star half'],
		'star-half-o' => ['no_data_fontawesome_icon_unicode' => '\f123', 'no_data_fontawesome_icon_name' => 'Star half o'],
		'star-o' => ['no_data_fontawesome_icon_unicode' => '\f006', 'no_data_fontawesome_icon_name' => 'Star o'],
		'steam' => ['no_data_fontawesome_icon_unicode' => '\f1b6', 'no_data_fontawesome_icon_name' => 'Steam'],
		'steam-square' => ['no_data_fontawesome_icon_unicode' => '\f1b7', 'no_data_fontawesome_icon_name' => 'Steam square'],
		'step-backward' => ['no_data_fontawesome_icon_unicode' => '\f048', 'no_data_fontawesome_icon_name' => 'Step backward'],
		'step-forward' => ['no_data_fontawesome_icon_unicode' => '\f051', 'no_data_fontawesome_icon_name' => 'Step forward'],
		'stethoscope' => ['no_data_fontawesome_icon_unicode' => '\f0f1', 'no_data_fontawesome_icon_name' => 'Stethoscope'],
		'sticky-note' => ['no_data_fontawesome_icon_unicode' => '\f249', 'no_data_fontawesome_icon_name' => 'Sticky note'],
		'sticky-note-o' => ['no_data_fontawesome_icon_unicode' => '\f24a', 'no_data_fontawesome_icon_name' => 'Sticky note o'],
		'stop' => ['no_data_fontawesome_icon_unicode' => '\f04d', 'no_data_fontawesome_icon_name' => 'Stop'],
		'stop-circle' => ['no_data_fontawesome_icon_unicode' => '\f28d', 'no_data_fontawesome_icon_name' => 'Stop circle'],
		'stop-circle-o' => ['no_data_fontawesome_icon_unicode' => '\f28e', 'no_data_fontawesome_icon_name' => 'Stop circle o'],
		'street-view' => ['no_data_fontawesome_icon_unicode' => '\f21d', 'no_data_fontawesome_icon_name' => 'Street view'],
		'strikethrough' => ['no_data_fontawesome_icon_unicode' => '\f0cc', 'no_data_fontawesome_icon_name' => 'Strikethrough'],
		'stumbleupon' => ['no_data_fontawesome_icon_unicode' => '\f1a4', 'no_data_fontawesome_icon_name' => 'Stumbleupon'],
		'stumbleupon-circle' => ['no_data_fontawesome_icon_unicode' => '\f1a3', 'no_data_fontawesome_icon_name' => 'Stumbleupon circle'],
		'subscript' => ['no_data_fontawesome_icon_unicode' => '\f12c', 'no_data_fontawesome_icon_name' => 'Subscript'],
		'subway' => ['no_data_fontawesome_icon_unicode' => '\f239', 'no_data_fontawesome_icon_name' => 'Subway'],
		'suitcase' => ['no_data_fontawesome_icon_unicode' => '\f0f2', 'no_data_fontawesome_icon_name' => 'Suitcase'],
		'sun-o' => ['no_data_fontawesome_icon_unicode' => '\f185', 'no_data_fontawesome_icon_name' => 'Sun o'],
		'superpowers' => ['no_data_fontawesome_icon_unicode' => '\f2dd', 'no_data_fontawesome_icon_name' => 'Superpowers'],
		'superscript' => ['no_data_fontawesome_icon_unicode' => '\f12b', 'no_data_fontawesome_icon_name' => 'Superscript'],
		'table' => ['no_data_fontawesome_icon_unicode' => '\f0ce', 'no_data_fontawesome_icon_name' => 'Table'],
		'tablet' => ['no_data_fontawesome_icon_unicode' => '\f10a', 'no_data_fontawesome_icon_name' => 'Tablet'],
		'tachometer' => ['no_data_fontawesome_icon_unicode' => '\f0e4', 'no_data_fontawesome_icon_name' => 'Tachometer'],
		'tag' => ['no_data_fontawesome_icon_unicode' => '\f02b', 'no_data_fontawesome_icon_name' => 'Tag'],
		'tags' => ['no_data_fontawesome_icon_unicode' => '\f02c', 'no_data_fontawesome_icon_name' => 'Tags'],
		'tasks' => ['no_data_fontawesome_icon_unicode' => '\f0ae', 'no_data_fontawesome_icon_name' => 'Tasks'],
		'taxi' => ['no_data_fontawesome_icon_unicode' => '\f1ba', 'no_data_fontawesome_icon_name' => 'Taxi'],
		'telegram' => ['no_data_fontawesome_icon_unicode' => '\f2c6', 'no_data_fontawesome_icon_name' => 'Telegram'],
		'television' => ['no_data_fontawesome_icon_unicode' => '\f26c', 'no_data_fontawesome_icon_name' => 'Television'],
		'tencent-weibo' => ['no_data_fontawesome_icon_unicode' => '\f1d5', 'no_data_fontawesome_icon_name' => 'Tencent weibo'],
		'terminal' => ['no_data_fontawesome_icon_unicode' => '\f120', 'no_data_fontawesome_icon_name' => 'Terminal'],
		'text-height' => ['no_data_fontawesome_icon_unicode' => '\f034', 'no_data_fontawesome_icon_name' => 'Text height'],
		'text-width' => ['no_data_fontawesome_icon_unicode' => '\f035', 'no_data_fontawesome_icon_name' => 'Text width'],
		'th' => ['no_data_fontawesome_icon_unicode' => '\f00a', 'no_data_fontawesome_icon_name' => 'Th'],
		'th-large' => ['no_data_fontawesome_icon_unicode' => '\f009', 'no_data_fontawesome_icon_name' => 'Th large'],
		'th-list' => ['no_data_fontawesome_icon_unicode' => '\f00b', 'no_data_fontawesome_icon_name' => 'Th list'],
		'themeisle' => ['no_data_fontawesome_icon_unicode' => '\f2b2', 'no_data_fontawesome_icon_name' => 'Themeisle'],
		'thermometer-empty' => ['no_data_fontawesome_icon_unicode' => '\f2cb', 'no_data_fontawesome_icon_name' => 'Thermometer empty'],
		'thermometer-full' => ['no_data_fontawesome_icon_unicode' => '\f2c7', 'no_data_fontawesome_icon_name' => 'Thermometer full'],
		'thermometer-half' => ['no_data_fontawesome_icon_unicode' => '\f2c9', 'no_data_fontawesome_icon_name' => 'Thermometer half'],
		'thermometer-quarter' => ['no_data_fontawesome_icon_unicode' => '\f2ca', 'no_data_fontawesome_icon_name' => 'Thermometer quarter'],
		'thermometer-three-quarters' => ['no_data_fontawesome_icon_unicode' => '\f2c8', 'no_data_fontawesome_icon_name' => 'Thermometer three quarters'],
		'thumb-tack' => ['no_data_fontawesome_icon_unicode' => '\f08d', 'no_data_fontawesome_icon_name' => 'Thumb tack'],
		'thumbs-down' => ['no_data_fontawesome_icon_unicode' => '\f165', 'no_data_fontawesome_icon_name' => 'Thumbs down'],
		'thumbs-o-down' => ['no_data_fontawesome_icon_unicode' => '\f088', 'no_data_fontawesome_icon_name' => 'Thumbs o down'],
		'thumbs-o-up' => ['no_data_fontawesome_icon_unicode' => '\f087', 'no_data_fontawesome_icon_name' => 'Thumbs o up'],
		'thumbs-up' => ['no_data_fontawesome_icon_unicode' => '\f164', 'no_data_fontawesome_icon_name' => 'Thumbs up'],
		'ticket' => ['no_data_fontawesome_icon_unicode' => '\f145', 'no_data_fontawesome_icon_name' => 'Ticket'],
		'times' => ['no_data_fontawesome_icon_unicode' => '\f00d', 'no_data_fontawesome_icon_name' => 'Times'],
		'times-circle' => ['no_data_fontawesome_icon_unicode' => '\f057', 'no_data_fontawesome_icon_name' => 'Times circle'],
		'times-circle-o' => ['no_data_fontawesome_icon_unicode' => '\f05c', 'no_data_fontawesome_icon_name' => 'Times circle o'],
		'tint' => ['no_data_fontawesome_icon_unicode' => '\f043', 'no_data_fontawesome_icon_name' => 'Tint'],
		'toggle-off' => ['no_data_fontawesome_icon_unicode' => '\f204', 'no_data_fontawesome_icon_name' => 'Toggle off'],
		'toggle-on' => ['no_data_fontawesome_icon_unicode' => '\f205', 'no_data_fontawesome_icon_name' => 'Toggle on'],
		'trademark' => ['no_data_fontawesome_icon_unicode' => '\f25c', 'no_data_fontawesome_icon_name' => 'Trademark'],
		'train' => ['no_data_fontawesome_icon_unicode' => '\f238', 'no_data_fontawesome_icon_name' => 'Train'],
		'transgender' => ['no_data_fontawesome_icon_unicode' => '\f224', 'no_data_fontawesome_icon_name' => 'Transgender'],
		'transgender-alt' => ['no_data_fontawesome_icon_unicode' => '\f225', 'no_data_fontawesome_icon_name' => 'Transgender alt'],
		'trash' => ['no_data_fontawesome_icon_unicode' => '\f1f8', 'no_data_fontawesome_icon_name' => 'Trash'],
		'trash-o' => ['no_data_fontawesome_icon_unicode' => '\f014', 'no_data_fontawesome_icon_name' => 'Trash o'],
		'tree' => ['no_data_fontawesome_icon_unicode' => '\f1bb', 'no_data_fontawesome_icon_name' => 'Tree'],
		'trello' => ['no_data_fontawesome_icon_unicode' => '\f181', 'no_data_fontawesome_icon_name' => 'Trello'],
		'tripadvisor' => ['no_data_fontawesome_icon_unicode' => '\f262', 'no_data_fontawesome_icon_name' => 'Tripadvisor'],
		'trophy' => ['no_data_fontawesome_icon_unicode' => '\f091', 'no_data_fontawesome_icon_name' => 'Trophy'],
		'truck' => ['no_data_fontawesome_icon_unicode' => '\f0d1', 'no_data_fontawesome_icon_name' => 'Truck'],
		'try' => ['no_data_fontawesome_icon_unicode' => '\f195', 'no_data_fontawesome_icon_name' => 'Try'],
		'tty' => ['no_data_fontawesome_icon_unicode' => '\f1e4', 'no_data_fontawesome_icon_name' => 'Tty'],
		'tumblr' => ['no_data_fontawesome_icon_unicode' => '\f173', 'no_data_fontawesome_icon_name' => 'Tumblr'],
		'tumblr-square' => ['no_data_fontawesome_icon_unicode' => '\f174', 'no_data_fontawesome_icon_name' => 'Tumblr square'],
		'twitch' => ['no_data_fontawesome_icon_unicode' => '\f1e8', 'no_data_fontawesome_icon_name' => 'Twitch'],
		'twitter' => ['no_data_fontawesome_icon_unicode' => '\f099', 'no_data_fontawesome_icon_name' => 'Twitter'],
		'twitter-square' => ['no_data_fontawesome_icon_unicode' => '\f081', 'no_data_fontawesome_icon_name' => 'Twitter square'],
		'umbrella' => ['no_data_fontawesome_icon_unicode' => '\f0e9', 'no_data_fontawesome_icon_name' => 'Umbrella'],
		'underline' => ['no_data_fontawesome_icon_unicode' => '\f0cd', 'no_data_fontawesome_icon_name' => 'Underline'],
		'undo' => ['no_data_fontawesome_icon_unicode' => '\f0e2', 'no_data_fontawesome_icon_name' => 'Undo'],
		'universal-access' => ['no_data_fontawesome_icon_unicode' => '\f29a', 'no_data_fontawesome_icon_name' => 'Universal access'],
		'university' => ['no_data_fontawesome_icon_unicode' => '\f19c', 'no_data_fontawesome_icon_name' => 'University'],
		'unlock' => ['no_data_fontawesome_icon_unicode' => '\f09c', 'no_data_fontawesome_icon_name' => 'Unlock'],
		'unlock-alt' => ['no_data_fontawesome_icon_unicode' => '\f13e', 'no_data_fontawesome_icon_name' => 'Unlock alt'],
		'upload' => ['no_data_fontawesome_icon_unicode' => '\f093', 'no_data_fontawesome_icon_name' => 'Upload'],
		'usb' => ['no_data_fontawesome_icon_unicode' => '\f287', 'no_data_fontawesome_icon_name' => 'Usb'],
		'usd' => ['no_data_fontawesome_icon_unicode' => '\f155', 'no_data_fontawesome_icon_name' => 'Usd'],
		'user' => ['no_data_fontawesome_icon_unicode' => '\f007', 'no_data_fontawesome_icon_name' => 'User'],
		'user-circle' => ['no_data_fontawesome_icon_unicode' => '\f2bd', 'no_data_fontawesome_icon_name' => 'User circle'],
		'user-circle-o' => ['no_data_fontawesome_icon_unicode' => '\f2be', 'no_data_fontawesome_icon_name' => 'User circle o'],
		'user-md' => ['no_data_fontawesome_icon_unicode' => '\f0f0', 'no_data_fontawesome_icon_name' => 'User md'],
		'user-o' => ['no_data_fontawesome_icon_unicode' => '\f2c0', 'no_data_fontawesome_icon_name' => 'User o'],
		'user-plus' => ['no_data_fontawesome_icon_unicode' => '\f234', 'no_data_fontawesome_icon_name' => 'User plus'],
		'user-secret' => ['no_data_fontawesome_icon_unicode' => '\f21b', 'no_data_fontawesome_icon_name' => 'User secret'],
		'user-times' => ['no_data_fontawesome_icon_unicode' => '\f235', 'no_data_fontawesome_icon_name' => 'User times'],
		'users' => ['no_data_fontawesome_icon_unicode' => '\f0c0', 'no_data_fontawesome_icon_name' => 'Users'],
		'venus' => ['no_data_fontawesome_icon_unicode' => '\f221', 'no_data_fontawesome_icon_name' => 'Venus'],
		'venus-double' => ['no_data_fontawesome_icon_unicode' => '\f226', 'no_data_fontawesome_icon_name' => 'Venus double'],
		'venus-mars' => ['no_data_fontawesome_icon_unicode' => '\f228', 'no_data_fontawesome_icon_name' => 'Venus mars'],
		'viacoin' => ['no_data_fontawesome_icon_unicode' => '\f237', 'no_data_fontawesome_icon_name' => 'Viacoin'],
		'viadeo' => ['no_data_fontawesome_icon_unicode' => '\f2a9', 'no_data_fontawesome_icon_name' => 'Viadeo'],
		'viadeo-square' => ['no_data_fontawesome_icon_unicode' => '\f2aa', 'no_data_fontawesome_icon_name' => 'Viadeo square'],
		'video-camera' => ['no_data_fontawesome_icon_unicode' => '\f03d', 'no_data_fontawesome_icon_name' => 'Video camera'],
		'vimeo' => ['no_data_fontawesome_icon_unicode' => '\f27d', 'no_data_fontawesome_icon_name' => 'Vimeo'],
		'vimeo-square' => ['no_data_fontawesome_icon_unicode' => '\f194', 'no_data_fontawesome_icon_name' => 'Vimeo square'],
		'vine' => ['no_data_fontawesome_icon_unicode' => '\f1ca', 'no_data_fontawesome_icon_name' => 'Vine'],
		'vk' => ['no_data_fontawesome_icon_unicode' => '\f189', 'no_data_fontawesome_icon_name' => 'Vk'],
		'volume-control-phone' => ['no_data_fontawesome_icon_unicode' => '\f2a0', 'no_data_fontawesome_icon_name' => 'Volume control phone'],
		'volume-down' => ['no_data_fontawesome_icon_unicode' => '\f027', 'no_data_fontawesome_icon_name' => 'Volume down'],
		'volume-off' => ['no_data_fontawesome_icon_unicode' => '\f026', 'no_data_fontawesome_icon_name' => 'Volume off'],
		'volume-up' => ['no_data_fontawesome_icon_unicode' => '\f028', 'no_data_fontawesome_icon_name' => 'Volume up'],
		'weibo' => ['no_data_fontawesome_icon_unicode' => '\f18a', 'no_data_fontawesome_icon_name' => 'Weibo'],
		'weixin' => ['no_data_fontawesome_icon_unicode' => '\f1d7', 'no_data_fontawesome_icon_name' => 'Weixin'],
		'whatsapp' => ['no_data_fontawesome_icon_unicode' => '\f232', 'no_data_fontawesome_icon_name' => 'Whatsapp'],
		'wheelchair' => ['no_data_fontawesome_icon_unicode' => '\f193', 'no_data_fontawesome_icon_name' => 'Wheelchair'],
		'wheelchair-alt' => ['no_data_fontawesome_icon_unicode' => '\f29b', 'no_data_fontawesome_icon_name' => 'Wheelchair alt'],
		'wifi' => ['no_data_fontawesome_icon_unicode' => '\f1eb', 'no_data_fontawesome_icon_name' => 'Wifi'],
		'wikipedia-w' => ['no_data_fontawesome_icon_unicode' => '\f266', 'no_data_fontawesome_icon_name' => 'Wikipedia w'],
		'window-close' => ['no_data_fontawesome_icon_unicode' => '\f2d3', 'no_data_fontawesome_icon_name' => 'Window close'],
		'window-close-o' => ['no_data_fontawesome_icon_unicode' => '\f2d4', 'no_data_fontawesome_icon_name' => 'Window close o'],
		'window-maximize' => ['no_data_fontawesome_icon_unicode' => '\f2d0', 'no_data_fontawesome_icon_name' => 'Window maximize'],
		'window-minimize' => ['no_data_fontawesome_icon_unicode' => '\f2d1', 'no_data_fontawesome_icon_name' => 'Window minimize'],
		'window-restore' => ['no_data_fontawesome_icon_unicode' => '\f2d2', 'no_data_fontawesome_icon_name' => 'Window restore'],
		'windows' => ['no_data_fontawesome_icon_unicode' => '\f17a', 'no_data_fontawesome_icon_name' => 'Windows'],
		'wordpress' => ['no_data_fontawesome_icon_unicode' => '\f19a', 'no_data_fontawesome_icon_name' => 'Wordpress'],
		'wpbeginner' => ['no_data_fontawesome_icon_unicode' => '\f297', 'no_data_fontawesome_icon_name' => 'Wpbeginner'],
		'wpexplorer' => ['no_data_fontawesome_icon_unicode' => '\f2de', 'no_data_fontawesome_icon_name' => 'Wpexplorer'],
		'wpforms' => ['no_data_fontawesome_icon_unicode' => '\f298', 'no_data_fontawesome_icon_name' => 'Wpforms'],
		'wrench' => ['no_data_fontawesome_icon_unicode' => '\f0ad', 'no_data_fontawesome_icon_name' => 'Wrench'],
		'xing' => ['no_data_fontawesome_icon_unicode' => '\f168', 'no_data_fontawesome_icon_name' => 'Xing'],
		'xing-square' => ['no_data_fontawesome_icon_unicode' => '\f169', 'no_data_fontawesome_icon_name' => 'Xing square'],
		'y-combinator' => ['no_data_fontawesome_icon_unicode' => '\f23b', 'no_data_fontawesome_icon_name' => 'Y combinator'],
		'yahoo' => ['no_data_fontawesome_icon_unicode' => '\f19e', 'no_data_fontawesome_icon_name' => 'Yahoo'],
		'yelp' => ['no_data_fontawesome_icon_unicode' => '\f1e9', 'no_data_fontawesome_icon_name' => 'Yelp'],
		'yoast' => ['no_data_fontawesome_icon_unicode' => '\f2b1', 'no_data_fontawesome_icon_name' => 'Yoast'],
		'youtube' => ['no_data_fontawesome_icon_unicode' => '\f167', 'no_data_fontawesome_icon_name' => 'Youtube'],
		'youtube-play' => ['no_data_fontawesome_icon_unicode' => '\f16a', 'no_data_fontawesome_icon_name' => 'Youtube play'],
		'youtube-square' => ['no_data_fontawesome_icon_unicode' => '\f166', 'no_data_fontawesome_icon_name' => 'Youtube square'],
	];
}