[module]
module.name = "Numbers\Frontend\Media\CDN"
module.code = "SM-Frontend-CDN"
module.title = "Frontend Media CDN"
module.version = "1.0.3"

[help]
; S/M-Frontend-CDN
;	- Bootstrap
;	- FontAwesome
;	- jQuery
;	- SemanticUI
;	- Tailwind