<?php

/*
 * This file is part of Numbers Framework.
 *
 * (c) Volodymyr Volynets <volodymyr.volynets@gmail.com>
 *
 * This source file is subject to the Apache 2.0 license that is bundled
 * with this source code in the file LICENSE.
 */

namespace Numbers\Frontend\HTML\Emojis\Model;

use Object\Data;

class Emojis extends Data
{
    public $column_key = 'code';
    public $column_prefix = '';
    public $columns = [
        'code' => ['name' => 'Code', 'type' => 'text'],
        'name' => ['name' => 'Name', 'type' => 'text'],
        'category' => ['name' => 'Category', 'type' => 'text'],
        'emoji' => ['name' => 'Emoji', 'type' => 'text'],
    ];
    public $options_map = [
        'name' => 'name',
        'category' => 'category',
    ];
    public $orderby = [
        'name' => SORT_ASC
    ];
    public const selectOptions = '\Numbers\Frontend\HTML\Emojis\Model\Emojis::options';
    public $options_skip_i18n = true;
    public $data = [
        'U+1F601' => ['name' => 'GRINNING FACE WITH SMILING EYES','category' => 'Emoticons','emoji' => '😁'],
        'U+1F602' => ['name' => 'FACE WITH TEARS OF JOY','category' => 'Emoticons','emoji' => '😂'],
        'U+1F603' => ['name' => 'SMILING FACE WITH OPEN MOUTH','category' => 'Emoticons','emoji' => '😃'],
        'U+1F604' => ['name' => 'SMILING FACE WITH OPEN MOUTH AND SMILING EYES','category' => 'Emoticons','emoji' => '😄'],
        'U+1F605' => ['name' => 'SMILING FACE WITH OPEN MOUTH AND COLD SWEAT','category' => 'Emoticons','emoji' => '😅'],
        'U+1F606' => ['name' => 'SMILING FACE WITH OPEN MOUTH AND TIGHTLY-CLOSED EYES','category' => 'Emoticons','emoji' => '😆'],
        'U+1F609' => ['name' => 'WINKING FACE','category' => 'Emoticons','emoji' => '😉'],
        'U+1F60A' => ['name' => 'SMILING FACE WITH SMILING EYES','category' => 'Emoticons','emoji' => '😊'],
        'U+1F60B' => ['name' => 'FACE SAVOURING DELICIOUS FOOD','category' => 'Emoticons','emoji' => '😋'],
        'U+1F60C' => ['name' => 'RELIEVED FACE','category' => 'Emoticons','emoji' => '😌'],
        'U+1F60D' => ['name' => 'SMILING FACE WITH HEART-SHAPED EYES','category' => 'Emoticons','emoji' => '😍'],
        'U+1F60F' => ['name' => 'SMIRKING FACE','category' => 'Emoticons','emoji' => '😏'],
        'U+1F612' => ['name' => 'UNAMUSED FACE','category' => 'Emoticons','emoji' => '😒'],
        'U+1F613' => ['name' => 'FACE WITH COLD SWEAT','category' => 'Emoticons','emoji' => '😓'],
        'U+1F614' => ['name' => 'PENSIVE FACE','category' => 'Emoticons','emoji' => '😔'],
        'U+1F616' => ['name' => 'CONFOUNDED FACE','category' => 'Emoticons','emoji' => '😖'],
        'U+1F618' => ['name' => 'FACE THROWING A KISS','category' => 'Emoticons','emoji' => '😘'],
        'U+1F61A' => ['name' => 'KISSING FACE WITH CLOSED EYES','category' => 'Emoticons','emoji' => '😚'],
        'U+1F61C' => ['name' => 'FACE WITH STUCK-OUT TONGUE AND WINKING EYE','category' => 'Emoticons','emoji' => '😜'],
        'U+1F61D' => ['name' => 'FACE WITH STUCK-OUT TONGUE AND TIGHTLY-CLOSED EYES','category' => 'Emoticons','emoji' => '😝'],
        'U+1F61E' => ['name' => 'DISAPPOINTED FACE','category' => 'Emoticons','emoji' => '😞'],
        'U+1F620' => ['name' => 'ANGRY FACE','category' => 'Emoticons','emoji' => '😠'],
        'U+1F621' => ['name' => 'POUTING FACE','category' => 'Emoticons','emoji' => '😡'],
        'U+1F622' => ['name' => 'CRYING FACE','category' => 'Emoticons','emoji' => '😢'],
        'U+1F623' => ['name' => 'PERSEVERING FACE','category' => 'Emoticons','emoji' => '😣'],
        'U+1F624' => ['name' => 'FACE WITH LOOK OF TRIUMPH','category' => 'Emoticons','emoji' => '😤'],
        'U+1F625' => ['name' => 'DISAPPOINTED BUT RELIEVED FACE','category' => 'Emoticons','emoji' => '😥'],
        'U+1F628' => ['name' => 'FEARFUL FACE','category' => 'Emoticons','emoji' => '😨'],
        'U+1F629' => ['name' => 'WEARY FACE','category' => 'Emoticons','emoji' => '😩'],
        'U+1F62A' => ['name' => 'SLEEPY FACE','category' => 'Emoticons','emoji' => '😪'],
        'U+1F62B' => ['name' => 'TIRED FACE','category' => 'Emoticons','emoji' => '😫'],
        'U+1F62D' => ['name' => 'LOUDLY CRYING FACE','category' => 'Emoticons','emoji' => '😭'],
        'U+1F630' => ['name' => 'FACE WITH OPEN MOUTH AND COLD SWEAT','category' => 'Emoticons','emoji' => '😰'],
        'U+1F631' => ['name' => 'FACE SCREAMING IN FEAR','category' => 'Emoticons','emoji' => '😱'],
        'U+1F632' => ['name' => 'ASTONISHED FACE','category' => 'Emoticons','emoji' => '😲'],
        'U+1F633' => ['name' => 'FLUSHED FACE','category' => 'Emoticons','emoji' => '😳'],
        'U+1F635' => ['name' => 'DIZZY FACE','category' => 'Emoticons','emoji' => '😵'],
        'U+1F637' => ['name' => 'FACE WITH MEDICAL MASK','category' => 'Emoticons','emoji' => '😷'],
        'U+1F638' => ['name' => 'GRINNING CAT FACE WITH SMILING EYES','category' => 'Emoticons','emoji' => '😸'],
        'U+1F639' => ['name' => 'CAT FACE WITH TEARS OF JOY','category' => 'Emoticons','emoji' => '😹'],
        'U+1F63A' => ['name' => 'SMILING CAT FACE WITH OPEN MOUTH','category' => 'Emoticons','emoji' => '😺'],
        'U+1F63B' => ['name' => 'SMILING CAT FACE WITH HEART-SHAPED EYES','category' => 'Emoticons','emoji' => '😻'],
        'U+1F63C' => ['name' => 'CAT FACE WITH WRY SMILE','category' => 'Emoticons','emoji' => '😼'],
        'U+1F63D' => ['name' => 'KISSING CAT FACE WITH CLOSED EYES','category' => 'Emoticons','emoji' => '😽'],
        'U+1F63E' => ['name' => 'POUTING CAT FACE','category' => 'Emoticons','emoji' => '😾'],
        'U+1F63F' => ['name' => 'CRYING CAT FACE','category' => 'Emoticons','emoji' => '😿'],
        'U+1F640' => ['name' => 'WEARY CAT FACE','category' => 'Emoticons','emoji' => '🙀'],
        'U+1F645' => ['name' => 'FACE WITH NO GOOD GESTURE','category' => 'Emoticons','emoji' => '🙅'],
        'U+1F646' => ['name' => 'FACE WITH OK GESTURE','category' => 'Emoticons','emoji' => '🙆'],
        'U+1F647' => ['name' => 'PERSON BOWING DEEPLY','category' => 'Emoticons','emoji' => '🙇'],
        'U+1F648' => ['name' => 'SEE-NO-EVIL MONKEY','category' => 'Emoticons','emoji' => '🙈'],
        'U+1F649' => ['name' => 'HEAR-NO-EVIL MONKEY','category' => 'Emoticons','emoji' => '🙉'],
        'U+1F64A' => ['name' => 'SPEAK-NO-EVIL MONKEY','category' => 'Emoticons','emoji' => '🙊'],
        'U+1F64B' => ['name' => 'HAPPY PERSON RAISING ONE HAND','category' => 'Emoticons','emoji' => '🙋'],
        'U+1F64C' => ['name' => 'PERSON RAISING BOTH HANDS IN CELEBRATION','category' => 'Emoticons','emoji' => '🙌'],
        'U+1F64D' => ['name' => 'PERSON FROWNING','category' => 'Emoticons','emoji' => '🙍'],
        'U+1F64E' => ['name' => 'PERSON WITH POUTING FACE','category' => 'Emoticons','emoji' => '🙎'],
        'U+1F64F' => ['name' => 'PERSON WITH FOLDED HANDS','category' => 'Emoticons','emoji' => '🙏'],
        'U+2702' => ['name' => 'BLACK SCISSORS','category' => 'Dingbats','emoji' => '✂'],
        'U+2705' => ['name' => 'WHITE HEAVY CHECK MARK','category' => 'Dingbats','emoji' => '✅'],
        'U+2708' => ['name' => 'AIRPLANE','category' => 'Dingbats','emoji' => '✈'],
        'U+2709' => ['name' => 'ENVELOPE','category' => 'Dingbats','emoji' => '✉'],
        'U+270A' => ['name' => 'RAISED FIST','category' => 'Dingbats','emoji' => '✊'],
        'U+270B' => ['name' => 'RAISED HAND','category' => 'Dingbats','emoji' => '✋'],
        'U+270C' => ['name' => 'VICTORY HAND','category' => 'Dingbats','emoji' => '✌'],
        'U+270F' => ['name' => 'PENCIL','category' => 'Dingbats','emoji' => '✏'],
        'U+2712' => ['name' => 'BLACK NIB','category' => 'Dingbats','emoji' => '✒'],
        'U+2714' => ['name' => 'HEAVY CHECK MARK','category' => 'Dingbats','emoji' => '✔'],
        'U+2716' => ['name' => 'HEAVY MULTIPLICATION X','category' => 'Dingbats','emoji' => '✖'],
        'U+2728' => ['name' => 'SPARKLES','category' => 'Dingbats','emoji' => '✨'],
        'U+2733' => ['name' => 'EIGHT SPOKED ASTERISK','category' => 'Dingbats','emoji' => '✳'],
        'U+2734' => ['name' => 'EIGHT POINTED BLACK STAR','category' => 'Dingbats','emoji' => '✴'],
        'U+2744' => ['name' => 'SNOWFLAKE','category' => 'Dingbats','emoji' => '❄'],
        'U+2747' => ['name' => 'SPARKLE','category' => 'Dingbats','emoji' => '❇'],
        'U+274C' => ['name' => 'CROSS MARK','category' => 'Dingbats','emoji' => '❌'],
        'U+274E' => ['name' => 'NEGATIVE SQUARED CROSS MARK','category' => 'Dingbats','emoji' => '❎'],
        'U+2753' => ['name' => 'BLACK QUESTION MARK ORNAMENT','category' => 'Dingbats','emoji' => '❓'],
        'U+2754' => ['name' => 'WHITE QUESTION MARK ORNAMENT','category' => 'Dingbats','emoji' => '❔'],
        'U+2755' => ['name' => 'WHITE EXCLAMATION MARK ORNAMENT','category' => 'Dingbats','emoji' => '❕'],
        'U+2757' => ['name' => 'HEAVY EXCLAMATION MARK SYMBOL','category' => 'Dingbats','emoji' => '❗'],
        'U+2764' => ['name' => 'HEAVY BLACK HEART','category' => 'Dingbats','emoji' => '❤'],
        'U+2795' => ['name' => 'HEAVY PLUS SIGN','category' => 'Dingbats','emoji' => '➕'],
        'U+2796' => ['name' => 'HEAVY MINUS SIGN','category' => 'Dingbats','emoji' => '➖'],
        'U+2797' => ['name' => 'HEAVY DIVISION SIGN','category' => 'Dingbats','emoji' => '➗'],
        'U+27A1' => ['name' => 'BLACK RIGHTWARDS ARROW','category' => 'Dingbats','emoji' => '➡'],
        'U+27B0' => ['name' => 'CURLY LOOP','category' => 'Dingbats','emoji' => '➰'],
        'U+1F680' => ['name' => 'ROCKET','category' => 'Transport and map symbols','emoji' => '🚀'],
        'U+1F683' => ['name' => 'RAILWAY CAR','category' => 'Transport and map symbols','emoji' => '🚃'],
        'U+1F684' => ['name' => 'HIGH-SPEED TRAIN','category' => 'Transport and map symbols','emoji' => '🚄'],
        'U+1F685' => ['name' => 'HIGH-SPEED TRAIN WITH BULLET NOSE','category' => 'Transport and map symbols','emoji' => '🚅'],
        'U+1F687' => ['name' => 'METRO','category' => 'Transport and map symbols','emoji' => '🚇'],
        'U+1F689' => ['name' => 'STATION','category' => 'Transport and map symbols','emoji' => '🚉'],
        'U+1F68C' => ['name' => 'BUS','category' => 'Transport and map symbols','emoji' => '🚌'],
        'U+1F68F' => ['name' => 'BUS STOP','category' => 'Transport and map symbols','emoji' => '🚏'],
        'U+1F691' => ['name' => 'AMBULANCE','category' => 'Transport and map symbols','emoji' => '🚑'],
        'U+1F692' => ['name' => 'FIRE ENGINE','category' => 'Transport and map symbols','emoji' => '🚒'],
        'U+1F693' => ['name' => 'POLICE CAR','category' => 'Transport and map symbols','emoji' => '🚓'],
        'U+1F695' => ['name' => 'TAXI','category' => 'Transport and map symbols','emoji' => '🚕'],
        'U+1F697' => ['name' => 'AUTOMOBILE','category' => 'Transport and map symbols','emoji' => '🚗'],
        'U+1F699' => ['name' => 'RECREATIONAL VEHICLE','category' => 'Transport and map symbols','emoji' => '🚙'],
        'U+1F69A' => ['name' => 'DELIVERY TRUCK','category' => 'Transport and map symbols','emoji' => '🚚'],
        'U+1F6A2' => ['name' => 'SHIP','category' => 'Transport and map symbols','emoji' => '🚢'],
        'U+1F6A4' => ['name' => 'SPEEDBOAT','category' => 'Transport and map symbols','emoji' => '🚤'],
        'U+1F6A5' => ['name' => 'HORIZONTAL TRAFFIC LIGHT','category' => 'Transport and map symbols','emoji' => '🚥'],
        'U+1F6A7' => ['name' => 'CONSTRUCTION SIGN','category' => 'Transport and map symbols','emoji' => '🚧'],
        'U+1F6A8' => ['name' => 'POLICE CARS REVOLVING LIGHT','category' => 'Transport and map symbols','emoji' => '🚨'],
        'U+1F6A9' => ['name' => 'TRIANGULAR FLAG ON POST','category' => 'Transport and map symbols','emoji' => '🚩'],
        'U+1F6AA' => ['name' => 'DOOR','category' => 'Transport and map symbols','emoji' => '🚪'],
        'U+1F6AB' => ['name' => 'NO ENTRY SIGN','category' => 'Transport and map symbols','emoji' => '🚫'],
        'U+1F6AC' => ['name' => 'SMOKING SYMBOL','category' => 'Transport and map symbols','emoji' => '🚬'],
        'U+1F6AD' => ['name' => 'NO SMOKING SYMBOL','category' => 'Transport and map symbols','emoji' => '🚭'],
        'U+1F6B2' => ['name' => 'BICYCLE','category' => 'Transport and map symbols','emoji' => '🚲'],
        'U+1F6B6' => ['name' => 'PEDESTRIAN','category' => 'Transport and map symbols','emoji' => '🚶'],
        'U+1F6B9' => ['name' => 'MENS SYMBOL','category' => 'Transport and map symbols','emoji' => '🚹'],
        'U+1F6BA' => ['name' => 'WOMENS SYMBOL','category' => 'Transport and map symbols','emoji' => '🚺'],
        'U+1F6BB' => ['name' => 'RESTROOM','category' => 'Transport and map symbols','emoji' => '🚻'],
        'U+1F6BC' => ['name' => 'BABY SYMBOL','category' => 'Transport and map symbols','emoji' => '🚼'],
        'U+1F6BD' => ['name' => 'TOILET','category' => 'Transport and map symbols','emoji' => '🚽'],
        'U+1F6BE' => ['name' => 'WATER CLOSET','category' => 'Transport and map symbols','emoji' => '🚾'],
        'U+1F6C0' => ['name' => 'BATH','category' => 'Transport and map symbols','emoji' => '🛀'],
        'U+24C2' => ['name' => 'CIRCLED LATIN CAPITAL LETTER M','category' => 'Enclosed characters','emoji' => 'Ⓜ'],
        'U+1F170' => ['name' => 'NEGATIVE SQUARED LATIN CAPITAL LETTER A','category' => 'Enclosed characters','emoji' => '🅰'],
        'U+1F171' => ['name' => 'NEGATIVE SQUARED LATIN CAPITAL LETTER B','category' => 'Enclosed characters','emoji' => '🅱'],
        'U+1F17E' => ['name' => 'NEGATIVE SQUARED LATIN CAPITAL LETTER O','category' => 'Enclosed characters','emoji' => '🅾'],
        'U+1F17F' => ['name' => 'NEGATIVE SQUARED LATIN CAPITAL LETTER P','category' => 'Enclosed characters','emoji' => '🅿'],
        'U+1F18E' => ['name' => 'NEGATIVE SQUARED AB','category' => 'Enclosed characters','emoji' => '🆎'],
        'U+1F191' => ['name' => 'SQUARED CL','category' => 'Enclosed characters','emoji' => '🆑'],
        'U+1F192' => ['name' => 'SQUARED COOL','category' => 'Enclosed characters','emoji' => '🆒'],
        'U+1F193' => ['name' => 'SQUARED FREE','category' => 'Enclosed characters','emoji' => '🆓'],
        'U+1F194' => ['name' => 'SQUARED ID','category' => 'Enclosed characters','emoji' => '🆔'],
        'U+1F195' => ['name' => 'SQUARED NEW','category' => 'Enclosed characters','emoji' => '🆕'],
        'U+1F196' => ['name' => 'SQUARED NG','category' => 'Enclosed characters','emoji' => '🆖'],
        'U+1F197' => ['name' => 'SQUARED OK','category' => 'Enclosed characters','emoji' => '🆗'],
        'U+1F198' => ['name' => 'SQUARED SOS','category' => 'Enclosed characters','emoji' => '🆘'],
        'U+1F199' => ['name' => 'SQUARED UP WITH EXCLAMATION MARK','category' => 'Enclosed characters','emoji' => '🆙'],
        'U+1F19A' => ['name' => 'SQUARED VS','category' => 'Enclosed characters','emoji' => '🆚'],
        'U+1F1E9' => ['name' => 'REGIONAL INDICATOR SYMBOL LETTER D','category' => 'Enclosed characters','emoji' => '🇩🇪'],
        'U+1F1EA' => ['name' => 'REGIONAL INDICATOR SYMBOL LETTER E','category' => 'Enclosed characters','emoji' => '🇪🇸'],
        'U+1F1EC' => ['name' => 'REGIONAL INDICATOR SYMBOL LETTER G','category' => 'Enclosed characters','emoji' => '🇬🇧'],
        'U+1F1E7' => ['name' => 'REGIONAL INDICATOR SYMBOL LETTER B','category' => 'Enclosed characters','emoji' => '🇬🇧'],
        'U+1F1E8' => ['name' => 'REGIONAL INDICATOR SYMBOL LETTER C','category' => 'Enclosed characters','emoji' => '🇨🇳'],
        'U+1F1F3' => ['name' => 'REGIONAL INDICATOR SYMBOL LETTER N','category' => 'Enclosed characters','emoji' => '🇨🇳'],
        'U+1F1EF' => ['name' => 'REGIONAL INDICATOR SYMBOL LETTER J','category' => 'Enclosed characters','emoji' => '🇯🇵'],
        'U+1F1F5' => ['name' => 'REGIONAL INDICATOR SYMBOL LETTER P','category' => 'Enclosed characters','emoji' => '🇯🇵'],
        'U+1F1EB' => ['name' => 'REGIONAL INDICATOR SYMBOL LETTER F','category' => 'Enclosed characters','emoji' => '🇫🇷'],
        'U+1F1F7' => ['name' => 'REGIONAL INDICATOR SYMBOL LETTER R','category' => 'Enclosed characters','emoji' => '🇷🇺'],
        'U+1F1F0' => ['name' => 'REGIONAL INDICATOR SYMBOL LETTER K','category' => 'Enclosed characters','emoji' => '🇰🇷'],
        'U+1F1F8' => ['name' => 'REGIONAL INDICATOR SYMBOL LETTER S','category' => 'Enclosed characters','emoji' => '🇺🇸'],
        'U+1F1EE' => ['name' => 'REGIONAL INDICATOR SYMBOL LETTER I','category' => 'Enclosed characters','emoji' => '🇮🇹'],
        'U+1F1F9' => ['name' => 'REGIONAL INDICATOR SYMBOL LETTER T','category' => 'Enclosed characters','emoji' => '🇮🇹'],
        'U+1F1FA' => ['name' => 'REGIONAL INDICATOR SYMBOL LETTER U','category' => 'Enclosed characters','emoji' => '🇺🇸'],
        'U+1F201' => ['name' => 'SQUARED KATAKANA KOKO','category' => 'Enclosed characters','emoji' => '🈁'],
        'U+1F202' => ['name' => 'SQUARED KATAKANA SA','category' => 'Enclosed characters','emoji' => '🈂'],
        'U+1F21A' => ['name' => 'SQUARED CJK UNIFIED IDEOGRAPH-7121','category' => 'Enclosed characters','emoji' => '🈚'],
        'U+1F22F' => ['name' => 'SQUARED CJK UNIFIED IDEOGRAPH-6307','category' => 'Enclosed characters','emoji' => '🈯'],
        'U+1F232' => ['name' => 'SQUARED CJK UNIFIED IDEOGRAPH-7981','category' => 'Enclosed characters','emoji' => '🈲'],
        'U+1F233' => ['name' => 'SQUARED CJK UNIFIED IDEOGRAPH-7A7A','category' => 'Enclosed characters','emoji' => '🈳'],
        'U+1F234' => ['name' => 'SQUARED CJK UNIFIED IDEOGRAPH-5408','category' => 'Enclosed characters','emoji' => '🈴'],
        'U+1F235' => ['name' => 'SQUARED CJK UNIFIED IDEOGRAPH-6E80','category' => 'Enclosed characters','emoji' => '🈵'],
        'U+1F236' => ['name' => 'SQUARED CJK UNIFIED IDEOGRAPH-6709','category' => 'Enclosed characters','emoji' => '🈶'],
        'U+1F237' => ['name' => 'SQUARED CJK UNIFIED IDEOGRAPH-6708','category' => 'Enclosed characters','emoji' => '🈷'],
        'U+1F238' => ['name' => 'SQUARED CJK UNIFIED IDEOGRAPH-7533','category' => 'Enclosed characters','emoji' => '🈸'],
        'U+1F239' => ['name' => 'SQUARED CJK UNIFIED IDEOGRAPH-5272','category' => 'Enclosed characters','emoji' => '🈹'],
        'U+1F23A' => ['name' => 'SQUARED CJK UNIFIED IDEOGRAPH-55B6','category' => 'Enclosed characters','emoji' => '🈺'],
        'U+1F250' => ['name' => 'CIRCLED IDEOGRAPH ADVANTAGE','category' => 'Enclosed characters','emoji' => '🉐'],
        'U+1F251' => ['name' => 'CIRCLED IDEOGRAPH ACCEPT','category' => 'Enclosed characters','emoji' => '🉑'],
        'U+00A9' => ['name' => 'COPYRIGHT SIGN','category' => 'Uncategorized','emoji' => '©'],
        'U+00AE' => ['name' => 'REGISTERED SIGN','category' => 'Uncategorized','emoji' => '®'],
        'U+203C' => ['name' => 'DOUBLE EXCLAMATION MARK','category' => 'Uncategorized','emoji' => '‼'],
        'U+2049' => ['name' => 'EXCLAMATION QUESTION MARK','category' => 'Uncategorized','emoji' => '⁉'],
        'U+0023' => ['name' => 'NUMBER SIGN','category' => 'Uncategorized','emoji' => '#⃣'],
        'U+20E3' => ['name' => 'COMBINING ENCLOSING KEYCAP','category' => 'Uncategorized','emoji' => '9⃣'],
        'U+0030' => ['name' => 'DIGIT ZERO','category' => 'Uncategorized','emoji' => '0⃣'],
        'U+0031' => ['name' => 'DIGIT ONE','category' => 'Uncategorized','emoji' => '1⃣'],
        'U+0032' => ['name' => 'DIGIT TWO','category' => 'Uncategorized','emoji' => '2⃣'],
        'U+0033' => ['name' => 'DIGIT THREE','category' => 'Uncategorized','emoji' => '3⃣'],
        'U+0034' => ['name' => 'DIGIT FOUR','category' => 'Uncategorized','emoji' => '4⃣'],
        'U+0035' => ['name' => 'DIGIT FIVE','category' => 'Uncategorized','emoji' => '5⃣'],
        'U+0036' => ['name' => 'DIGIT SIX','category' => 'Uncategorized','emoji' => '6⃣'],
        'U+0037' => ['name' => 'DIGIT SEVEN','category' => 'Uncategorized','emoji' => '7⃣'],
        'U+0038' => ['name' => 'DIGIT EIGHT','category' => 'Uncategorized','emoji' => '8⃣'],
        'U+0039' => ['name' => 'DIGIT NINE','category' => 'Uncategorized','emoji' => '9⃣'],
        'U+2122' => ['name' => 'TRADE MARK SIGN','category' => 'Uncategorized','emoji' => '™'],
        'U+2139' => ['name' => 'INFORMATION SOURCE','category' => 'Uncategorized','emoji' => 'ℹ'],
        'U+2194' => ['name' => 'LEFT RIGHT ARROW','category' => 'Uncategorized','emoji' => '↔'],
        'U+2195' => ['name' => 'UP DOWN ARROW','category' => 'Uncategorized','emoji' => '↕'],
        'U+2196' => ['name' => 'NORTH WEST ARROW','category' => 'Uncategorized','emoji' => '↖'],
        'U+2197' => ['name' => 'NORTH EAST ARROW','category' => 'Uncategorized','emoji' => '↗'],
        'U+2198' => ['name' => 'SOUTH EAST ARROW','category' => 'Uncategorized','emoji' => '↘'],
        'U+2199' => ['name' => 'SOUTH WEST ARROW','category' => 'Uncategorized','emoji' => '↙'],
        'U+21A9' => ['name' => 'LEFTWARDS ARROW WITH HOOK','category' => 'Uncategorized','emoji' => '↩'],
        'U+21AA' => ['name' => 'RIGHTWARDS ARROW WITH HOOK','category' => 'Uncategorized','emoji' => '↪'],
        'U+231A' => ['name' => 'WATCH','category' => 'Uncategorized','emoji' => '⌚'],
        'U+231B' => ['name' => 'HOURGLASS','category' => 'Uncategorized','emoji' => '⌛'],
        'U+23E9' => ['name' => 'BLACK RIGHT-POINTING DOUBLE TRIANGLE','category' => 'Uncategorized','emoji' => '⏩'],
        'U+23EA' => ['name' => 'BLACK LEFT-POINTING DOUBLE TRIANGLE','category' => 'Uncategorized','emoji' => '⏪'],
        'U+23EB' => ['name' => 'BLACK UP-POINTING DOUBLE TRIANGLE','category' => 'Uncategorized','emoji' => '⏫'],
        'U+23EC' => ['name' => 'BLACK DOWN-POINTING DOUBLE TRIANGLE','category' => 'Uncategorized','emoji' => '⏬'],
        'U+23F0' => ['name' => 'ALARM CLOCK','category' => 'Uncategorized','emoji' => '⏰'],
        'U+23F3' => ['name' => 'HOURGLASS WITH FLOWING SAND','category' => 'Uncategorized','emoji' => '⏳'],
        'U+25AA' => ['name' => 'BLACK SMALL SQUARE','category' => 'Uncategorized','emoji' => '▪'],
        'U+25AB' => ['name' => 'WHITE SMALL SQUARE','category' => 'Uncategorized','emoji' => '▫'],
        'U+25B6' => ['name' => 'BLACK RIGHT-POINTING TRIANGLE','category' => 'Uncategorized','emoji' => '▶'],
        'U+25C0' => ['name' => 'BLACK LEFT-POINTING TRIANGLE','category' => 'Uncategorized','emoji' => '◀'],
        'U+25FB' => ['name' => 'WHITE MEDIUM SQUARE','category' => 'Uncategorized','emoji' => '◻'],
        'U+25FC' => ['name' => 'BLACK MEDIUM SQUARE','category' => 'Uncategorized','emoji' => '◼'],
        'U+25FD' => ['name' => 'WHITE MEDIUM SMALL SQUARE','category' => 'Uncategorized','emoji' => '◽'],
        'U+25FE' => ['name' => 'BLACK MEDIUM SMALL SQUARE','category' => 'Uncategorized','emoji' => '◾'],
        'U+2600' => ['name' => 'BLACK SUN WITH RAYS','category' => 'Uncategorized','emoji' => '☀'],
        'U+2601' => ['name' => 'CLOUD','category' => 'Uncategorized','emoji' => '☁'],
        'U+260E' => ['name' => 'BLACK TELEPHONE','category' => 'Uncategorized','emoji' => '☎'],
        'U+2611' => ['name' => 'BALLOT BOX WITH CHECK','category' => 'Uncategorized','emoji' => '☑'],
        'U+2614' => ['name' => 'UMBRELLA WITH RAIN DROPS','category' => 'Uncategorized','emoji' => '☔'],
        'U+2615' => ['name' => 'HOT BEVERAGE','category' => 'Uncategorized','emoji' => '☕'],
        'U+261D' => ['name' => 'WHITE UP POINTING INDEX','category' => 'Uncategorized','emoji' => '☝'],
        'U+263A' => ['name' => 'WHITE SMILING FACE','category' => 'Uncategorized','emoji' => '☺'],
        'U+2648' => ['name' => 'ARIES','category' => 'Uncategorized','emoji' => '♈'],
        'U+2649' => ['name' => 'TAURUS','category' => 'Uncategorized','emoji' => '♉'],
        'U+264A' => ['name' => 'GEMINI','category' => 'Uncategorized','emoji' => '♊'],
        'U+264B' => ['name' => 'CANCER','category' => 'Uncategorized','emoji' => '♋'],
        'U+264C' => ['name' => 'LEO','category' => 'Uncategorized','emoji' => '♌'],
        'U+264D' => ['name' => 'VIRGO','category' => 'Uncategorized','emoji' => '♍'],
        'U+264E' => ['name' => 'LIBRA','category' => 'Uncategorized','emoji' => '♎'],
        'U+264F' => ['name' => 'SCORPIUS','category' => 'Uncategorized','emoji' => '♏'],
        'U+2650' => ['name' => 'SAGITTARIUS','category' => 'Uncategorized','emoji' => '♐'],
        'U+2651' => ['name' => 'CAPRICORN','category' => 'Uncategorized','emoji' => '♑'],
        'U+2652' => ['name' => 'AQUARIUS','category' => 'Uncategorized','emoji' => '♒'],
        'U+2653' => ['name' => 'PISCES','category' => 'Uncategorized','emoji' => '♓'],
        'U+2660' => ['name' => 'BLACK SPADE SUIT','category' => 'Uncategorized','emoji' => '♠'],
        'U+2663' => ['name' => 'BLACK CLUB SUIT','category' => 'Uncategorized','emoji' => '♣'],
        'U+2665' => ['name' => 'BLACK HEART SUIT','category' => 'Uncategorized','emoji' => '♥'],
        'U+2666' => ['name' => 'BLACK DIAMOND SUIT','category' => 'Uncategorized','emoji' => '♦'],
        'U+2668' => ['name' => 'HOT SPRINGS','category' => 'Uncategorized','emoji' => '♨'],
        'U+267B' => ['name' => 'BLACK UNIVERSAL RECYCLING SYMBOL','category' => 'Uncategorized','emoji' => '♻'],
        'U+267F' => ['name' => 'WHEELCHAIR SYMBOL','category' => 'Uncategorized','emoji' => '♿'],
        'U+2693' => ['name' => 'ANCHOR','category' => 'Uncategorized','emoji' => '⚓'],
        'U+26A0' => ['name' => 'WARNING SIGN','category' => 'Uncategorized','emoji' => '⚠'],
        'U+26A1' => ['name' => 'HIGH VOLTAGE SIGN','category' => 'Uncategorized','emoji' => '⚡'],
        'U+26AA' => ['name' => 'MEDIUM WHITE CIRCLE','category' => 'Uncategorized','emoji' => '⚪'],
        'U+26AB' => ['name' => 'MEDIUM BLACK CIRCLE','category' => 'Uncategorized','emoji' => '⚫'],
        'U+26BD' => ['name' => 'SOCCER BALL','category' => 'Uncategorized','emoji' => '⚽'],
        'U+26BE' => ['name' => 'BASEBALL','category' => 'Uncategorized','emoji' => '⚾'],
        'U+26C4' => ['name' => 'SNOWMAN WITHOUT SNOW','category' => 'Uncategorized','emoji' => '⛄'],
        'U+26C5' => ['name' => 'SUN BEHIND CLOUD','category' => 'Uncategorized','emoji' => '⛅'],
        'U+26CE' => ['name' => 'OPHIUCHUS','category' => 'Uncategorized','emoji' => '⛎'],
        'U+26D4' => ['name' => 'NO ENTRY','category' => 'Uncategorized','emoji' => '⛔'],
        'U+26EA' => ['name' => 'CHURCH','category' => 'Uncategorized','emoji' => '⛪'],
        'U+26F2' => ['name' => 'FOUNTAIN','category' => 'Uncategorized','emoji' => '⛲'],
        'U+26F3' => ['name' => 'FLAG IN HOLE','category' => 'Uncategorized','emoji' => '⛳'],
        'U+26F5' => ['name' => 'SAILBOAT','category' => 'Uncategorized','emoji' => '⛵'],
        'U+26FA' => ['name' => 'TENT','category' => 'Uncategorized','emoji' => '⛺'],
        'U+26FD' => ['name' => 'FUEL PUMP','category' => 'Uncategorized','emoji' => '⛽'],
        'U+2934' => ['name' => 'ARROW POINTING RIGHTWARDS THEN CURVING UPWARDS','category' => 'Uncategorized','emoji' => '⤴'],
        'U+2935' => ['name' => 'ARROW POINTING RIGHTWARDS THEN CURVING DOWNWARDS','category' => 'Uncategorized','emoji' => '⤵'],
        'U+2B05' => ['name' => 'LEFTWARDS BLACK ARROW','category' => 'Uncategorized','emoji' => '⬅'],
        'U+2B06' => ['name' => 'UPWARDS BLACK ARROW','category' => 'Uncategorized','emoji' => '⬆'],
        'U+2B07' => ['name' => 'DOWNWARDS BLACK ARROW','category' => 'Uncategorized','emoji' => '⬇'],
        'U+2B1B' => ['name' => 'BLACK LARGE SQUARE','category' => 'Uncategorized','emoji' => '⬛'],
        'U+2B1C' => ['name' => 'WHITE LARGE SQUARE','category' => 'Uncategorized','emoji' => '⬜'],
        'U+2B50' => ['name' => 'WHITE MEDIUM STAR','category' => 'Uncategorized','emoji' => '⭐'],
        'U+2B55' => ['name' => 'HEAVY LARGE CIRCLE','category' => 'Uncategorized','emoji' => '⭕'],
        'U+3030' => ['name' => 'WAVY DASH','category' => 'Uncategorized','emoji' => '〰'],
        'U+303D' => ['name' => 'PART ALTERNATION MARK','category' => 'Uncategorized','emoji' => '〽'],
        'U+3297' => ['name' => 'CIRCLED IDEOGRAPH CONGRATULATION','category' => 'Uncategorized','emoji' => '㊗'],
        'U+3299' => ['name' => 'CIRCLED IDEOGRAPH SECRET','category' => 'Uncategorized','emoji' => '㊙'],
        'U+1F004' => ['name' => 'MAHJONG TILE RED DRAGON','category' => 'Uncategorized','emoji' => '🀄'],
        'U+1F0CF' => ['name' => 'PLAYING CARD BLACK JOKER','category' => 'Uncategorized','emoji' => '🃏'],
        'U+1F300' => ['name' => 'CYCLONE','category' => 'Uncategorized','emoji' => '🌀'],
        'U+1F301' => ['name' => 'FOGGY','category' => 'Uncategorized','emoji' => '🌁'],
        'U+1F302' => ['name' => 'CLOSED UMBRELLA','category' => 'Uncategorized','emoji' => '🌂'],
        'U+1F303' => ['name' => 'NIGHT WITH STARS','category' => 'Uncategorized','emoji' => '🌃'],
        'U+1F304' => ['name' => 'SUNRISE OVER MOUNTAINS','category' => 'Uncategorized','emoji' => '🌄'],
        'U+1F305' => ['name' => 'SUNRISE','category' => 'Uncategorized','emoji' => '🌅'],
        'U+1F306' => ['name' => 'CITYSCAPE AT DUSK','category' => 'Uncategorized','emoji' => '🌆'],
        'U+1F307' => ['name' => 'SUNSET OVER BUILDINGS','category' => 'Uncategorized','emoji' => '🌇'],
        'U+1F308' => ['name' => 'RAINBOW','category' => 'Uncategorized','emoji' => '🌈'],
        'U+1F309' => ['name' => 'BRIDGE AT NIGHT','category' => 'Uncategorized','emoji' => '🌉'],
        'U+1F30A' => ['name' => 'WATER WAVE','category' => 'Uncategorized','emoji' => '🌊'],
        'U+1F30B' => ['name' => 'VOLCANO','category' => 'Uncategorized','emoji' => '🌋'],
        'U+1F30C' => ['name' => 'MILKY WAY','category' => 'Uncategorized','emoji' => '🌌'],
        'U+1F30F' => ['name' => 'EARTH GLOBE ASIA-AUSTRALIA','category' => 'Uncategorized','emoji' => '🌏'],
        'U+1F311' => ['name' => 'NEW MOON SYMBOL','category' => 'Uncategorized','emoji' => '🌑'],
        'U+1F313' => ['name' => 'FIRST QUARTER MOON SYMBOL','category' => 'Uncategorized','emoji' => '🌓'],
        'U+1F314' => ['name' => 'WAXING GIBBOUS MOON SYMBOL','category' => 'Uncategorized','emoji' => '🌔'],
        'U+1F315' => ['name' => 'FULL MOON SYMBOL','category' => 'Uncategorized','emoji' => '🌕'],
        'U+1F319' => ['name' => 'CRESCENT MOON','category' => 'Uncategorized','emoji' => '🌙'],
        'U+1F31B' => ['name' => 'FIRST QUARTER MOON WITH FACE','category' => 'Uncategorized','emoji' => '🌛'],
        'U+1F31F' => ['name' => 'GLOWING STAR','category' => 'Uncategorized','emoji' => '🌟'],
        'U+1F320' => ['name' => 'SHOOTING STAR','category' => 'Uncategorized','emoji' => '🌠'],
        'U+1F330' => ['name' => 'CHESTNUT','category' => 'Uncategorized','emoji' => '🌰'],
        'U+1F331' => ['name' => 'SEEDLING','category' => 'Uncategorized','emoji' => '🌱'],
        'U+1F334' => ['name' => 'PALM TREE','category' => 'Uncategorized','emoji' => '🌴'],
        'U+1F335' => ['name' => 'CACTUS','category' => 'Uncategorized','emoji' => '🌵'],
        'U+1F337' => ['name' => 'TULIP','category' => 'Uncategorized','emoji' => '🌷'],
        'U+1F338' => ['name' => 'CHERRY BLOSSOM','category' => 'Uncategorized','emoji' => '🌸'],
        'U+1F339' => ['name' => 'ROSE','category' => 'Uncategorized','emoji' => '🌹'],
        'U+1F33A' => ['name' => 'HIBISCUS','category' => 'Uncategorized','emoji' => '🌺'],
        'U+1F33B' => ['name' => 'SUNFLOWER','category' => 'Uncategorized','emoji' => '🌻'],
        'U+1F33C' => ['name' => 'BLOSSOM','category' => 'Uncategorized','emoji' => '🌼'],
        'U+1F33D' => ['name' => 'EAR OF MAIZE','category' => 'Uncategorized','emoji' => '🌽'],
        'U+1F33E' => ['name' => 'EAR OF RICE','category' => 'Uncategorized','emoji' => '🌾'],
        'U+1F33F' => ['name' => 'HERB','category' => 'Uncategorized','emoji' => '🌿'],
        'U+1F340' => ['name' => 'FOUR LEAF CLOVER','category' => 'Uncategorized','emoji' => '🍀'],
        'U+1F341' => ['name' => 'MAPLE LEAF','category' => 'Uncategorized','emoji' => '🍁'],
        'U+1F342' => ['name' => 'FALLEN LEAF','category' => 'Uncategorized','emoji' => '🍂'],
        'U+1F343' => ['name' => 'LEAF FLUTTERING IN WIND','category' => 'Uncategorized','emoji' => '🍃'],
        'U+1F344' => ['name' => 'MUSHROOM','category' => 'Uncategorized','emoji' => '🍄'],
        'U+1F345' => ['name' => 'TOMATO','category' => 'Uncategorized','emoji' => '🍅'],
        'U+1F346' => ['name' => 'AUBERGINE','category' => 'Uncategorized','emoji' => '🍆'],
        'U+1F347' => ['name' => 'GRAPES','category' => 'Uncategorized','emoji' => '🍇'],
        'U+1F348' => ['name' => 'MELON','category' => 'Uncategorized','emoji' => '🍈'],
        'U+1F349' => ['name' => 'WATERMELON','category' => 'Uncategorized','emoji' => '🍉'],
        'U+1F34A' => ['name' => 'TANGERINE','category' => 'Uncategorized','emoji' => '🍊'],
        'U+1F34C' => ['name' => 'BANANA','category' => 'Uncategorized','emoji' => '🍌'],
        'U+1F34D' => ['name' => 'PINEAPPLE','category' => 'Uncategorized','emoji' => '🍍'],
        'U+1F34E' => ['name' => 'RED APPLE','category' => 'Uncategorized','emoji' => '🍎'],
        'U+1F34F' => ['name' => 'GREEN APPLE','category' => 'Uncategorized','emoji' => '🍏'],
        'U+1F351' => ['name' => 'PEACH','category' => 'Uncategorized','emoji' => '🍑'],
        'U+1F352' => ['name' => 'CHERRIES','category' => 'Uncategorized','emoji' => '🍒'],
        'U+1F353' => ['name' => 'STRAWBERRY','category' => 'Uncategorized','emoji' => '🍓'],
        'U+1F354' => ['name' => 'HAMBURGER','category' => 'Uncategorized','emoji' => '🍔'],
        'U+1F355' => ['name' => 'SLICE OF PIZZA','category' => 'Uncategorized','emoji' => '🍕'],
        'U+1F356' => ['name' => 'MEAT ON BONE','category' => 'Uncategorized','emoji' => '🍖'],
        'U+1F357' => ['name' => 'POULTRY LEG','category' => 'Uncategorized','emoji' => '🍗'],
        'U+1F358' => ['name' => 'RICE CRACKER','category' => 'Uncategorized','emoji' => '🍘'],
        'U+1F359' => ['name' => 'RICE BALL','category' => 'Uncategorized','emoji' => '🍙'],
        'U+1F35A' => ['name' => 'COOKED RICE','category' => 'Uncategorized','emoji' => '🍚'],
        'U+1F35B' => ['name' => 'CURRY AND RICE','category' => 'Uncategorized','emoji' => '🍛'],
        'U+1F35C' => ['name' => 'STEAMING BOWL','category' => 'Uncategorized','emoji' => '🍜'],
        'U+1F35D' => ['name' => 'SPAGHETTI','category' => 'Uncategorized','emoji' => '🍝'],
        'U+1F35E' => ['name' => 'BREAD','category' => 'Uncategorized','emoji' => '🍞'],
        'U+1F35F' => ['name' => 'FRENCH FRIES','category' => 'Uncategorized','emoji' => '🍟'],
        'U+1F360' => ['name' => 'ROASTED SWEET POTATO','category' => 'Uncategorized','emoji' => '🍠'],
        'U+1F361' => ['name' => 'DANGO','category' => 'Uncategorized','emoji' => '🍡'],
        'U+1F362' => ['name' => 'ODEN','category' => 'Uncategorized','emoji' => '🍢'],
        'U+1F363' => ['name' => 'SUSHI','category' => 'Uncategorized','emoji' => '🍣'],
        'U+1F364' => ['name' => 'FRIED SHRIMP','category' => 'Uncategorized','emoji' => '🍤'],
        'U+1F365' => ['name' => 'FISH CAKE WITH SWIRL DESIGN','category' => 'Uncategorized','emoji' => '🍥'],
        'U+1F366' => ['name' => 'SOFT ICE CREAM','category' => 'Uncategorized','emoji' => '🍦'],
        'U+1F367' => ['name' => 'SHAVED ICE','category' => 'Uncategorized','emoji' => '🍧'],
        'U+1F368' => ['name' => 'ICE CREAM','category' => 'Uncategorized','emoji' => '🍨'],
        'U+1F369' => ['name' => 'DOUGHNUT','category' => 'Uncategorized','emoji' => '🍩'],
        'U+1F36A' => ['name' => 'COOKIE','category' => 'Uncategorized','emoji' => '🍪'],
        'U+1F36B' => ['name' => 'CHOCOLATE BAR','category' => 'Uncategorized','emoji' => '🍫'],
        'U+1F36C' => ['name' => 'CANDY','category' => 'Uncategorized','emoji' => '🍬'],
        'U+1F36D' => ['name' => 'LOLLIPOP','category' => 'Uncategorized','emoji' => '🍭'],
        'U+1F36E' => ['name' => 'CUSTARD','category' => 'Uncategorized','emoji' => '🍮'],
        'U+1F36F' => ['name' => 'HONEY POT','category' => 'Uncategorized','emoji' => '🍯'],
        'U+1F370' => ['name' => 'SHORTCAKE','category' => 'Uncategorized','emoji' => '🍰'],
        'U+1F371' => ['name' => 'BENTO BOX','category' => 'Uncategorized','emoji' => '🍱'],
        'U+1F372' => ['name' => 'POT OF FOOD','category' => 'Uncategorized','emoji' => '🍲'],
        'U+1F373' => ['name' => 'COOKING','category' => 'Uncategorized','emoji' => '🍳'],
        'U+1F374' => ['name' => 'FORK AND KNIFE','category' => 'Uncategorized','emoji' => '🍴'],
        'U+1F375' => ['name' => 'TEACUP WITHOUT HANDLE','category' => 'Uncategorized','emoji' => '🍵'],
        'U+1F376' => ['name' => 'SAKE BOTTLE AND CUP','category' => 'Uncategorized','emoji' => '🍶'],
        'U+1F377' => ['name' => 'WINE GLASS','category' => 'Uncategorized','emoji' => '🍷'],
        'U+1F378' => ['name' => 'COCKTAIL GLASS','category' => 'Uncategorized','emoji' => '🍸'],
        'U+1F379' => ['name' => 'TROPICAL DRINK','category' => 'Uncategorized','emoji' => '🍹'],
        'U+1F37A' => ['name' => 'BEER MUG','category' => 'Uncategorized','emoji' => '🍺'],
        'U+1F37B' => ['name' => 'CLINKING BEER MUGS','category' => 'Uncategorized','emoji' => '🍻'],
        'U+1F380' => ['name' => 'RIBBON','category' => 'Uncategorized','emoji' => '🎀'],
        'U+1F381' => ['name' => 'WRAPPED PRESENT','category' => 'Uncategorized','emoji' => '🎁'],
        'U+1F382' => ['name' => 'BIRTHDAY CAKE','category' => 'Uncategorized','emoji' => '🎂'],
        'U+1F383' => ['name' => 'JACK-O-LANTERN','category' => 'Uncategorized','emoji' => '🎃'],
        'U+1F384' => ['name' => 'CHRISTMAS TREE','category' => 'Uncategorized','emoji' => '🎄'],
        'U+1F385' => ['name' => 'FATHER CHRISTMAS','category' => 'Uncategorized','emoji' => '🎅'],
        'U+1F386' => ['name' => 'FIREWORKS','category' => 'Uncategorized','emoji' => '🎆'],
        'U+1F387' => ['name' => 'FIREWORK SPARKLER','category' => 'Uncategorized','emoji' => '🎇'],
        'U+1F388' => ['name' => 'BALLOON','category' => 'Uncategorized','emoji' => '🎈'],
        'U+1F389' => ['name' => 'PARTY POPPER','category' => 'Uncategorized','emoji' => '🎉'],
        'U+1F38A' => ['name' => 'CONFETTI BALL','category' => 'Uncategorized','emoji' => '🎊'],
        'U+1F38B' => ['name' => 'TANABATA TREE','category' => 'Uncategorized','emoji' => '🎋'],
        'U+1F38C' => ['name' => 'CROSSED FLAGS','category' => 'Uncategorized','emoji' => '🎌'],
        'U+1F38D' => ['name' => 'PINE DECORATION','category' => 'Uncategorized','emoji' => '🎍'],
        'U+1F38E' => ['name' => 'JAPANESE DOLLS','category' => 'Uncategorized','emoji' => '🎎'],
        'U+1F38F' => ['name' => 'CARP STREAMER','category' => 'Uncategorized','emoji' => '🎏'],
        'U+1F390' => ['name' => 'WIND CHIME','category' => 'Uncategorized','emoji' => '🎐'],
        'U+1F391' => ['name' => 'MOON VIEWING CEREMONY','category' => 'Uncategorized','emoji' => '🎑'],
        'U+1F392' => ['name' => 'SCHOOL SATCHEL','category' => 'Uncategorized','emoji' => '🎒'],
        'U+1F393' => ['name' => 'GRADUATION CAP','category' => 'Uncategorized','emoji' => '🎓'],
        'U+1F3A0' => ['name' => 'CAROUSEL HORSE','category' => 'Uncategorized','emoji' => '🎠'],
        'U+1F3A1' => ['name' => 'FERRIS WHEEL','category' => 'Uncategorized','emoji' => '🎡'],
        'U+1F3A2' => ['name' => 'ROLLER COASTER','category' => 'Uncategorized','emoji' => '🎢'],
        'U+1F3A3' => ['name' => 'FISHING POLE AND FISH','category' => 'Uncategorized','emoji' => '🎣'],
        'U+1F3A4' => ['name' => 'MICROPHONE','category' => 'Uncategorized','emoji' => '🎤'],
        'U+1F3A5' => ['name' => 'MOVIE CAMERA','category' => 'Uncategorized','emoji' => '🎥'],
        'U+1F3A6' => ['name' => 'CINEMA','category' => 'Uncategorized','emoji' => '🎦'],
        'U+1F3A7' => ['name' => 'HEADPHONE','category' => 'Uncategorized','emoji' => '🎧'],
        'U+1F3A8' => ['name' => 'ARTIST PALETTE','category' => 'Uncategorized','emoji' => '🎨'],
        'U+1F3A9' => ['name' => 'TOP HAT','category' => 'Uncategorized','emoji' => '🎩'],
        'U+1F3AA' => ['name' => 'CIRCUS TENT','category' => 'Uncategorized','emoji' => '🎪'],
        'U+1F3AB' => ['name' => 'TICKET','category' => 'Uncategorized','emoji' => '🎫'],
        'U+1F3AC' => ['name' => 'CLAPPER BOARD','category' => 'Uncategorized','emoji' => '🎬'],
        'U+1F3AD' => ['name' => 'PERFORMING ARTS','category' => 'Uncategorized','emoji' => '🎭'],
        'U+1F3AE' => ['name' => 'VIDEO GAME','category' => 'Uncategorized','emoji' => '🎮'],
        'U+1F3AF' => ['name' => 'DIRECT HIT','category' => 'Uncategorized','emoji' => '🎯'],
        'U+1F3B0' => ['name' => 'SLOT MACHINE','category' => 'Uncategorized','emoji' => '🎰'],
        'U+1F3B1' => ['name' => 'BILLIARDS','category' => 'Uncategorized','emoji' => '🎱'],
        'U+1F3B2' => ['name' => 'GAME DIE','category' => 'Uncategorized','emoji' => '🎲'],
        'U+1F3B3' => ['name' => 'BOWLING','category' => 'Uncategorized','emoji' => '🎳'],
        'U+1F3B4' => ['name' => 'FLOWER PLAYING CARDS','category' => 'Uncategorized','emoji' => '🎴'],
        'U+1F3B5' => ['name' => 'MUSICAL NOTE','category' => 'Uncategorized','emoji' => '🎵'],
        'U+1F3B6' => ['name' => 'MULTIPLE MUSICAL NOTES','category' => 'Uncategorized','emoji' => '🎶'],
        'U+1F3B7' => ['name' => 'SAXOPHONE','category' => 'Uncategorized','emoji' => '🎷'],
        'U+1F3B8' => ['name' => 'GUITAR','category' => 'Uncategorized','emoji' => '🎸'],
        'U+1F3B9' => ['name' => 'MUSICAL KEYBOARD','category' => 'Uncategorized','emoji' => '🎹'],
        'U+1F3BA' => ['name' => 'TRUMPET','category' => 'Uncategorized','emoji' => '🎺'],
        'U+1F3BB' => ['name' => 'VIOLIN','category' => 'Uncategorized','emoji' => '🎻'],
        'U+1F3BC' => ['name' => 'MUSICAL SCORE','category' => 'Uncategorized','emoji' => '🎼'],
        'U+1F3BD' => ['name' => 'RUNNING SHIRT WITH SASH','category' => 'Uncategorized','emoji' => '🎽'],
        'U+1F3BE' => ['name' => 'TENNIS RACQUET AND BALL','category' => 'Uncategorized','emoji' => '🎾'],
        'U+1F3BF' => ['name' => 'SKI AND SKI BOOT','category' => 'Uncategorized','emoji' => '🎿'],
        'U+1F3C0' => ['name' => 'BASKETBALL AND HOOP','category' => 'Uncategorized','emoji' => '🏀'],
        'U+1F3C1' => ['name' => 'CHEQUERED FLAG','category' => 'Uncategorized','emoji' => '🏁'],
        'U+1F3C2' => ['name' => 'SNOWBOARDER','category' => 'Uncategorized','emoji' => '🏂'],
        'U+1F3C3' => ['name' => 'RUNNER','category' => 'Uncategorized','emoji' => '🏃'],
        'U+1F3C4' => ['name' => 'SURFER','category' => 'Uncategorized','emoji' => '🏄'],
        'U+1F3C6' => ['name' => 'TROPHY','category' => 'Uncategorized','emoji' => '🏆'],
        'U+1F3C8' => ['name' => 'AMERICAN FOOTBALL','category' => 'Uncategorized','emoji' => '🏈'],
        'U+1F3CA' => ['name' => 'SWIMMER','category' => 'Uncategorized','emoji' => '🏊'],
        'U+1F3E0' => ['name' => 'HOUSE BUILDING','category' => 'Uncategorized','emoji' => '🏠'],
        'U+1F3E1' => ['name' => 'HOUSE WITH GARDEN','category' => 'Uncategorized','emoji' => '🏡'],
        'U+1F3E2' => ['name' => 'OFFICE BUILDING','category' => 'Uncategorized','emoji' => '🏢'],
        'U+1F3E3' => ['name' => 'JAPANESE POST OFFICE','category' => 'Uncategorized','emoji' => '🏣'],
        'U+1F3E5' => ['name' => 'HOSPITAL','category' => 'Uncategorized','emoji' => '🏥'],
        'U+1F3E6' => ['name' => 'BANK','category' => 'Uncategorized','emoji' => '🏦'],
        'U+1F3E7' => ['name' => 'AUTOMATED TELLER MACHINE','category' => 'Uncategorized','emoji' => '🏧'],
        'U+1F3E8' => ['name' => 'HOTEL','category' => 'Uncategorized','emoji' => '🏨'],
        'U+1F3E9' => ['name' => 'LOVE HOTEL','category' => 'Uncategorized','emoji' => '🏩'],
        'U+1F3EA' => ['name' => 'CONVENIENCE STORE','category' => 'Uncategorized','emoji' => '🏪'],
        'U+1F3EB' => ['name' => 'SCHOOL','category' => 'Uncategorized','emoji' => '🏫'],
        'U+1F3EC' => ['name' => 'DEPARTMENT STORE','category' => 'Uncategorized','emoji' => '🏬'],
        'U+1F3ED' => ['name' => 'FACTORY','category' => 'Uncategorized','emoji' => '🏭'],
        'U+1F3EE' => ['name' => 'IZAKAYA LANTERN','category' => 'Uncategorized','emoji' => '🏮'],
        'U+1F3EF' => ['name' => 'JAPANESE CASTLE','category' => 'Uncategorized','emoji' => '🏯'],
        'U+1F3F0' => ['name' => 'EUROPEAN CASTLE','category' => 'Uncategorized','emoji' => '🏰'],
        'U+1F40C' => ['name' => 'SNAIL','category' => 'Uncategorized','emoji' => '🐌'],
        'U+1F40D' => ['name' => 'SNAKE','category' => 'Uncategorized','emoji' => '🐍'],
        'U+1F40E' => ['name' => 'HORSE','category' => 'Uncategorized','emoji' => '🐎'],
        'U+1F411' => ['name' => 'SHEEP','category' => 'Uncategorized','emoji' => '🐑'],
        'U+1F412' => ['name' => 'MONKEY','category' => 'Uncategorized','emoji' => '🐒'],
        'U+1F414' => ['name' => 'CHICKEN','category' => 'Uncategorized','emoji' => '🐔'],
        'U+1F417' => ['name' => 'BOAR','category' => 'Uncategorized','emoji' => '🐗'],
        'U+1F418' => ['name' => 'ELEPHANT','category' => 'Uncategorized','emoji' => '🐘'],
        'U+1F419' => ['name' => 'OCTOPUS','category' => 'Uncategorized','emoji' => '🐙'],
        'U+1F41A' => ['name' => 'SPIRAL SHELL','category' => 'Uncategorized','emoji' => '🐚'],
        'U+1F41B' => ['name' => 'BUG','category' => 'Uncategorized','emoji' => '🐛'],
        'U+1F41C' => ['name' => 'ANT','category' => 'Uncategorized','emoji' => '🐜'],
        'U+1F41D' => ['name' => 'HONEYBEE','category' => 'Uncategorized','emoji' => '🐝'],
        'U+1F41E' => ['name' => 'LADY BEETLE','category' => 'Uncategorized','emoji' => '🐞'],
        'U+1F41F' => ['name' => 'FISH','category' => 'Uncategorized','emoji' => '🐟'],
        'U+1F420' => ['name' => 'TROPICAL FISH','category' => 'Uncategorized','emoji' => '🐠'],
        'U+1F421' => ['name' => 'BLOWFISH','category' => 'Uncategorized','emoji' => '🐡'],
        'U+1F422' => ['name' => 'TURTLE','category' => 'Uncategorized','emoji' => '🐢'],
        'U+1F423' => ['name' => 'HATCHING CHICK','category' => 'Uncategorized','emoji' => '🐣'],
        'U+1F424' => ['name' => 'BABY CHICK','category' => 'Uncategorized','emoji' => '🐤'],
        'U+1F425' => ['name' => 'FRONT-FACING BABY CHICK','category' => 'Uncategorized','emoji' => '🐥'],
        'U+1F426' => ['name' => 'BIRD','category' => 'Uncategorized','emoji' => '🐦'],
        'U+1F427' => ['name' => 'PENGUIN','category' => 'Uncategorized','emoji' => '🐧'],
        'U+1F428' => ['name' => 'KOALA','category' => 'Uncategorized','emoji' => '🐨'],
        'U+1F429' => ['name' => 'POODLE','category' => 'Uncategorized','emoji' => '🐩'],
        'U+1F42B' => ['name' => 'BACTRIAN CAMEL','category' => 'Uncategorized','emoji' => '🐫'],
        'U+1F42C' => ['name' => 'DOLPHIN','category' => 'Uncategorized','emoji' => '🐬'],
        'U+1F42D' => ['name' => 'MOUSE FACE','category' => 'Uncategorized','emoji' => '🐭'],
        'U+1F42E' => ['name' => 'COW FACE','category' => 'Uncategorized','emoji' => '🐮'],
        'U+1F42F' => ['name' => 'TIGER FACE','category' => 'Uncategorized','emoji' => '🐯'],
        'U+1F430' => ['name' => 'RABBIT FACE','category' => 'Uncategorized','emoji' => '🐰'],
        'U+1F431' => ['name' => 'CAT FACE','category' => 'Uncategorized','emoji' => '🐱'],
        'U+1F432' => ['name' => 'DRAGON FACE','category' => 'Uncategorized','emoji' => '🐲'],
        'U+1F433' => ['name' => 'SPOUTING WHALE','category' => 'Uncategorized','emoji' => '🐳'],
        'U+1F434' => ['name' => 'HORSE FACE','category' => 'Uncategorized','emoji' => '🐴'],
        'U+1F435' => ['name' => 'MONKEY FACE','category' => 'Uncategorized','emoji' => '🐵'],
        'U+1F436' => ['name' => 'DOG FACE','category' => 'Uncategorized','emoji' => '🐶'],
        'U+1F437' => ['name' => 'PIG FACE','category' => 'Uncategorized','emoji' => '🐷'],
        'U+1F438' => ['name' => 'FROG FACE','category' => 'Uncategorized','emoji' => '🐸'],
        'U+1F439' => ['name' => 'HAMSTER FACE','category' => 'Uncategorized','emoji' => '🐹'],
        'U+1F43A' => ['name' => 'WOLF FACE','category' => 'Uncategorized','emoji' => '🐺'],
        'U+1F43B' => ['name' => 'BEAR FACE','category' => 'Uncategorized','emoji' => '🐻'],
        'U+1F43C' => ['name' => 'PANDA FACE','category' => 'Uncategorized','emoji' => '🐼'],
        'U+1F43D' => ['name' => 'PIG NOSE','category' => 'Uncategorized','emoji' => '🐽'],
        'U+1F43E' => ['name' => 'PAW PRINTS','category' => 'Uncategorized','emoji' => '🐾'],
        'U+1F440' => ['name' => 'EYES','category' => 'Uncategorized','emoji' => '👀'],
        'U+1F442' => ['name' => 'EAR','category' => 'Uncategorized','emoji' => '👂'],
        'U+1F443' => ['name' => 'NOSE','category' => 'Uncategorized','emoji' => '👃'],
        'U+1F444' => ['name' => 'MOUTH','category' => 'Uncategorized','emoji' => '👄'],
        'U+1F445' => ['name' => 'TONGUE','category' => 'Uncategorized','emoji' => '👅'],
        'U+1F446' => ['name' => 'WHITE UP POINTING BACKHAND INDEX','category' => 'Uncategorized','emoji' => '👆'],
        'U+1F447' => ['name' => 'WHITE DOWN POINTING BACKHAND INDEX','category' => 'Uncategorized','emoji' => '👇'],
        'U+1F448' => ['name' => 'WHITE LEFT POINTING BACKHAND INDEX','category' => 'Uncategorized','emoji' => '👈'],
        'U+1F449' => ['name' => 'WHITE RIGHT POINTING BACKHAND INDEX','category' => 'Uncategorized','emoji' => '👉'],
        'U+1F44A' => ['name' => 'FISTED HAND SIGN','category' => 'Uncategorized','emoji' => '👊'],
        'U+1F44B' => ['name' => 'WAVING HAND SIGN','category' => 'Uncategorized','emoji' => '👋'],
        'U+1F44C' => ['name' => 'OK HAND SIGN','category' => 'Uncategorized','emoji' => '👌'],
        'U+1F44D' => ['name' => 'THUMBS UP SIGN','category' => 'Uncategorized','emoji' => '👍'],
        'U+1F44E' => ['name' => 'THUMBS DOWN SIGN','category' => 'Uncategorized','emoji' => '👎'],
        'U+1F44F' => ['name' => 'CLAPPING HANDS SIGN','category' => 'Uncategorized','emoji' => '👏'],
        'U+1F450' => ['name' => 'OPEN HANDS SIGN','category' => 'Uncategorized','emoji' => '👐'],
        'U+1F451' => ['name' => 'CROWN','category' => 'Uncategorized','emoji' => '👑'],
        'U+1F452' => ['name' => 'WOMANS HAT','category' => 'Uncategorized','emoji' => '👒'],
        'U+1F453' => ['name' => 'EYEGLASSES','category' => 'Uncategorized','emoji' => '👓'],
        'U+1F454' => ['name' => 'NECKTIE','category' => 'Uncategorized','emoji' => '👔'],
        'U+1F455' => ['name' => 'T-SHIRT','category' => 'Uncategorized','emoji' => '👕'],
        'U+1F456' => ['name' => 'JEANS','category' => 'Uncategorized','emoji' => '👖'],
        'U+1F457' => ['name' => 'DRESS','category' => 'Uncategorized','emoji' => '👗'],
        'U+1F458' => ['name' => 'KIMONO','category' => 'Uncategorized','emoji' => '👘'],
        'U+1F459' => ['name' => 'BIKINI','category' => 'Uncategorized','emoji' => '👙'],
        'U+1F45A' => ['name' => 'WOMANS CLOTHES','category' => 'Uncategorized','emoji' => '👚'],
        'U+1F45B' => ['name' => 'PURSE','category' => 'Uncategorized','emoji' => '👛'],
        'U+1F45C' => ['name' => 'HANDBAG','category' => 'Uncategorized','emoji' => '👜'],
        'U+1F45D' => ['name' => 'POUCH','category' => 'Uncategorized','emoji' => '👝'],
        'U+1F45E' => ['name' => 'MANS SHOE','category' => 'Uncategorized','emoji' => '👞'],
        'U+1F45F' => ['name' => 'ATHLETIC SHOE','category' => 'Uncategorized','emoji' => '👟'],
        'U+1F460' => ['name' => 'HIGH-HEELED SHOE','category' => 'Uncategorized','emoji' => '👠'],
        'U+1F461' => ['name' => 'WOMANS SANDAL','category' => 'Uncategorized','emoji' => '👡'],
        'U+1F462' => ['name' => 'WOMANS BOOTS','category' => 'Uncategorized','emoji' => '👢'],
        'U+1F463' => ['name' => 'FOOTPRINTS','category' => 'Uncategorized','emoji' => '👣'],
        'U+1F464' => ['name' => 'BUST IN SILHOUETTE','category' => 'Uncategorized','emoji' => '👤'],
        'U+1F466' => ['name' => 'BOY','category' => 'Uncategorized','emoji' => '👦'],
        'U+1F467' => ['name' => 'GIRL','category' => 'Uncategorized','emoji' => '👧'],
        'U+1F468' => ['name' => 'MAN','category' => 'Uncategorized','emoji' => '👨'],
        'U+1F469' => ['name' => 'WOMAN','category' => 'Uncategorized','emoji' => '👩'],
        'U+1F46A' => ['name' => 'FAMILY','category' => 'Uncategorized','emoji' => '👪'],
        'U+1F46B' => ['name' => 'MAN AND WOMAN HOLDING HANDS','category' => 'Uncategorized','emoji' => '👫'],
        'U+1F46E' => ['name' => 'POLICE OFFICER','category' => 'Uncategorized','emoji' => '👮'],
        'U+1F46F' => ['name' => 'WOMAN WITH BUNNY EARS','category' => 'Uncategorized','emoji' => '👯'],
        'U+1F470' => ['name' => 'BRIDE WITH VEIL','category' => 'Uncategorized','emoji' => '👰'],
        'U+1F471' => ['name' => 'PERSON WITH BLOND HAIR','category' => 'Uncategorized','emoji' => '👱'],
        'U+1F472' => ['name' => 'MAN WITH GUA PI MAO','category' => 'Uncategorized','emoji' => '👲'],
        'U+1F473' => ['name' => 'MAN WITH TURBAN','category' => 'Uncategorized','emoji' => '👳'],
        'U+1F474' => ['name' => 'OLDER MAN','category' => 'Uncategorized','emoji' => '👴'],
        'U+1F475' => ['name' => 'OLDER WOMAN','category' => 'Uncategorized','emoji' => '👵'],
        'U+1F476' => ['name' => 'BABY','category' => 'Uncategorized','emoji' => '👶'],
        'U+1F477' => ['name' => 'CONSTRUCTION WORKER','category' => 'Uncategorized','emoji' => '👷'],
        'U+1F478' => ['name' => 'PRINCESS','category' => 'Uncategorized','emoji' => '👸'],
        'U+1F479' => ['name' => 'JAPANESE OGRE','category' => 'Uncategorized','emoji' => '👹'],
        'U+1F47A' => ['name' => 'JAPANESE GOBLIN','category' => 'Uncategorized','emoji' => '👺'],
        'U+1F47B' => ['name' => 'GHOST','category' => 'Uncategorized','emoji' => '👻'],
        'U+1F47C' => ['name' => 'BABY ANGEL','category' => 'Uncategorized','emoji' => '👼'],
        'U+1F47D' => ['name' => 'EXTRATERRESTRIAL ALIEN','category' => 'Uncategorized','emoji' => '👽'],
        'U+1F47E' => ['name' => 'ALIEN MONSTER','category' => 'Uncategorized','emoji' => '👾'],
        'U+1F47F' => ['name' => 'IMP','category' => 'Uncategorized','emoji' => '👿'],
        'U+1F480' => ['name' => 'SKULL','category' => 'Uncategorized','emoji' => '💀'],
        'U+1F481' => ['name' => 'INFORMATION DESK PERSON','category' => 'Uncategorized','emoji' => '💁'],
        'U+1F482' => ['name' => 'GUARDSMAN','category' => 'Uncategorized','emoji' => '💂'],
        'U+1F483' => ['name' => 'DANCER','category' => 'Uncategorized','emoji' => '💃'],
        'U+1F484' => ['name' => 'LIPSTICK','category' => 'Uncategorized','emoji' => '💄'],
        'U+1F485' => ['name' => 'NAIL POLISH','category' => 'Uncategorized','emoji' => '💅'],
        'U+1F486' => ['name' => 'FACE MASSAGE','category' => 'Uncategorized','emoji' => '💆'],
        'U+1F487' => ['name' => 'HAIRCUT','category' => 'Uncategorized','emoji' => '💇'],
        'U+1F488' => ['name' => 'BARBER POLE','category' => 'Uncategorized','emoji' => '💈'],
        'U+1F489' => ['name' => 'SYRINGE','category' => 'Uncategorized','emoji' => '💉'],
        'U+1F48A' => ['name' => 'PILL','category' => 'Uncategorized','emoji' => '💊'],
        'U+1F48B' => ['name' => 'KISS MARK','category' => 'Uncategorized','emoji' => '💋'],
        'U+1F48C' => ['name' => 'LOVE LETTER','category' => 'Uncategorized','emoji' => '💌'],
        'U+1F48D' => ['name' => 'RING','category' => 'Uncategorized','emoji' => '💍'],
        'U+1F48E' => ['name' => 'GEM STONE','category' => 'Uncategorized','emoji' => '💎'],
        'U+1F48F' => ['name' => 'KISS','category' => 'Uncategorized','emoji' => '💏'],
        'U+1F490' => ['name' => 'BOUQUET','category' => 'Uncategorized','emoji' => '💐'],
        'U+1F491' => ['name' => 'COUPLE WITH HEART','category' => 'Uncategorized','emoji' => '💑'],
        'U+1F492' => ['name' => 'WEDDING','category' => 'Uncategorized','emoji' => '💒'],
        'U+1F493' => ['name' => 'BEATING HEART','category' => 'Uncategorized','emoji' => '💓'],
        'U+1F494' => ['name' => 'BROKEN HEART','category' => 'Uncategorized','emoji' => '💔'],
        'U+1F495' => ['name' => 'TWO HEARTS','category' => 'Uncategorized','emoji' => '💕'],
        'U+1F496' => ['name' => 'SPARKLING HEART','category' => 'Uncategorized','emoji' => '💖'],
        'U+1F497' => ['name' => 'GROWING HEART','category' => 'Uncategorized','emoji' => '💗'],
        'U+1F498' => ['name' => 'HEART WITH ARROW','category' => 'Uncategorized','emoji' => '💘'],
        'U+1F499' => ['name' => 'BLUE HEART','category' => 'Uncategorized','emoji' => '💙'],
        'U+1F49A' => ['name' => 'GREEN HEART','category' => 'Uncategorized','emoji' => '💚'],
        'U+1F49B' => ['name' => 'YELLOW HEART','category' => 'Uncategorized','emoji' => '💛'],
        'U+1F49C' => ['name' => 'PURPLE HEART','category' => 'Uncategorized','emoji' => '💜'],
        'U+1F49D' => ['name' => 'HEART WITH RIBBON','category' => 'Uncategorized','emoji' => '💝'],
        'U+1F49E' => ['name' => 'REVOLVING HEARTS','category' => 'Uncategorized','emoji' => '💞'],
        'U+1F49F' => ['name' => 'HEART DECORATION','category' => 'Uncategorized','emoji' => '💟'],
        'U+1F4A0' => ['name' => 'DIAMOND SHAPE WITH A DOT INSIDE','category' => 'Uncategorized','emoji' => '💠'],
        'U+1F4A1' => ['name' => 'ELECTRIC LIGHT BULB','category' => 'Uncategorized','emoji' => '💡'],
        'U+1F4A2' => ['name' => 'ANGER SYMBOL','category' => 'Uncategorized','emoji' => '💢'],
        'U+1F4A3' => ['name' => 'BOMB','category' => 'Uncategorized','emoji' => '💣'],
        'U+1F4A4' => ['name' => 'SLEEPING SYMBOL','category' => 'Uncategorized','emoji' => '💤'],
        'U+1F4A5' => ['name' => 'COLLISION SYMBOL','category' => 'Uncategorized','emoji' => '💥'],
        'U+1F4A6' => ['name' => 'SPLASHING SWEAT SYMBOL','category' => 'Uncategorized','emoji' => '💦'],
        'U+1F4A7' => ['name' => 'DROPLET','category' => 'Uncategorized','emoji' => '💧'],
        'U+1F4A8' => ['name' => 'DASH SYMBOL','category' => 'Uncategorized','emoji' => '💨'],
        'U+1F4A9' => ['name' => 'PILE OF POO','category' => 'Uncategorized','emoji' => '💩'],
        'U+1F4AA' => ['name' => 'FLEXED BICEPS','category' => 'Uncategorized','emoji' => '💪'],
        'U+1F4AB' => ['name' => 'DIZZY SYMBOL','category' => 'Uncategorized','emoji' => '💫'],
        'U+1F4AC' => ['name' => 'SPEECH BALLOON','category' => 'Uncategorized','emoji' => '💬'],
        'U+1F4AE' => ['name' => 'WHITE FLOWER','category' => 'Uncategorized','emoji' => '💮'],
        'U+1F4AF' => ['name' => 'HUNDRED POINTS SYMBOL','category' => 'Uncategorized','emoji' => '💯'],
        'U+1F4B0' => ['name' => 'MONEY BAG','category' => 'Uncategorized','emoji' => '💰'],
        'U+1F4B1' => ['name' => 'CURRENCY EXCHANGE','category' => 'Uncategorized','emoji' => '💱'],
        'U+1F4B2' => ['name' => 'HEAVY DOLLAR SIGN','category' => 'Uncategorized','emoji' => '💲'],
        'U+1F4B3' => ['name' => 'CREDIT CARD','category' => 'Uncategorized','emoji' => '💳'],
        'U+1F4B4' => ['name' => 'BANKNOTE WITH YEN SIGN','category' => 'Uncategorized','emoji' => '💴'],
        'U+1F4B5' => ['name' => 'BANKNOTE WITH DOLLAR SIGN','category' => 'Uncategorized','emoji' => '💵'],
        'U+1F4B8' => ['name' => 'MONEY WITH WINGS','category' => 'Uncategorized','emoji' => '💸'],
        'U+1F4B9' => ['name' => 'CHART WITH UPWARDS TREND AND YEN SIGN','category' => 'Uncategorized','emoji' => '💹'],
        'U+1F4BA' => ['name' => 'SEAT','category' => 'Uncategorized','emoji' => '💺'],
        'U+1F4BB' => ['name' => 'PERSONAL COMPUTER','category' => 'Uncategorized','emoji' => '💻'],
        'U+1F4BC' => ['name' => 'BRIEFCASE','category' => 'Uncategorized','emoji' => '💼'],
        'U+1F4BD' => ['name' => 'MINIDISC','category' => 'Uncategorized','emoji' => '💽'],
        'U+1F4BE' => ['name' => 'FLOPPY DISK','category' => 'Uncategorized','emoji' => '💾'],
        'U+1F4BF' => ['name' => 'OPTICAL DISC','category' => 'Uncategorized','emoji' => '💿'],
        'U+1F4C0' => ['name' => 'DVD','category' => 'Uncategorized','emoji' => '📀'],
        'U+1F4C1' => ['name' => 'FILE FOLDER','category' => 'Uncategorized','emoji' => '📁'],
        'U+1F4C2' => ['name' => 'OPEN FILE FOLDER','category' => 'Uncategorized','emoji' => '📂'],
        'U+1F4C3' => ['name' => 'PAGE WITH CURL','category' => 'Uncategorized','emoji' => '📃'],
        'U+1F4C4' => ['name' => 'PAGE FACING UP','category' => 'Uncategorized','emoji' => '📄'],
        'U+1F4C5' => ['name' => 'CALENDAR','category' => 'Uncategorized','emoji' => '📅'],
        'U+1F4C6' => ['name' => 'TEAR-OFF CALENDAR','category' => 'Uncategorized','emoji' => '📆'],
        'U+1F4C7' => ['name' => 'CARD INDEX','category' => 'Uncategorized','emoji' => '📇'],
        'U+1F4C8' => ['name' => 'CHART WITH UPWARDS TREND','category' => 'Uncategorized','emoji' => '📈'],
        'U+1F4C9' => ['name' => 'CHART WITH DOWNWARDS TREND','category' => 'Uncategorized','emoji' => '📉'],
        'U+1F4CA' => ['name' => 'BAR CHART','category' => 'Uncategorized','emoji' => '📊'],
        'U+1F4CB' => ['name' => 'CLIPBOARD','category' => 'Uncategorized','emoji' => '📋'],
        'U+1F4CC' => ['name' => 'PUSHPIN','category' => 'Uncategorized','emoji' => '📌'],
        'U+1F4CD' => ['name' => 'ROUND PUSHPIN','category' => 'Uncategorized','emoji' => '📍'],
        'U+1F4CE' => ['name' => 'PAPERCLIP','category' => 'Uncategorized','emoji' => '📎'],
        'U+1F4CF' => ['name' => 'STRAIGHT RULER','category' => 'Uncategorized','emoji' => '📏'],
        'U+1F4D0' => ['name' => 'TRIANGULAR RULER','category' => 'Uncategorized','emoji' => '📐'],
        'U+1F4D1' => ['name' => 'BOOKMARK TABS','category' => 'Uncategorized','emoji' => '📑'],
        'U+1F4D2' => ['name' => 'LEDGER','category' => 'Uncategorized','emoji' => '📒'],
        'U+1F4D3' => ['name' => 'NOTEBOOK','category' => 'Uncategorized','emoji' => '📓'],
        'U+1F4D4' => ['name' => 'NOTEBOOK WITH DECORATIVE COVER','category' => 'Uncategorized','emoji' => '📔'],
        'U+1F4D5' => ['name' => 'CLOSED BOOK','category' => 'Uncategorized','emoji' => '📕'],
        'U+1F4D6' => ['name' => 'OPEN BOOK','category' => 'Uncategorized','emoji' => '📖'],
        'U+1F4D7' => ['name' => 'GREEN BOOK','category' => 'Uncategorized','emoji' => '📗'],
        'U+1F4D8' => ['name' => 'BLUE BOOK','category' => 'Uncategorized','emoji' => '📘'],
        'U+1F4D9' => ['name' => 'ORANGE BOOK','category' => 'Uncategorized','emoji' => '📙'],
        'U+1F4DA' => ['name' => 'BOOKS','category' => 'Uncategorized','emoji' => '📚'],
        'U+1F4DB' => ['name' => 'NAME BADGE','category' => 'Uncategorized','emoji' => '📛'],
        'U+1F4DC' => ['name' => 'SCROLL','category' => 'Uncategorized','emoji' => '📜'],
        'U+1F4DD' => ['name' => 'MEMO','category' => 'Uncategorized','emoji' => '📝'],
        'U+1F4DE' => ['name' => 'TELEPHONE RECEIVER','category' => 'Uncategorized','emoji' => '📞'],
        'U+1F4DF' => ['name' => 'PAGER','category' => 'Uncategorized','emoji' => '📟'],
        'U+1F4E0' => ['name' => 'FAX MACHINE','category' => 'Uncategorized','emoji' => '📠'],
        'U+1F4E1' => ['name' => 'SATELLITE ANTENNA','category' => 'Uncategorized','emoji' => '📡'],
        'U+1F4E2' => ['name' => 'PUBLIC ADDRESS LOUDSPEAKER','category' => 'Uncategorized','emoji' => '📢'],
        'U+1F4E3' => ['name' => 'CHEERING MEGAPHONE','category' => 'Uncategorized','emoji' => '📣'],
        'U+1F4E4' => ['name' => 'OUTBOX TRAY','category' => 'Uncategorized','emoji' => '📤'],
        'U+1F4E5' => ['name' => 'INBOX TRAY','category' => 'Uncategorized','emoji' => '📥'],
        'U+1F4E6' => ['name' => 'PACKAGE','category' => 'Uncategorized','emoji' => '📦'],
        'U+1F4E7' => ['name' => 'E-MAIL SYMBOL','category' => 'Uncategorized','emoji' => '📧'],
        'U+1F4E8' => ['name' => 'INCOMING ENVELOPE','category' => 'Uncategorized','emoji' => '📨'],
        'U+1F4E9' => ['name' => 'ENVELOPE WITH DOWNWARDS ARROW ABOVE','category' => 'Uncategorized','emoji' => '📩'],
        'U+1F4EA' => ['name' => 'CLOSED MAILBOX WITH LOWERED FLAG','category' => 'Uncategorized','emoji' => '📪'],
        'U+1F4EB' => ['name' => 'CLOSED MAILBOX WITH RAISED FLAG','category' => 'Uncategorized','emoji' => '📫'],
        'U+1F4EE' => ['name' => 'POSTBOX','category' => 'Uncategorized','emoji' => '📮'],
        'U+1F4F0' => ['name' => 'NEWSPAPER','category' => 'Uncategorized','emoji' => '📰'],
        'U+1F4F1' => ['name' => 'MOBILE PHONE','category' => 'Uncategorized','emoji' => '📱'],
        'U+1F4F2' => ['name' => 'MOBILE PHONE WITH RIGHTWARDS ARROW AT LEFT','category' => 'Uncategorized','emoji' => '📲'],
        'U+1F4F3' => ['name' => 'VIBRATION MODE','category' => 'Uncategorized','emoji' => '📳'],
        'U+1F4F4' => ['name' => 'MOBILE PHONE OFF','category' => 'Uncategorized','emoji' => '📴'],
        'U+1F4F6' => ['name' => 'ANTENNA WITH BARS','category' => 'Uncategorized','emoji' => '📶'],
        'U+1F4F7' => ['name' => 'CAMERA','category' => 'Uncategorized','emoji' => '📷'],
        'U+1F4F9' => ['name' => 'VIDEO CAMERA','category' => 'Uncategorized','emoji' => '📹'],
        'U+1F4FA' => ['name' => 'TELEVISION','category' => 'Uncategorized','emoji' => '📺'],
        'U+1F4FB' => ['name' => 'RADIO','category' => 'Uncategorized','emoji' => '📻'],
        'U+1F4FC' => ['name' => 'VIDEOCASSETTE','category' => 'Uncategorized','emoji' => '📼'],
        'U+1F503' => ['name' => 'CLOCKWISE DOWNWARDS AND UPWARDS OPEN CIRCLE ARROWS','category' => 'Uncategorized','emoji' => '🔃'],
        'U+1F50A' => ['name' => 'SPEAKER WITH THREE SOUND WAVES','category' => 'Uncategorized','emoji' => '🔊'],
        'U+1F50B' => ['name' => 'BATTERY','category' => 'Uncategorized','emoji' => '🔋'],
        'U+1F50C' => ['name' => 'ELECTRIC PLUG','category' => 'Uncategorized','emoji' => '🔌'],
        'U+1F50D' => ['name' => 'LEFT-POINTING MAGNIFYING GLASS','category' => 'Uncategorized','emoji' => '🔍'],
        'U+1F50E' => ['name' => 'RIGHT-POINTING MAGNIFYING GLASS','category' => 'Uncategorized','emoji' => '🔎'],
        'U+1F50F' => ['name' => 'LOCK WITH INK PEN','category' => 'Uncategorized','emoji' => '🔏'],
        'U+1F510' => ['name' => 'CLOSED LOCK WITH KEY','category' => 'Uncategorized','emoji' => '🔐'],
        'U+1F511' => ['name' => 'KEY','category' => 'Uncategorized','emoji' => '🔑'],
        'U+1F512' => ['name' => 'LOCK','category' => 'Uncategorized','emoji' => '🔒'],
        'U+1F513' => ['name' => 'OPEN LOCK','category' => 'Uncategorized','emoji' => '🔓'],
        'U+1F514' => ['name' => 'BELL','category' => 'Uncategorized','emoji' => '🔔'],
        'U+1F516' => ['name' => 'BOOKMARK','category' => 'Uncategorized','emoji' => '🔖'],
        'U+1F517' => ['name' => 'LINK SYMBOL','category' => 'Uncategorized','emoji' => '🔗'],
        'U+1F518' => ['name' => 'RADIO BUTTON','category' => 'Uncategorized','emoji' => '🔘'],
        'U+1F519' => ['name' => 'BACK WITH LEFTWARDS ARROW ABOVE','category' => 'Uncategorized','emoji' => '🔙'],
        'U+1F51A' => ['name' => 'END WITH LEFTWARDS ARROW ABOVE','category' => 'Uncategorized','emoji' => '🔚'],
        'U+1F51B' => ['name' => 'ON WITH EXCLAMATION MARK WITH LEFT RIGHT ARROW ABOVE','category' => 'Uncategorized','emoji' => '🔛'],
        'U+1F51C' => ['name' => 'SOON WITH RIGHTWARDS ARROW ABOVE','category' => 'Uncategorized','emoji' => '🔜'],
        'U+1F51D' => ['name' => 'TOP WITH UPWARDS ARROW ABOVE','category' => 'Uncategorized','emoji' => '🔝'],
        'U+1F51E' => ['name' => 'NO ONE UNDER EIGHTEEN SYMBOL','category' => 'Uncategorized','emoji' => '🔞'],
        'U+1F51F' => ['name' => 'KEYCAP TEN','category' => 'Uncategorized','emoji' => '🔟'],
        'U+1F520' => ['name' => 'INPUT SYMBOL FOR LATIN CAPITAL LETTERS','category' => 'Uncategorized','emoji' => '🔠'],
        'U+1F521' => ['name' => 'INPUT SYMBOL FOR LATIN SMALL LETTERS','category' => 'Uncategorized','emoji' => '🔡'],
        'U+1F522' => ['name' => 'INPUT SYMBOL FOR NUMBERS','category' => 'Uncategorized','emoji' => '🔢'],
        'U+1F523' => ['name' => 'INPUT SYMBOL FOR SYMBOLS','category' => 'Uncategorized','emoji' => '🔣'],
        'U+1F524' => ['name' => 'INPUT SYMBOL FOR LATIN LETTERS','category' => 'Uncategorized','emoji' => '🔤'],
        'U+1F525' => ['name' => 'FIRE','category' => 'Uncategorized','emoji' => '🔥'],
        'U+1F526' => ['name' => 'ELECTRIC TORCH','category' => 'Uncategorized','emoji' => '🔦'],
        'U+1F527' => ['name' => 'WRENCH','category' => 'Uncategorized','emoji' => '🔧'],
        'U+1F528' => ['name' => 'HAMMER','category' => 'Uncategorized','emoji' => '🔨'],
        'U+1F529' => ['name' => 'NUT AND BOLT','category' => 'Uncategorized','emoji' => '🔩'],
        'U+1F52A' => ['name' => 'HOCHO','category' => 'Uncategorized','emoji' => '🔪'],
        'U+1F52B' => ['name' => 'PISTOL','category' => 'Uncategorized','emoji' => '🔫'],
        'U+1F52E' => ['name' => 'CRYSTAL BALL','category' => 'Uncategorized','emoji' => '🔮'],
        'U+1F52F' => ['name' => 'SIX POINTED STAR WITH MIDDLE DOT','category' => 'Uncategorized','emoji' => '🔯'],
        'U+1F530' => ['name' => 'JAPANESE SYMBOL FOR BEGINNER','category' => 'Uncategorized','emoji' => '🔰'],
        'U+1F531' => ['name' => 'TRIDENT EMBLEM','category' => 'Uncategorized','emoji' => '🔱'],
        'U+1F532' => ['name' => 'BLACK SQUARE BUTTON','category' => 'Uncategorized','emoji' => '🔲'],
        'U+1F533' => ['name' => 'WHITE SQUARE BUTTON','category' => 'Uncategorized','emoji' => '🔳'],
        'U+1F534' => ['name' => 'LARGE RED CIRCLE','category' => 'Uncategorized','emoji' => '🔴'],
        'U+1F535' => ['name' => 'LARGE BLUE CIRCLE','category' => 'Uncategorized','emoji' => '🔵'],
        'U+1F536' => ['name' => 'LARGE ORANGE DIAMOND','category' => 'Uncategorized','emoji' => '🔶'],
        'U+1F537' => ['name' => 'LARGE BLUE DIAMOND','category' => 'Uncategorized','emoji' => '🔷'],
        'U+1F538' => ['name' => 'SMALL ORANGE DIAMOND','category' => 'Uncategorized','emoji' => '🔸'],
        'U+1F539' => ['name' => 'SMALL BLUE DIAMOND','category' => 'Uncategorized','emoji' => '🔹'],
        'U+1F53A' => ['name' => 'UP-POINTING RED TRIANGLE','category' => 'Uncategorized','emoji' => '🔺'],
        'U+1F53B' => ['name' => 'DOWN-POINTING RED TRIANGLE','category' => 'Uncategorized','emoji' => '🔻'],
        'U+1F53C' => ['name' => 'UP-POINTING SMALL RED TRIANGLE','category' => 'Uncategorized','emoji' => '🔼'],
        'U+1F53D' => ['name' => 'DOWN-POINTING SMALL RED TRIANGLE','category' => 'Uncategorized','emoji' => '🔽'],
        'U+1F550' => ['name' => 'CLOCK FACE ONE OCLOCK','category' => 'Uncategorized','emoji' => '🕐'],
        'U+1F551' => ['name' => 'CLOCK FACE TWO OCLOCK','category' => 'Uncategorized','emoji' => '🕑'],
        'U+1F552' => ['name' => 'CLOCK FACE THREE OCLOCK','category' => 'Uncategorized','emoji' => '🕒'],
        'U+1F553' => ['name' => 'CLOCK FACE FOUR OCLOCK','category' => 'Uncategorized','emoji' => '🕓'],
        'U+1F554' => ['name' => 'CLOCK FACE FIVE OCLOCK','category' => 'Uncategorized','emoji' => '🕔'],
        'U+1F555' => ['name' => 'CLOCK FACE SIX OCLOCK','category' => 'Uncategorized','emoji' => '🕕'],
        'U+1F556' => ['name' => 'CLOCK FACE SEVEN OCLOCK','category' => 'Uncategorized','emoji' => '🕖'],
        'U+1F557' => ['name' => 'CLOCK FACE EIGHT OCLOCK','category' => 'Uncategorized','emoji' => '🕗'],
        'U+1F558' => ['name' => 'CLOCK FACE NINE OCLOCK','category' => 'Uncategorized','emoji' => '🕘'],
        'U+1F559' => ['name' => 'CLOCK FACE TEN OCLOCK','category' => 'Uncategorized','emoji' => '🕙'],
        'U+1F55A' => ['name' => 'CLOCK FACE ELEVEN OCLOCK','category' => 'Uncategorized','emoji' => '🕚'],
        'U+1F55B' => ['name' => 'CLOCK FACE TWELVE OCLOCK','category' => 'Uncategorized','emoji' => '🕛'],
        'U+1F5FB' => ['name' => 'MOUNT FUJI','category' => 'Uncategorized','emoji' => '🗻'],
        'U+1F5FC' => ['name' => 'TOKYO TOWER','category' => 'Uncategorized','emoji' => '🗼'],
        'U+1F5FD' => ['name' => 'STATUE OF LIBERTY','category' => 'Uncategorized','emoji' => '🗽'],
        'U+1F5FE' => ['name' => 'SILHOUETTE OF JAPAN','category' => 'Uncategorized','emoji' => '🗾'],
        'U+1F5FF' => ['name' => 'MOYAI','category' => 'Uncategorized','emoji' => '🗿'],
        'U+1F600' => ['name' => 'GRINNING FACE','category' => 'Additional emoticons','emoji' => '😀'],
        'U+1F607' => ['name' => 'SMILING FACE WITH HALO','category' => 'Additional emoticons','emoji' => '😇'],
        'U+1F608' => ['name' => 'SMILING FACE WITH HORNS','category' => 'Additional emoticons','emoji' => '😈'],
        'U+1F60E' => ['name' => 'SMILING FACE WITH SUNGLASSES','category' => 'Additional emoticons','emoji' => '😎'],
        'U+1F610' => ['name' => 'NEUTRAL FACE','category' => 'Additional emoticons','emoji' => '😐'],
        'U+1F611' => ['name' => 'EXPRESSIONLESS FACE','category' => 'Additional emoticons','emoji' => '😑'],
        'U+1F615' => ['name' => 'CONFUSED FACE','category' => 'Additional emoticons','emoji' => '😕'],
        'U+1F617' => ['name' => 'KISSING FACE','category' => 'Additional emoticons','emoji' => '😗'],
        'U+1F619' => ['name' => 'KISSING FACE WITH SMILING EYES','category' => 'Additional emoticons','emoji' => '😙'],
        'U+1F61B' => ['name' => 'FACE WITH STUCK-OUT TONGUE','category' => 'Additional emoticons','emoji' => '😛'],
        'U+1F61F' => ['name' => 'WORRIED FACE','category' => 'Additional emoticons','emoji' => '😟'],
        'U+1F626' => ['name' => 'FROWNING FACE WITH OPEN MOUTH','category' => 'Additional emoticons','emoji' => '😦'],
        'U+1F627' => ['name' => 'ANGUISHED FACE','category' => 'Additional emoticons','emoji' => '😧'],
        'U+1F62C' => ['name' => 'GRIMACING FACE','category' => 'Additional emoticons','emoji' => '😬'],
        'U+1F62E' => ['name' => 'FACE WITH OPEN MOUTH','category' => 'Additional emoticons','emoji' => '😮'],
        'U+1F62F' => ['name' => 'HUSHED FACE','category' => 'Additional emoticons','emoji' => '😯'],
        'U+1F634' => ['name' => 'SLEEPING FACE','category' => 'Additional emoticons','emoji' => '😴'],
        'U+1F636' => ['name' => 'FACE WITHOUT MOUTH','category' => 'Additional emoticons','emoji' => '😶'],
        'U+1F681' => ['name' => 'HELICOPTER','category' => 'Additional transport and map symbols','emoji' => '🚁'],
        'U+1F682' => ['name' => 'STEAM LOCOMOTIVE','category' => 'Additional transport and map symbols','emoji' => '🚂'],
        'U+1F686' => ['name' => 'TRAIN','category' => 'Additional transport and map symbols','emoji' => '🚆'],
        'U+1F688' => ['name' => 'LIGHT RAIL','category' => 'Additional transport and map symbols','emoji' => '🚈'],
        'U+1F68A' => ['name' => 'TRAM','category' => 'Additional transport and map symbols','emoji' => '🚊'],
        'U+1F68D' => ['name' => 'ONCOMING BUS','category' => 'Additional transport and map symbols','emoji' => '🚍'],
        'U+1F68E' => ['name' => 'TROLLEYBUS','category' => 'Additional transport and map symbols','emoji' => '🚎'],
        'U+1F690' => ['name' => 'MINIBUS','category' => 'Additional transport and map symbols','emoji' => '🚐'],
        'U+1F694' => ['name' => 'ONCOMING POLICE CAR','category' => 'Additional transport and map symbols','emoji' => '🚔'],
        'U+1F696' => ['name' => 'ONCOMING TAXI','category' => 'Additional transport and map symbols','emoji' => '🚖'],
        'U+1F698' => ['name' => 'ONCOMING AUTOMOBILE','category' => 'Additional transport and map symbols','emoji' => '🚘'],
        'U+1F69B' => ['name' => 'ARTICULATED LORRY','category' => 'Additional transport and map symbols','emoji' => '🚛'],
        'U+1F69C' => ['name' => 'TRACTOR','category' => 'Additional transport and map symbols','emoji' => '🚜'],
        'U+1F69D' => ['name' => 'MONORAIL','category' => 'Additional transport and map symbols','emoji' => '🚝'],
        'U+1F69E' => ['name' => 'MOUNTAIN RAILWAY','category' => 'Additional transport and map symbols','emoji' => '🚞'],
        'U+1F69F' => ['name' => 'SUSPENSION RAILWAY','category' => 'Additional transport and map symbols','emoji' => '🚟'],
        'U+1F6A0' => ['name' => 'MOUNTAIN CABLEWAY','category' => 'Additional transport and map symbols','emoji' => '🚠'],
        'U+1F6A1' => ['name' => 'AERIAL TRAMWAY','category' => 'Additional transport and map symbols','emoji' => '🚡'],
        'U+1F6A3' => ['name' => 'ROWBOAT','category' => 'Additional transport and map symbols','emoji' => '🚣'],
        'U+1F6A6' => ['name' => 'VERTICAL TRAFFIC LIGHT','category' => 'Additional transport and map symbols','emoji' => '🚦'],
        'U+1F6AE' => ['name' => 'PUT LITTER IN ITS PLACE SYMBOL','category' => 'Additional transport and map symbols','emoji' => '🚮'],
        'U+1F6AF' => ['name' => 'DO NOT LITTER SYMBOL','category' => 'Additional transport and map symbols','emoji' => '🚯'],
        'U+1F6B0' => ['name' => 'POTABLE WATER SYMBOL','category' => 'Additional transport and map symbols','emoji' => '🚰'],
        'U+1F6B1' => ['name' => 'NON-POTABLE WATER SYMBOL','category' => 'Additional transport and map symbols','emoji' => '🚱'],
        'U+1F6B3' => ['name' => 'NO BICYCLES','category' => 'Additional transport and map symbols','emoji' => '🚳'],
        'U+1F6B4' => ['name' => 'BICYCLIST','category' => 'Additional transport and map symbols','emoji' => '🚴'],
        'U+1F6B5' => ['name' => 'MOUNTAIN BICYCLIST','category' => 'Additional transport and map symbols','emoji' => '🚵'],
        'U+1F6B7' => ['name' => 'NO PEDESTRIANS','category' => 'Additional transport and map symbols','emoji' => '🚷'],
        'U+1F6B8' => ['name' => 'CHILDREN CROSSING','category' => 'Additional transport and map symbols','emoji' => '🚸'],
        'U+1F6BF' => ['name' => 'SHOWER','category' => 'Additional transport and map symbols','emoji' => '🚿'],
        'U+1F6C1' => ['name' => 'BATHTUB','category' => 'Additional transport and map symbols','emoji' => '🛁'],
        'U+1F6C2' => ['name' => 'PASSPORT CONTROL','category' => 'Additional transport and map symbols','emoji' => '🛂'],
        'U+1F6C3' => ['name' => 'CUSTOMS','category' => 'Additional transport and map symbols','emoji' => '🛃'],
        'U+1F6C4' => ['name' => 'BAGGAGE CLAIM','category' => 'Additional transport and map symbols','emoji' => '🛄'],
        'U+1F6C5' => ['name' => 'LEFT LUGGAGE','category' => 'Additional transport and map symbols','emoji' => '🛅'],
        'U+1F30D' => ['name' => 'EARTH GLOBE EUROPE-AFRICA','category' => 'Other additional symbols','emoji' => '🌍'],
        'U+1F30E' => ['name' => 'EARTH GLOBE AMERICAS','category' => 'Other additional symbols','emoji' => '🌎'],
        'U+1F310' => ['name' => 'GLOBE WITH MERIDIANS','category' => 'Other additional symbols','emoji' => '🌐'],
        'U+1F312' => ['name' => 'WAXING CRESCENT MOON SYMBOL','category' => 'Other additional symbols','emoji' => '🌒'],
        'U+1F316' => ['name' => 'WANING GIBBOUS MOON SYMBOL','category' => 'Other additional symbols','emoji' => '🌖'],
        'U+1F317' => ['name' => 'LAST QUARTER MOON SYMBOL','category' => 'Other additional symbols','emoji' => '🌗'],
        'U+1F318' => ['name' => 'WANING CRESCENT MOON SYMBOL','category' => 'Other additional symbols','emoji' => '🌘'],
        'U+1F31A' => ['name' => 'NEW MOON WITH FACE','category' => 'Other additional symbols','emoji' => '🌚'],
        'U+1F31C' => ['name' => 'LAST QUARTER MOON WITH FACE','category' => 'Other additional symbols','emoji' => '🌜'],
        'U+1F31D' => ['name' => 'FULL MOON WITH FACE','category' => 'Other additional symbols','emoji' => '🌝'],
        'U+1F31E' => ['name' => 'SUN WITH FACE','category' => 'Other additional symbols','emoji' => '🌞'],
        'U+1F332' => ['name' => 'EVERGREEN TREE','category' => 'Other additional symbols','emoji' => '🌲'],
        'U+1F333' => ['name' => 'DECIDUOUS TREE','category' => 'Other additional symbols','emoji' => '🌳'],
        'U+1F34B' => ['name' => 'LEMON','category' => 'Other additional symbols','emoji' => '🍋'],
        'U+1F350' => ['name' => 'PEAR','category' => 'Other additional symbols','emoji' => '🍐'],
        'U+1F37C' => ['name' => 'BABY BOTTLE','category' => 'Other additional symbols','emoji' => '🍼'],
        'U+1F3C7' => ['name' => 'HORSE RACING','category' => 'Other additional symbols','emoji' => '🏇'],
        'U+1F3C9' => ['name' => 'RUGBY FOOTBALL','category' => 'Other additional symbols','emoji' => '🏉'],
        'U+1F3E4' => ['name' => 'EUROPEAN POST OFFICE','category' => 'Other additional symbols','emoji' => '🏤'],
        'U+1F400' => ['name' => 'RAT','category' => 'Other additional symbols','emoji' => '🐀'],
        'U+1F401' => ['name' => 'MOUSE','category' => 'Other additional symbols','emoji' => '🐁'],
        'U+1F402' => ['name' => 'OX','category' => 'Other additional symbols','emoji' => '🐂'],
        'U+1F403' => ['name' => 'WATER BUFFALO','category' => 'Other additional symbols','emoji' => '🐃'],
        'U+1F404' => ['name' => 'COW','category' => 'Other additional symbols','emoji' => '🐄'],
        'U+1F405' => ['name' => 'TIGER','category' => 'Other additional symbols','emoji' => '🐅'],
        'U+1F406' => ['name' => 'LEOPARD','category' => 'Other additional symbols','emoji' => '🐆'],
        'U+1F407' => ['name' => 'RABBIT','category' => 'Other additional symbols','emoji' => '🐇'],
        'U+1F408' => ['name' => 'CAT','category' => 'Other additional symbols','emoji' => '🐈'],
        'U+1F409' => ['name' => 'DRAGON','category' => 'Other additional symbols','emoji' => '🐉'],
        'U+1F40A' => ['name' => 'CROCODILE','category' => 'Other additional symbols','emoji' => '🐊'],
        'U+1F40B' => ['name' => 'WHALE','category' => 'Other additional symbols','emoji' => '🐋'],
        'U+1F40F' => ['name' => 'RAM','category' => 'Other additional symbols','emoji' => '🐏'],
        'U+1F410' => ['name' => 'GOAT','category' => 'Other additional symbols','emoji' => '🐐'],
        'U+1F413' => ['name' => 'ROOSTER','category' => 'Other additional symbols','emoji' => '🐓'],
        'U+1F415' => ['name' => 'DOG','category' => 'Other additional symbols','emoji' => '🐕'],
        'U+1F416' => ['name' => 'PIG','category' => 'Other additional symbols','emoji' => '🐖'],
        'U+1F42A' => ['name' => 'DROMEDARY CAMEL','category' => 'Other additional symbols','emoji' => '🐪'],
        'U+1F465' => ['name' => 'BUSTS IN SILHOUETTE','category' => 'Other additional symbols','emoji' => '👥'],
        'U+1F46C' => ['name' => 'TWO MEN HOLDING HANDS','category' => 'Other additional symbols','emoji' => '👬'],
        'U+1F46D' => ['name' => 'TWO WOMEN HOLDING HANDS','category' => 'Other additional symbols','emoji' => '👭'],
        'U+1F4AD' => ['name' => 'THOUGHT BALLOON','category' => 'Other additional symbols','emoji' => '💭'],
        'U+1F4B6' => ['name' => 'BANKNOTE WITH EURO SIGN','category' => 'Other additional symbols','emoji' => '💶'],
        'U+1F4B7' => ['name' => 'BANKNOTE WITH POUND SIGN','category' => 'Other additional symbols','emoji' => '💷'],
        'U+1F4EC' => ['name' => 'OPEN MAILBOX WITH RAISED FLAG','category' => 'Other additional symbols','emoji' => '📬'],
        'U+1F4ED' => ['name' => 'OPEN MAILBOX WITH LOWERED FLAG','category' => 'Other additional symbols','emoji' => '📭'],
        'U+1F4EF' => ['name' => 'POSTAL HORN','category' => 'Other additional symbols','emoji' => '📯'],
        'U+1F4F5' => ['name' => 'NO MOBILE PHONES','category' => 'Other additional symbols','emoji' => '📵'],
        'U+1F500' => ['name' => 'TWISTED RIGHTWARDS ARROWS','category' => 'Other additional symbols','emoji' => '🔀'],
        'U+1F501' => ['name' => 'CLOCKWISE RIGHTWARDS AND LEFTWARDS OPEN CIRCLE ARROWS','category' => 'Other additional symbols','emoji' => '🔁'],
        'U+1F502' => ['name' => 'CLOCKWISE RIGHTWARDS AND LEFTWARDS OPEN CIRCLE ARROWS WITH CIRCLED ONE OVERLAY','category' => 'Other additional symbols','emoji' => '🔂'],
        'U+1F504' => ['name' => 'ANTICLOCKWISE DOWNWARDS AND UPWARDS OPEN CIRCLE ARROWS','category' => 'Other additional symbols','emoji' => '🔄'],
        'U+1F505' => ['name' => 'LOW BRIGHTNESS SYMBOL','category' => 'Other additional symbols','emoji' => '🔅'],
        'U+1F506' => ['name' => 'HIGH BRIGHTNESS SYMBOL','category' => 'Other additional symbols','emoji' => '🔆'],
        'U+1F507' => ['name' => 'SPEAKER WITH CANCELLATION STROKE','category' => 'Other additional symbols','emoji' => '🔇'],
        'U+1F509' => ['name' => 'SPEAKER WITH ONE SOUND WAVE','category' => 'Other additional symbols','emoji' => '🔉'],
        'U+1F515' => ['name' => 'BELL WITH CANCELLATION STROKE','category' => 'Other additional symbols','emoji' => '🔕'],
        'U+1F52C' => ['name' => 'MICROSCOPE','category' => 'Other additional symbols','emoji' => '🔬'],
        'U+1F52D' => ['name' => 'TELESCOPE','category' => 'Other additional symbols','emoji' => '🔭'],
        'U+1F55C' => ['name' => 'CLOCK FACE ONE-THIRTY','category' => 'Other additional symbols','emoji' => '🕜'],
        'U+1F55D' => ['name' => 'CLOCK FACE TWO-THIRTY','category' => 'Other additional symbols','emoji' => '🕝'],
        'U+1F55E' => ['name' => 'CLOCK FACE THREE-THIRTY','category' => 'Other additional symbols','emoji' => '🕞'],
        'U+1F55F' => ['name' => 'CLOCK FACE FOUR-THIRTY','category' => 'Other additional symbols','emoji' => '🕟'],
        'U+1F560' => ['name' => 'CLOCK FACE FIVE-THIRTY','category' => 'Other additional symbols','emoji' => '🕠'],
        'U+1F561' => ['name' => 'CLOCK FACE SIX-THIRTY','category' => 'Other additional symbols','emoji' => '🕡'],
        'U+1F562' => ['name' => 'CLOCK FACE SEVEN-THIRTY','category' => 'Other additional symbols','emoji' => '🕢'],
        'U+1F563' => ['name' => 'CLOCK FACE EIGHT-THIRTY','category' => 'Other additional symbols','emoji' => '🕣'],
        'U+1F564' => ['name' => 'CLOCK FACE NINE-THIRTY','category' => 'Other additional symbols','emoji' => '🕤'],
        'U+1F565' => ['name' => 'CLOCK FACE TEN-THIRTY','category' => 'Other additional symbols','emoji' => '🕥'],
        'U+1F566' => ['name' => 'CLOCK FACE ELEVEN-THIRTY','category' => 'Other additional symbols','emoji' => '🕦'],
        'U+1F567' => ['name' => 'CLOCK FACE TWELVE-THIRTY','category' => 'Other additional symbols','emoji' => '🕧']
    ];

    /**
     * u2entity
     *
     * @param string $u
     * @return string
     */
    public static function u2entity(string $u): string
    {
        return str_replace('U+', '&#x', $u) . ';';
    }
}
